### ISSUE TITLE
AutomaticKeepAliveClientMixin for HookWidget?

### ISSUE THREAD

**Issue by zaralockheart** [rrousselGit/flutter_hooks#101]
Hi, Thanks for the great library. Can I know if there's any way I can use `AutomaticKeepAliveClientMixin` for widget that extends `HookWidget`?

**Comment by rrousselGit** [comment]
No. On the other hand, you can copy its implementation and make it a `useAutomaticKeepAlive` hook.

**Comment by zaralockheart** [comment]
:( I really hope there is plan for this. Anyway thanks! :D

**Comment by xantiagoma** [comment]
@rrousselGit  Any update about this? or how should be the implementation for `useAutomaticKeepAlive`?

**Comment by DevNico** [comment]
I wrote a hook that seems to work as far as I tested.
```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

void useAutomaticKeepAlive({
  bool wantKeepAlive,
}) =>
    use(_AutomaticKeepAliveHook(
      wantKeepAlive: wantKeepAlive ?? true,
    ));

class _AutomaticKeepAliveHook extends Hook<void> {
  final bool wantKeepAlive;

  _AutomaticKeepAliveHook({this.wantKeepAlive});

  @override
  HookState<void, _AutomaticKeepAliveHook> createState() => _AutomaticKeepAliveHookState();
}

class _AutomaticKeepAliveHookState extends HookState<void, _AutomaticKeepAliveHook> {
  KeepAliveHandle _keepAliveHandle;

  void _ensureKeepAlive() {
    assert(_keepAliveHandle == null);
    _keepAliveHandle = KeepAliveHandle();
    KeepAliveNotification(_keepAliveHandle).dispatch(context);
  }

  void _releaseKeepAlive() {
    _keepAliveHandle.release();
    _keepAliveHandle = null;
  }

  void updateKeepAlive() {
    if (hook.wantKeepAlive) {
      if (_keepAliveHandle == null) _ensureKeepAlive();
    } else {
      if (_keepAliveHandle != null) _releaseKeepAlive();
    }
  }

  @override
  void initHook() {
    super.initHook();
    if (hook.wantKeepAlive) _ensureKeepAlive();
  }

  @override
  void build(BuildContext context) {
    if (hook.wantKeepAlive && _keepAliveHandle == null) _ensureKeepAlive();
    return null;
  }

  @override
  void deactivate() {
    if (_keepAliveHandle != null) _releaseKeepAlive();
    super.deactivate();
  }

  @override
  Object get debugValue => _keepAliveHandle;

  @override
  String get debugLabel => 'useAutomaticKeepAlive';
}
```

**Comment by jnknewaj** [comment]
> I wrote a hook that seems to work as far as I tested.
> 
> ```dart
> import 'package:flutter/widgets.dart';
> import 'package:flutter_hooks/flutter_hooks.dart';
> 
> void useAutomaticKeepAlive({
>   bool wantKeepAlive,
> }) =>
>     use(_AutomaticKeepAliveHook(
>       wantKeepAlive: wantKeepAlive ?? true,
>     ));
> 
> class _AutomaticKeepAliveHook extends Hook<void> {
>   final bool wantKeepAlive;
> 
>   _AutomaticKeepAliveHook({this.wantKeepAlive});
> 
>   @override
>   HookState<void, _AutomaticKeepAliveHook> createState() => _AutomaticKeepAliveHookState();
> }
> 
> class _AutomaticKeepAliveHookState extends HookState<void, _AutomaticKeepAliveHook> {
>   KeepAliveHandle _keepAliveHandle;
> 
>   void _ensureKeepAlive() {
>     assert(_keepAliveHandle == null);
>     _keepAliveHandle = KeepAliveHandle();
>     KeepAliveNotification(_keepAliveHandle).dispatch(context);
>   }
> 
>   void _releaseKeepAlive() {
>     _keepAliveHandle.release();
>     _keepAliveHandle = null;
>   }
> 
>   void updateKeepAlive() {
>     if (hook.wantKeepAlive) {
>       if (_keepAliveHandle == null) _ensureKeepAlive();
>     } else {
>       if (_keepAliveHandle != null) _releaseKeepAlive();
>     }
>   }
> 
>   @override
>   void initHook() {
>     super.initHook();
>     if (hook.wantKeepAlive) _ensureKeepAlive();
>   }
> 
>   @override
>   void build(BuildContext context) {
>     if (hook.wantKeepAlive && _keepAliveHandle == null) _ensureKeepAlive();
>     return null;
>   }
> 
>   @override
>   void deactivate() {
>     if (_keepAliveHandle != null) _releaseKeepAlive();
>     super.deactivate();
>   }
> 
>   @override
>   Object get debugValue => _keepAliveHandle;
> 
>   @override
>   String get debugLabel => 'useAutomaticKeepAlive';
> }
> ```

@DevNico , Ok, `final alive = useAutomaticKeepAlive(wantKeepAlive: true);` Now where to use it?

**Comment by DevNico** [comment]
Just use it in the widget you want to be kept alive. The return value can be ignored.

**Comment by Agondev** [comment]
> I wrote a hook that seems to work as far as I tested.
> 
> ```dart
> import 'package:flutter/widgets.dart';
> import 'package:flutter_hooks/flutter_hooks.dart';
> 
> void useAutomaticKeepAlive({
>   bool wantKeepAlive,
> }) =>
>     use(_AutomaticKeepAliveHook(
>       wantKeepAlive: wantKeepAlive ?? true,
>     ));
> 
> class _AutomaticKeepAliveHook extends Hook<void> {
>   final bool wantKeepAlive;
> 
>   _AutomaticKeepAliveHook({this.wantKeepAlive});
> 
>   @override
>   HookState<void, _AutomaticKeepAliveHook> createState() => _AutomaticKeepAliveHookState();
> }
> 
> class _AutomaticKeepAliveHookState extends HookState<void, _AutomaticKeepAliveHook> {
>   KeepAliveHandle _keepAliveHandle;
> 
>   void _ensureKeepAlive() {
>     assert(_keepAliveHandle == null);
>     _keepAliveHandle = KeepAliveHandle();
>     KeepAliveNotification(_keepAliveHandle).dispatch(context);
>   }
> 
>   void _releaseKeepAlive() {
>     _keepAliveHandle.release();
>     _keepAliveHandle = null;
>   }
> 
>   void updateKeepAlive() {
>     if (hook.wantKeepAlive) {
>       if (_keepAliveHandle == null) _ensureKeepAlive();
>     } else {
>       if (_keepAliveHandle != null) _releaseKeepAlive();
>     }
>   }
> 
>   @override
>   void initHook() {
>     super.initHook();
>     if (hook.wantKeepAlive) _ensureKeepAlive();
>   }
> 
>   @override
>   void build(BuildContext context) {
>     if (hook.wantKeepAlive && _keepAliveHandle == null) _ensureKeepAlive();
>     return null;
>   }
> 
>   @override
>   void deactivate() {
>     if (_keepAliveHandle != null) _releaseKeepAlive();
>     super.deactivate();
>   }
> 
>   @override
>   Object get debugValue => _keepAliveHandle;
> 
>   @override
>   String get debugLabel => 'useAutomaticKeepAlive';
> }
> ```

For anyone looking for this post NNBD:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

void useAutomaticKeepAlive({
  bool? wantKeepAlive,
}) =>
    use(
      _AutomaticKeepAliveHook(
        wantKeepAlive: wantKeepAlive ?? true,
      ),
    );

class _AutomaticKeepAliveHook extends Hook<void> {
  final bool wantKeepAlive;

  const _AutomaticKeepAliveHook({required this.wantKeepAlive});

  @override
  HookState<void, _AutomaticKeepAliveHook> createState() =>
      _AutomaticKeepAliveHookState();
}

class _AutomaticKeepAliveHookState
    extends HookState<void, _AutomaticKeepAliveHook> {
  KeepAliveHandle? _keepAliveHandle;

  void _ensureKeepAlive() {
    _keepAliveHandle = KeepAliveHandle();
    KeepAliveNotification(_keepAliveHandle!).dispatch(context);
  }

  void _releaseKeepAlive() {
    _keepAliveHandle!.release();
    _keepAliveHandle = null;
  }

  void updateKeepAlive() {
    if (hook.wantKeepAlive) {
      if (_keepAliveHandle == null) _ensureKeepAlive();
    } else {
      if (_keepAliveHandle != null) _releaseKeepAlive();
    }
  }

  @override
  void initHook() {
    super.initHook();
    if (hook.wantKeepAlive) _ensureKeepAlive();
  }

  @override
  void build(BuildContext context) {
    if (hook.wantKeepAlive && _keepAliveHandle == null) _ensureKeepAlive();
    return;
  }

  @override
  void deactivate() {
    if (_keepAliveHandle != null) _releaseKeepAlive();
    super.deactivate();
  }

  @override
  Object get debugValue => _keepAliveHandle!;

  @override
  String get debugLabel => 'useAutomaticKeepAlive';
}
```

**Comment by DmitrySboychakov** [comment]
@[rrousselGit](https://github.com/rrousselGit) could you consider taking above upstream?

**Comment by rrousselGit** [comment]
Sure.

Happy to review a PR 😄

**Comment by DevNico** [comment]
I'll go ahead and submit that PR soon since I wrote that code initially. 😄

**Comment by DevNico** [comment]
I'll go ahead and submit that PR soon since I wrote that code initially. 😄
