### ISSUE TITLE
MVC using hooks and provider

### ISSUE THREAD

**Issue by NourEldinShobier** [rrousselGit/flutter_hooks#102]
Hi, I'm new to hooks and need a little help... Basically what I'm trying to do is to separate events ...etc from the UI using this approach

`page.view.dart`
```
class PageX extends HookWidget {
  PageX({Key key}) : super(key: key);

  var page = PageXController();

  Widget build(BuildContext context) {
    page.init();

    return Provider<PageXController>.value(
      child: _PageBody(),
      value: page,
    );
  }
}

class _PageBody extends HookWidget {
  _PageBody({Key key}) : super(key: key);
  Widget build(BuildContext context) {
    var page = Provider.of<PageXController>(context);

    return Container(child: Text(page.name.value),);
  }
}
```

`page.controller.dart`
```
class PageXController {
  var name = useState('Nour');

  void init() {}
}
```

later on I figured out that I can use `useState()` only inside the build method, so is there any way to overcome this problem

thanks in advance

**Comment by MahdiPishguy** [comment]
+1

**Comment by GregorySech** [comment]
I'm new too and I'm really confused about this. I've looked at this example: https://github.com/rrousselGit/flutter_hooks/blob/master/example/lib/use_effect.dart and maybe the best way to separate business logic from a view is to create one or more custom hooks. 

My instinct is telling me to reduce the number of hooks per view as much as possible as I'm really afraid of future refactoring when using a lot of "basic" hooks inside my views.

Using other hooks inside custom hooks is possible so it might be really clean. The `useEffect` hook seems to work quite well if we need to interface with our app model (services + data).

I might be wrong but my conclusion is that using hooks as MVC's controllers is the safe play.

**Comment by rrousselGit** [comment]
It's not possible and never will be possible to use hooks outside of widgets.
Hooks are built specifically for widgets. 

If you do not want the widget dependency, you'll need something other than hooks.
