### ISSUE TITLE
Q: Very curious if folks are finding this as useful as it sounds ...

### ISSUE THREAD

**Issue by aktxyz** [rrousselGit/flutter_hooks#104]
I love the hook stuff in react, and this looks very nice too ... just wary of the "sounds too good to be true" thing ... any thoughts from folks that have used this heavily?

**Comment by PavelPZ** [comment]
I am using it in my private project. It works really great (in combination with another excellent @rrousselGit packages as a [provider](https://pub.dev/packages/provider) or [functional_widget](https://github.com/rrousselGit/functional_widget)).

**Comment by wstrange** [comment]
I'm curious about this as well.  I'm not terribly happy about all the boilerplate with solutions like Bloc -and hooks seems like far less ceremony.

It would be nice to see endorsement of hooks from the Flutter team  (I know there is an issue tracking this). 

It is not clear to me how hooks relates to things like mobx, which I know that @rrousselGit is also involved with. 

WIth mobx, I need to declare a backing store class for each of my widgets.  For hooks, it seems like I can just inline a few `useStream`, `useFuture`, etc.right in my HookWidget - which further cuts down on boilerplate. Am I missing something? Does it makes sense to use both mobx and hooks, or can hooks essentially replace mobx with less boilerplate?

**Comment by aktxyz** [comment]
wow ... I hesitated posting this non-issue question ... but the functional widget lead was worth it !

**Comment by rrousselGit** [comment]
If you're familiar with React Hooks, then they are (almost) the same.
The few differences are mainly language specific (had to use code generator to make widgets as functions).

In fact, it's this library that inspired the support of hot reload for the real React Hooks. 😘

On the other hand, this flutter implementation falls short in term of tooling. 
There's currently no eslint equivalent for Flutter hooks (which is the reason why I don't talk too much about them).


I'm thinking about it though. I'll try to make one in the coming months.

**Comment by aktxyz** [comment]
this is really great ... I am just scratching the surface but already love it ... so many things seem to add boiler plate and I love stuff that removes it

**Comment by smiLLe** [comment]
best lib for flutter  IMO.

**Comment by spiralni** [comment]
Already using it together with functional_wiget, still learning but definitively it's in my toolbelt.

**Comment by cgestes** [comment]
love it, it removes boilerplate :)

**Comment by derolf** [comment]
We are using it heavily, but there are some pitfalls. Especially annoying is that the destruction order isn’t reverse to construction, which leads to some hacks in our codebase.

**Comment by cgestes** [comment]
The more I use it the more I would like the hooks values to be accessible from the class.

I usually have widgets like that:
```
class MyWidget extends HookWidget {

  const MyWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final state1Val = useState(...);
    final state2Val = useState(...);

    switch (stateVal.value) {
      case A:
        return _buildA(context, state1Val, state2Val);
      case B:
        return _buildB(context, state1Val, state2Val);
    }
  }
}
```

Same with callbacks, I have to pass the states down all functions.

Tried to experiment with putting all the hooks related function in a buildState function but I wasn't really satisfied, as dart data class are pretty verbose!


I believe that in React hooks are designed with functional component in mind more than with classes.

Maybe we have something to gain by improving the design for classes.

PS: I can open a new issue for discussion if you prefer @rrousselGit

**Comment by rrousselGit** [comment]
Sure, feel free to open an issue

**Comment by cgestes** [comment]
Done: https://github.com/rrousselGit/flutter_hooks/issues/112

**Comment by rrousselGit** [comment]
With my recent release of `Freezed`, I think hooks are more useful than before.\
Freezed makes `useState` drastically more powerful.

It may make me spend a bit more energy on flutter_hooks

**Comment by rrousselGit** [comment]
Anyway, closing this 😄
