### ISSUE TITLE
Any way to check value when parent widget rebuilds

### ISSUE THREAD

**Issue by spiralni** [rrousselGit/flutter_hooks#105]
Using `StatefulWidget` am able  to know if a new parameter was passed into the widget by doing:

`  @override
  void didUpdateWidget(Widget oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (oldWidget.selectedIndex != widget.selectedIndex) {
      _selectedIndex = widget.selectedIndex;
    }
  }`

Is therea any way I can achieve this using hooks?

**Comment by smiLLe** [comment]
can you tell us more about what you are trying to do?

**Comment by spiralni** [comment]
Thanks for replying. @smiLLe 

I just try to rebuild my stateful widget (child) when the parent widget changes.

```
ParentWidget
  |
  |------ChildWidget (stateful)

```
Every time my ParentWidget changes, I need to notify the children about this change, the problem is I dont know how to do it with hooks.

I can achive this using StatefulWidget class, as stated in the official documentation https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html

**Comment by spiralni** [comment]
oooooh, it was easier than I thought!

First I just need to init an empty state and then accept the value that comes in the parameter.
 
```
@hwidget
Widget logsList(List<int> list) {

final _list = useState<List<int>>(); // init as empty
_list.value = list; // accept the value parameter has passed

........
}

```

The problem was I was expecting the value of the state changes by itself by just initializing the list once, e.g:

```
@hwidget
Widget logsList(List<int> list) {

final _list = useState<List<int>>(list); // init once,  _list doesnt change even if the "list" parameter changes.
........
}

```
