### ISSUE TITLE
assertion: _currentHook.current != null

### ISSUE THREAD

**Issue by cgestes** [rrousselGit/flutter_hooks#110]
Any idea why I would end up triggering this assertion?

```
Assertion failed: org-dartlang-app:///packages/flutter_hooks/src/framework.dart:407:16
_currentHook.current != null
is not true
```
Thanks :)

**Comment by rrousselGit** [comment]
Sounds like you broke the "never add hooks in a if" rule, or need a key on your widgets

**Comment by cgestes** [comment]
I did.

I have a base widget responsible for authentication state, calling an overridden function only if authenticated.

Thanks, I will rework my code.

Btw, why can't I add new hooks after the first render?

**Comment by rrousselGit** [comment]
Theorically, it's feasible. But it's to match React for now.

Maybe in the future it will change

**Comment by cgestes** [comment]
Ok. thank you for the quick answers :)
