### ISSUE TITLE
Explicitly use setState

### ISSUE THREAD

**Issue by wurikiji** [rrousselGit/flutter_hooks#111]
# Current code - simple version

For some reason, I want to explicitly call `setState` outside of the `build` method. 
 
```dart
var _setState;

class TT extends HookWidget with WidgetsBindingObserver {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      _someGlobalResetter();
     _setState.value++; // to rebuild this widget
    }
  }

  @override
  Widget build(BuildContext context) {    
    useEffect(() {
      WidgetsBinding.instance.addObserver(this);
      return () {
        WidgetsBinding.instance.removeObserver(this);
      };
    });
    _setState = useState(0);
    return SomeWidget();
  }
}
```

# Question

Is there any better way instead of using a global variable?
If I rewrite this code to my own `StatefulWidget`, the code is going to be long lines. So I want to solve this problem in the scope of `HookWidget`.

**Comment by simolus3** [comment]
I might be missing something obvious, but couldn't you just make `_setState` a field in the `TT` class?

If you need to update `_setState` outside of the `TT` widget, you could move it up the widget tree, for instance by making some parent widget create a `ChangeNotifier` and passing it down via `Provider`.

**Comment by rrousselGit** [comment]
Instead of making `HookWidget` implement `WidgetsBindingObserver`, make a custom `useWidgetsBindingObserver` hook:

```dart
Widget build(context) {
  final state = useState(0);
  useWidgetsBindingObserver(
    didChangeAppLifecycleState: (appState) {
      if (appState == AppLifecycleState.resumed) {
        state.value++;
      }
    },
  );
}
```

**Comment by wurikiji** [comment]
Thanks all! I will implement custom hook.

**Comment by Ferdzzzzzzzz** [comment]
@wurikiji did you implement this hook? I tried an implementation that seems to get the job done: https://github.com/Ferdzzzzzzzz/custom_flutter_hooks

**Comment by atereshkov** [comment]
Could anyone please share custom hook to use WidgetsBindingObserver? Or point where I can get info related to creating custom hooks..

**Comment by Ferdzzzzzzzz** [comment]
@atereshkov I seem to have misplaced my implementation for this hook, but [this](https://resocoder.com/2020/01/21/flutter-hooks-hide-fab-animation-100-widget-code-reuse/) is a great tutorial for creating custom hooks 👍

**Comment by callmejm** [comment]
can anyone share the code of `useWidgetsBindingObserver` hook , it will be helpful

**Comment by jiggum** [comment]
Here is implementation of `useAppLifecycleState` (Same purpose as `useWidgetsBindingObserver`, but limited to `didChangeAppLifecycleState`)

```dart
typedef TAppLifecycleListener = void Function(AppLifecycleState state);

class _AppLifecycleStateObserver extends WidgetsBindingObserver {
  _AppLifecycleStateObserver(this._appLifecycleListener);

  final TAppLifecycleListener _appLifecycleListener;

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    _appLifecycleListener(state);
  }
}

void useAppLifecycleState(TAppLifecycleListener onChangeListener) {
  useEffect(() {
    final observer = _AppLifecycleStateObserver(onChangeListener);
    WidgetsBinding.instance.addObserver(observer);
    return () => WidgetsBinding.instance.removeObserver(observer);
  }, [onChangeListener]);
}
```
