### ISSUE TITLE
useDetached to create an independent hook context

### ISSUE THREAD

**Issue by derolf** [rrousselGit/flutter_hooks#113]
I‘d like to have:

`void useDetached(VoidCallback callback, List<dynamic> keys);`

It should create a new child hook context that re-builds independently from the current context, but is attached to the lifecycle of the current context.

`callback` Is the function that is called whenever the child context is rebuilt. It can use hooks which are only triggering in the child context, but not the current context.

This way, we can have “background-operations”.

If a key in `keys` change, the child context is destroyed and recreated.

Currently, this behavior can be “emulated” by using a `Stack` with an invisible `HookBuilder` that provides the independent child context. But that is rather a dirty hack.

**Comment by rrousselGit** [comment]
Do you have a concrete use-case example?
Currently you should be able to use HookBuilder for something roughly similar

**Comment by derolf** [comment]
I find hooks quite useful also outside of traditional widget building, but for background logic running. 

One example could be a background operation that centrally listens to a geoposition-listenable to update some current-roadname-listenable.

For that, you could use an rx-stream that pumps the data from one observable into a broadcast behavior subject. But, hooks could serve the same purpose if we could make them run detached, but they could still use then widget tree to resolve dependencies (via Provider etc.).

**Comment by derolf** [comment]
Another usecase is denouncing a Listenable. Our current implementation (ported from useDebounce in React), still causes the context to rebuild with every update of the Listenable.

If we hand useDetached, we could encapsulate the debounce logic inside a child context and update the outer context via a useState-obtained notifier.

The child context would always rebuild, but the outer context only if you emit a debounced value.

**Comment by rrousselGit** [comment]
That's an interesting idea.
It's quite a big feature, with a certain complexity.

I'm not sure that it's truly worth it. I don't see myself working on this any time soon. I'd prefer to work on devtools for hooks instead. 

PRs are welcome though.

**Comment by sesam** [comment]
Hm, if I'd want a useTimeout or useInterval would this be enough to cover that? Or would that require a more strongly detached kind of state, maybe more like a recoil `atom`?

**Comment by rrousselGit** [comment]
A timeout is unrelated to this

A useEffect+useMemo should be enough

**Comment by rrousselGit** [comment]
Closing as I have no plan to work on this at the moment.
