### ISSUE TITLE
Provide mechanism to observe didChangeDependencies

### ISSUE THREAD

**Issue by derolf** [rrousselGit/flutter_hooks#115]
State.didChangeDependencies allows to make use of inherited widgets and react accordingly if something changed.

Provide a way to forward didChangeDependencies into HookState so that HookState can use inherited widgets outside of build.

Use-case: Bind a Hook to RouteAware which requires obtaining ModelRoute.of and subscribing to some RouteObserver.

**Comment by misha** [comment]
In my case, I only needed to know when I am on/not on the current route. I ended up with the following in my widget:

```dart
final _onCurrentRoute = ModalRoute.of(context).isCurrent;
final _previousOnCurrentRoute = usePrevious(_onCurrentRoute);

if (_previousOnCurrentRoute != _onCurrentRoute) {
  // React to route change.
}
```

Posting in case this is enough for your use case, but it would be great to have access to `ModalRoute.of` in hooks.

**Comment by derolf** [comment]
@misha I found out that ModalRoute.of does not always react to changes of current. This is why I wrote a hook that uses RouteObserver.

**Comment by misha** [comment]
I haven't seen anything wrong with it yet myself. Do you have an example where it breaks?

There's also another value called `isActive` that seems to change at a slightly different time than `isCurrent`;

**Comment by derolf** [comment]
I know the difference between isCurrent and isActive. As said, we saw some bugs due to unreliable behavior. I think there was no trigger when switching form isCurrent true to false. This is why we created a hook with RouteObserver.

**Comment by rrousselGit** [comment]
To be honest with the recent changes on `master` channel, didChangeDependencies and build are almost identical.

Not sure if it's really needed
