### ISSUE TITLE
How to use class as InitialState when using useState ?

### ISSUE THREAD

**Issue by sessionboy** [rrousselGit/flutter_hooks#116]
Hi. 
I am exploring how to use flutter_hooks to centrally manage the state of widgets, including local state, subscriptions, data fetching, and more.
I want to be as concise as possible, so I don't want to use state managers like fish_redux, bloc, etc.

I have used some great state managers, and [react-model](https://github.com/byte-fe/react-model) is one of them. I want to implement it using flutter_hooks in flutter.

I will create a class as the model of the widget, centrally manage the state of the widget, including data fetching, etc.
```js
class WidgetModel {
  int _count = 0;
  int get count => _count;

  void increment(){
    _count++;
  }
}
```
I want to use the above model with useState.
```js
useStore () {
  final state = useState(WidgetModel);
  ...
}
```
But I am confused, I don't know how to update the state.

I want to achieve the following:
```js
class App extends HookWidget {
  @override
  Widget build(BuildContext context) {
    const model = useStore(WidgetModel);
    return Column(
      children: <Widget>[
        Text("current count is: ${ model.count }"),
        IconButton(
          icon: Icon(Icons.add_circle),
          onPressed: ()=>{
             model.add();
          },
        )
      ],
    );
  }
}
```

**Comment by smiLLe** [comment]
For example, your WidgetModel can extend ValueNotifier and instead of useStore, you'd then use useValueNotifier :)

**Comment by rrousselGit** [comment]
Sorry for the late reply.

This seems to be more of a question than a problem, so if you still have an issue with this I'd suggest asking it on StackOverflow (where I am more active).
