### ISSUE TITLE
Provide a function `shouldResetHooks` on `HookWidget`

### ISSUE THREAD

**Issue by derolf** [rrousselGit/flutter_hooks#117]
Assume you have a HookWidget like:

```
class Foo extends HookWidget {
  final List<Promise> promises;
  ...
}
```

in the `build` function, we now use `usePromise` for all the `promises`, hence we need a loop. If the length of the list changes, the app "crashes".

Currently, there is no way to invalidate the whole `HookWidget`'s state. It would be nice to have a function to be able to reset all hooks.

**Comment by smiLLe** [comment]
I think with ``` Promise ``` you mean a ```Future``` and i assume you want to wait until all futues have been completed?

```dart
class MyClass extends HookWidget {
final List<Future> futures;
MyClass(this.futures);

Widget build(BuiltContext context) {
  final waitForAll = useMemoized(() => Future.wait(futures), [futures]);
  final snapshot = usePromise(waitForAll);
  }
}
```

**Comment by derolf** [comment]
Yes, I meant Future. Mixing languages...

However, I want to access individuals Futures one-by-one as soon as they resolve and not wait for all.

**Comment by rrousselGit** [comment]
> Yes, I meant Future. Mixing languages...
> 
> However, I want to access individuals Futures one-by-one as soon as they resolve and not wait for all.

Could you still use useMemoized, just with a different implementation instead of Future.all?

**Comment by derolf** [comment]
@rrousselGit could you please elaborate on that?

**Comment by rrousselGit** [comment]
Something like:

```dart
useEffect(() {
  futures[0].then((value) {

  });
  futures[1].then((value) {

  });
}, [futures]);
```
