### ISSUE TITLE
Why no initState?

### ISSUE THREAD

**Issue by esDotDev** [rrousselGit/flutter_hooks#122]
I'm a bit confused why there is no equivalent of the initState fxn. If I had an animation and wanted it to play from 0 to 1, only once, when the widget is first created, how would I do that? I can see how you could use a custom isFirstBuild state value, but that seems kinda hacky compared to just having a dedicated init fxn. Am I missing something?

**Comment by sahandevs** [comment]
you can use `useEffect`
```dart
useEffect(() {
  // init state code
  return () {
     // your dispose code
   };
}, []);
```

also you can use `initHook` instead if you are making a custom class hook.

**Comment by esDotDev** [comment]
Ah interesting, thx! According to docs, it looks like I need to use a key to get this behavior?

_By default effect is called on every HookWidget.build call, unless keys is specified. In which case, effect is called once on the first useEffect call and whenever something within keys change/_

**Comment by rrousselGit** [comment]
One of the goals of hooks is to have a declarative code.
You _could_ have an `initState` hook, but that'd lead to something imperative

In any case, you can make one yourself if you want to, by subclassing `Hook`/`HookState`

**Comment by esDotDev** [comment]
Just to make a last ditch argument, this library pitches itself as a complete replacement for Stateful widget, and then doesn't provide a straightforward way to _initState_. Doesn't make any sense to me. Probably 30% of the time I'm using a Stateful, I'm using the initState hook. For example, many of my views fire off a update request when they first load, just to ensure they have the latest data. 

Seems like we're letting purity get in the way of pragmatism here. Being able to mix the declarative and imperative in a clean way, gives the most power and flexibility. The whole point of hooks is to replace boilerplate, but then it forces boilerplate for such a common use case, just because of a concern over purity?

**Comment by rrousselGit** [comment]
> Just to make a last ditch argument, this library pitches itself as a complete replacement for Stateful widget, and then doesn't provide a straightforward way to initState or dispose

That's what `useEffect` does.

**Comment by esDotDev** [comment]
Ok, thanks. I wasn't sure if that was the recommended approach for this or just a 'hack'. Definitely not as readable/explicit as I would hope, but it is nice and succinct :)

**Comment by esDotDev** [comment]
Sorry, I understand much better after using it for a bit. I think I'm in love :)

**Comment by f-person** [comment]
Shouldn't it be easier for first-time hooks users to understand this? For example write that they can use `useEffect` for achieving the behavior expected from `initState`.

**Comment by venkatd** [comment]
The difference between `useEffect(..., [])` and `useEffect(...)` may not be obvious to beginners. I think the difference between passing `[]` or nothing is too subtle.

I ended up adding my own helper to avoid confusion.

```import 'package:flutter_hooks/flutter_hooks.dart';

void useInit(void Function() init) {
  useEffect(() {
    init();
    return null;
  }, []);
}
```

**Comment by rrousselGit** [comment]
The problem is, this is a bad practice.  
With hooks, you're not supposed to think in life-cycles such as "on init".

StatefulWidgets = imperative
Hooks = declarative

An alternate solution would be instead to make the array of dependency required

**Comment by esDotDev** [comment]
This is just not pragmatic thinking. In designs that are highly dynamic, with cool effects and moving parts, you very often need setup code when a state is first initialized, so why pretend otherwise and then end up with less readable less maintainable code. Just too black and white in the thinking.

I posted this in the flutter issue on state management, but I totally agree, the "magic" in this statement is way over the top and serving no purpose but to obfuscate:
```
 useEffect(() {
    init();
    return null;
  }, []);
  ```
  The return is `dispose()`, but thats not clear. `[]` means don't rebuild, but `` would mean always rebuild, also not clear.

**Comment by f-person** [comment]
Now I don't have any problems with using hooks, I use them a lot, I love them. But when I wanted to try them out, I was really confused about the "hooks way" of doing `initState`. I think this can be at least explained better in the README.

**Comment by venkatd** [comment]
I agree declarative is much easier for me to think about over imperative. However I feel like it's worth thinking about the mental model when we need to deal with non-declarative things.

For example, if we want to fetch some data on the first load of a widget. How should I think about it in my head? I'm still thinking "on init, fetch the data" then I need to write code to make that happen.

Right now when I read the `useEffect` code, the literal interpretation "when nothing changes, run someEffect". So I have to do some mental twists for it to make sense to me. So I was motivated to make my personal helper `useInit`.

It's possible I'm missing some mental model. Like when I learned functional programming, I had to stop thinking about for loops and assignment and think about transformations and side effects. Perhaps there's a similar mental model I'm missing in hooks. If so, what would it be? Is there some thinking already on this subject?

**Comment by esDotDev** [comment]
Could start with a simple pragmatic example. How do I `useAnimation()` and play it forward automatically once. And have some code that is actually readable? Without thinking of the term of the `init()` phase of a life-cycle? 

Seems like we'd need another param `useAnimationController(autoplay: true)`, which gets to the whole point of why you might want to use init(), flexibility. If the param is not there, I can at least do:
```
AnimationController anim = useAnim();
useInit(init: (){
   anim.forward(from: .5); //Why .5? Doesn't matter, flexibility is the pt here. Designers come up with weirds things.
})
```

**Comment by rrousselGit** [comment]
You don't do that.

Make an implicit animation instead:

```dart
TweenAnimatipnBuilder(
  tween: Tween(begin: 0, end: 5)
)
```

Same thing, but declarative.

**Comment by esDotDev** [comment]
TAB is one of my favorite widgets, but about half the time it doesn't really fit the use case. Specifically when I will need to restart or play from a specific point, or I want to delay the start of it. Not to mention we're all well aware of the issues with readability and nesting. 

As far as I can tell, your argument kinda comes down to being against all Imperative code at all. Which I think is not the role of hooks, if we want to hook in a bunch of controllers, and do some thing @ initState, why should it have such a strong opinion about this as to force us to write unreadable code?

As it stands right now, I'm not even sure the point of having `useAnimation`, if we're not supposed to ever use imperative API. It's ok to use imperative API on a button handler, but not when a view is first constructed, is that the argument?

**Comment by esDotDev** [comment]
More evidence of this is the lack of `autoplay` or `delay` in the existing `useAnimation` hook. If we had support for a decent `init()` hook this is no big deal, we just do it inline and it's all good. Without, it's basically a big pain in the neck, we either write that nasty `useEffect` code, or write some custom hook we need to port from project to project, which puts a serious damper on using `hooks` fulltime. And that's just for Anims, this extends to any controller style object, so it puts a damper on all community hooks.

**Comment by rrousselGit** [comment]
>  Which I think is not the role of hooks

it is.

Flutter_hooks is a port of React hooks. That's one of their goals in React.

You're free to disagree. And you're free to make your custom hooks. If you like a `useInit`, make one yourself. But that is a bad practice.

>  Specifically when I will need to restart or play from a specific point, or I want to delay the start of it. Not to mention we're all well aware of the issues with readability and nesting.

You can make custom hooks if needed. You can have a `useTweenAnimation` and make variants of it for different use-cases

>  if we're not supposed to ever use imperative API. It's ok to use imperative API on a button handler, but not when a view is first constructed, is that the argument?

I'm not saying you shouldn't use "forward". I'm saying you shouldn't think in terms of "initState" vs "dispose" and instead implement something akin to implicit animations.

**Comment by esDotDev** [comment]
You haven't addressed any of my points about the pragmatism lacking in this approach. Not thinking in terms of initState is completely nonsensical. My designer says, I want this list to scroll to the top when it's first shown, I have to explain to them it will take longer cause I'm not allowed to think about init() as an event.

I'm here posting about hooks, because I'd like hooks to be better. Having to write a custom hook, to get basic functionality, for _one_ controller type, is clearly not appealing.

But with most things like this, when you've made up your mind, there is no budging regardless of how many use cases we can put in front of you. It's same for the bizarre decision to force us to write ugly code if we want to read something in build.

**Comment by esDotDev** [comment]
This points to sortof declarative API you actually need to implement if you want to seriously claim there is no need for imperitive:
![image](https://user-images.githubusercontent.com/736973/102720054-1b51fc80-42af-11eb-868e-ea5f79524392.png)

Now imagine doing that for every single type of controller you use, what a giant pain, and for what? You're writing more code, more tests, and inevitably creating more bugs. It's fine if it's a well tested community component, but building your own, simple to avoid making basic method calls, is just a horrible idea in terms of efficiency & robustness.

**Comment by esDotDev** [comment]
Even the react devs realize there is no point denying this use case:
![image](https://user-images.githubusercontent.com/736973/102720349-0bd3b300-42b1-11eb-8487-a6607b4809be.png)
https://stackoverflow.com/a/56767883

At least this would sidestep the gross hack that is `useEffect(.., [])`

**Comment by rrousselGit** [comment]
As I said, `flutter_hooks` is a port of React hooks.

Something like `useInit` is against the official recommendations of React hooks, and therefore against the recommendations of `flutter_hooks`.

From the React team:

> You’ll definitely struggle with them (hooks) for as long as you try to map them mentally to lifecycles. They just don’t work that way. So you’re making it more difficult for yourself by trying to mix two paradigms in your head.

https://twitter.com/dan_abramov/status/1157250021852684288

Now if you disagree and want a `useInit`, that's entirely fine. `flutter_hooks` provides you will all the tools necessary to make whatever you want on your own.

Writing such a hook is a single line of code, so complaining about having to explain to your designer that it'll take more time is disingenuous.

It takes 10 seconds:

```dart
void useInit(VoidCallback cb) => useEffect(() {cb();}, []);
```

So the effort on your side is neglible.

On the other hand, having `flutter_hooks` promote something that is against the official good-practices of hooks is a different beast.

If the package itself includes something that is considered bad practice, this will confuse potentially hundreds of people. After all, why would it be included in the package if you shouldn't use it?
Similarly, once we have a `useInit`, people will ask for a `useDispose` or `useDidUpdate`, which are equally bad practices; but it wouldn't make sense to refuse one and not the others

If you want a hook that is built directly inside React that is missing inside `flutter_hooks`, that's a totally different matter.

**Comment by venkatd** [comment]
@rrousselGit apologies looks like the discussion got a bit heated :(

I already have this hook in our hooks folder, so this change would have no effect on my personal productivity. So the intention is to help improve the library. 

The discussion I meant to have was: is it worth including something like `useInit` hook inside of the library? If it promotes bad practice, it would be good for us to understand what the good practice and mental model is.

This is probably the piece of info that I was missing:

![image](https://user-images.githubusercontent.com/220686/102721435-cb802f00-42c8-11eb-90a1-131489826c6d.png)

I do think the react "all state" vs "no state" is too subtle of a difference for the API but perhaps aligning to the React API is worth that downside of confusion.

**Comment by rrousselGit** [comment]
> @rrousselGit what do you think of including some useful react hooks talks/articles I find in the README of flutter hooks?

Sure, fancy making a PR?

The biggest downside is it needs some translation for non-React users.

**Comment by esDotDev** [comment]
First off I really appreciate the time Remi. All love here. Just trying to understand the thinking here... 

> > You’ll definitely struggle with them (hooks) for as long as you try to map them mentally to lifecycles. They just don’t work that way. So you’re making it more difficult for yourself by trying to mix two paradigms in your head.
> 
> https://twitter.com/dan_abramov/status/1157250021852684288

This misses a key point and is a red herring I think. React has many lifecycle hooks. We're talking about 2, mount and unmount, the 2 specifically called out in the docs for **useEffect**. 
http://screens.gskinner.com/shawn/chrome_2020-12-20_11-47-19.png
![image](https://user-images.githubusercontent.com/736973/102721884-bbf9e980-42ba-11eb-811e-02bbecfb8603.png)

The docs go to great ends to explain how to work both with mount and unmount. Why would they do this if it was such bad practice? And even if they were to say this is bad practice, which they don't, why should we never question their wisdom? Can you point to any specific examples in `Flutter` where we would make it "more difficult" if we ran a init/dispose method?

> Writing such a hook is a single line of code, so complaining about having to explain to your designer that it'll take more time is disingenuous.

I wasn't arguing I would do that, but that was what you were recommended I do when you bring up TAB and say everything should be like that. Of course I would just figure out some way to hack around the silly limitation, or just use a SW, but that's my entire point. 

Your argument seems to be "Of course you would do it imperatively in this use case", then at the same time "you should never do things imperatively, it's bad practice". 

> But you're free to make a package that contains `useInit`.
> Also, if you want a hook that is built directly inside React that is missing inside `flutter_hooks`, I'd be happy to include it.

Sounds like I at least have the design for a nice package I can use myself! But now you're laying more and more abstractions on top of core Flutter, which itself is a negative. Just seems like a really obvious thing to have. Is your plan to then stay locked to react_hooks forever with no thought to how things might work better in Flutter? Already you have broken convention somewhat by properly naming your variables in `useAnimationController`, It would be more harmonious if the core of hooks matched the hooks themselves.

> Similarly, once we have a useInit, people will ask for a useDispose or useDidUpdate, which are equally bad practices; but it > wouldn't make sense to refuse one and not the others

There is a pragmatic argument to support one over others, 95% of the hooks we want are initState and dispose() in real world use case. Probably the reason they call out these 2 hooks specifically in the useEffect docs and explicitly explain that they are supported and how they work. **useEffect was clearly built to support both of these lifecycle events as a design goal**.

I'd propose you just tweak the internal syntax to be more dart like (when do we ever pass raw `[]` like this?), and then just add a simple hook for init/dispose, so people aren't forced into this hack, which I hope we can both agree is a worse case scenario. It's basically declarative code, acting in an mysterious way that literally no one can read unless they've first read the docs.

```
useEffect(effect: (){}, { dispose:(){}, dependancies: [],  } ); //No deps (null or []) means always rebuild, no silly hidden behavior
useLifecycle({ init(){}, dispose: (){} });
```

**Comment by esDotDev** [comment]
> ![image](https://user-images.githubusercontent.com/220686/102721435-cb802f00-42c8-11eb-90a1-131489826c6d.png)

On it's face, this is kinda funny statement:
```
useEffect(fn); //all state
useEffect(fn, []); //no state
```
![image](https://user-images.githubusercontent.com/736973/102722259-2d3a9c00-42bd-11eb-87c5-5840d645733f.png)

**Comment by rrousselGit** [comment]
> Your argument seems to be "Of course you would do it imperatively in this use case", then at the same time "you should never do things imperatively, it's bad practice".

Which part of my argumentation do you refer to for the "Of course you would do it imperatively in this use case"?

I believe that all use-cases can be represented in a non-imperative way, and therefore imperative solutions are straight up no-go

> The docs go to great ends to explain how to work both with mount and unmount. Why would they do this if it was such bad practice? 

They explain how it is similar to class life-cycles in some ways, but they aren't saying "You should have a `useInit` hook".

In the design steps when they made hooks, they _used_ to have what you called `useLifecycle`. They voluntarily moved away from it to favor what `useEffect` currently is, which is something that fills the same goals as what `initState` + `didUpdateWidget` + `dispose` are but with a different mental model.


> I'd propose you just tweak the internal syntax to be more dart like (when do we ever pass raw [] like this?), and then just add a simple hook for init/dispose, so people aren't forced into this hack, which I hope we can both agree is a worse case scenario. It's basically declarative code, acting in an mysterious way that literally no one can read unless they've first read the docs.
>
> ```dart
> useEffect(effect: (){}, { dispose:(){}, dependancies: [],  } ); //No deps (null or []) means always rebuild, no silly hidden behavior
> useLifecycle({ init(){}, dispose: (){} });
> ```

This is explicitly what `useEffect` is trying to avoid.

It's also something that bit me in provider, which adopted this `init: () {}, dispose: () {}` syntax and something that Riverpod moved away from.

A good example of why this syntax is important would be subscriptions:

```dart
class MyWidget extends HookWidget {

  final ChangeNotifier notifier;

  @override
  Widget build(BuidContext context) {
    useEffect(() {
      void listener() {
        print('Value changed');
      }

      notifier.addListener(listener);
      return () => notifier.removeListener(listener);
    }, [notifier]);
  }
}
```

This code highlight a use-case that would not be doable with something like `useLifecycle` or a pair of `useInit`+`useDispose`.

The difficulty? The dispose action depends on variables from the init action. But with a `useLifecycle` approach, dispose and init share no variable. 

On top of it, the `ChangeNotifier` instance can change over time. So it's not exactly an `initState` and `dispose`, because the action needs to be performed again whenever the `ChangeNotifier` changes

**Comment by esDotDev** [comment]
I do see the inherent need for nesting init() and dispose() together with the functional slant of hooks, so that's fair.  But I don't see why we can't at least name things properly so its readable, and suport `[]` and `null` as the logically equivalent things they read as.  When you have a method like `useEffect` that is totally overloaded in behavior, any clarification to intent you can provide is good.  

The point of declarative programming is to hide implementation details, aka to "push-down" the imperative code. In this case, by overloading `useEffect` they are forcing implementation details into the declarative code. A developer who wants to "syncronize" with init/dispose, should not have to worry about how that is done. Opaque lines of code like: `((){ return (){}}, [], null, {})` are not declarative by any reasonable definition of the term.

> Which part of my argumentation do you refer to for the "Of course you would do it imperatively in this use case"?

Well I asked a really basic question, "how do I start anim my controller, or delay start of the controller, without useEffect". You response was "Use a Dec. Widged like TAB", I responded that that a lot of extra work if TAB doesn't make my use case, and then you said I could just write my own `init()` hook myself in 10 seconds (which is admitting that we do actually want to just tie into mount event here).

**Comment by esDotDev** [comment]
Seems like a more reasonable solution that doesn't overload useEffects so much would be:
1. `useInit()` will handle the 'init/dispose' case, no silly passing of `[]` as if it means something
2. useEffect() requires a list of deps
3. if you want to call `fn()` every build, just call it, no `useEffect(fn)`

Seems to me this doesn't add any extra functionality, or stray from react_hooks philosophy.  It just provides use-case clarity, and readable code, rather than using a single function to serve 3 use cases with opaque syntax.

But maybe I am missing a use case for `useEffect(fn)`

**Comment by venkatd** [comment]
@esDotDev 

I have a slightly different stance now. I am starting to see why the React team went away from lifecycle hooks. If you have a mental model of lifecycles, your brain will get wired to think in terms of lifecycles and you will be fighting with the model of hooks.

As an example, when I picked up Elixir, my first functional language, it came with an if statement. This construct was designed for beginners to make people feel comfortable. It was just syntax sugar over pattern matching.

However, using the if actually got in my way. I was thinking about things in previous paradigm. Once I ditched if, I was able to rewire my brain to thinking in a more functional way.

Even if `useEffect(() {})` is essentially `scheduleMicrotask`, using one over the other influences how I think about the problem. So the name is important to me.

Maybe the real confusion can be narrowed down to the difference `useEffect(handler, [])` and `useEffect(handler, null)`?

**Comment by esDotDev** [comment]
I guess I just don't buy it, clearly we still do need to think in terms of widget lifecycles when we need to decide whether to use [] or not. To me its virtually pure semantics to say you want to "syncronize with the state", (ie do something when it is created, and destroyed), or you want hooks for mount/unmount. It's distinction without any difference.

fwiw, some common usage examples of imperitive code on initState:
```
ScrollController scrollController = useScrollController(initialScrollOffset: 200);
AnimationController animController = useAnimationController(duration: Duration(seconds: 1));
TextEditingController textController = useTextEditingController(text: "Hooks are cool!");
    // Init
    useEffect(() {
      textController.selection = TextSelection(baseOffset: 0, extentOffset: textController.text.length);
      animController.forward();
      scheduleMicrotask(() {
        scrollController.animateTo(0, duration: Duration(seconds: 1), curve: Curves.easeOut);
      });
      return null;
    }, []);
```

**Comment by esDotDev** [comment]
Also fwiw, `useEffect` is not totally analogous to scheduleMicrotask. If I try and scroll my scrollController with useEffect, I get an error that no list is attached, but scheduleMicrotask works fine. So useEffect must be firing somehow in the same frame, so I'm back to being unsure as to why it exists at all.

**Comment by esDotDev** [comment]
Another example of a very popular set of react hook extensions **17,000** stars,160 contributors, 
https://github.com/streamich/react-use

And look here:
```
useLifecycles — calls mount and unmount callbacks.
useMount — calls mount callbacks.
useUnmount — calls unmount callbacks.
```

**Comment by rrousselGit** [comment]
> ScrollController scrollController = useScrollController(initialScrollOffset: 200);
> AnimationController animController = useAnimationController(duration: Duration(seconds: 1));
> TextEditingController textController = useTextEditingController(text: "Hooks are cool!");
> // Init
> useEffect(() {
>   // Select all text when view is first shown
>   textController.selection = TextSelection(baseOffset: 0, extentOffset: textController.text.length);
>   // Play some animation when view is first shown
>   animController.forward();
>   // Scroll list to some position, when the view is first shown
>   scheduleMicrotask(() {
>       scrollController.animateTo(0, duration: Duration(seconds: 1), curve: Curves.easeOut);
>   });
>   return null;
> }, []);

I think there is a misunderstanding: This should **not** have an empty dependency list

You should instead have:

```dart
useEffect(() {
 ...
}, [animationControler, scrollController, textController]);
```

You should always list all the dependencies of the effect in the dependency list.

I'm working on implementing a linter for hooks rules, and this would definitely be one of the thing on the list.

As such, a `useMount` would basically never be useful. If your effect has no dependency at all, what does it even do?

**Comment by f-person** [comment]
> If your effect has no dependency at all, what does it even do?

In one of my past  projects I needed to play audio when the page opened. With a StatefulWidget, I would have used `initState`. With hooks I used `useEffect` with empty dependency list, so it would run just once.

**Comment by rrousselGit** [comment]
> In one of my past projects I needed to play audio when the page opened. With a StatefulWidget, I would have used initState. With hooks I used useEffect with empty dependency list, so it would run just once.

That's still one dependency: the audio player

**Comment by esDotDev** [comment]
> What does it do

It runs once! The entire ask of this thread.

In this case we are after init-like behavior, even if the scrollController were rebuilt for some reason, we would not want the scrollToTop or fadeIn to fire again. 

I'm surprised you'd say this, this use case is called out in the [docs](https://reactjs.org/docs/hooks-effect.html),
_If you want to run an effect and clean it up only once (on mount and unmount), you can pass an empty array ([]) as a second argument. This tells React that your effect doesn’t depend on any values from props or state, so it never needs to re-run._

It's is also in tons of sample hooks that I looked at last night. For example:
https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/src/useDidMount.js
https://github.com/beautifulinteractions/beautiful-react-hooks/blob/master/src/useWillUnmount.js
https://github.com/streamich/react-use/blob/master/src/useLifecycles.ts

You also do not always have a dependency, an extremely common pattern in our apps, is to load a specific type of data when a page has loaded:
```
void initState() {
  RefreshFeedCommant(type: Feeds.HomeFeed);
}
```

**Comment by esDotDev** [comment]
fwiw, I made a custom didMount, and the code now looks more like:
```
// Vars
// Vars
final textController = useTextEditingController(text: "Hooks are cool!");
final scrollController = useScrollController(initialScrollOffset: 200);
final animController = useAnimController(
  Duration(seconds: 1),
  onStart: (c) => c.forward(),
  delay: Duration(milliseconds: 200),
);
// Init
useMount(() {
  // Select all text when the view is first shown
  textController.selection = TextSelection(baseOffset: 0, extentOffset: textController.text.length);
  //Scroll up 1 frame after the view is first shown
  scheduleMicrotask(() {
    scrollController.animateTo(0, duration: Duration(seconds: 1), curve: Curves.easeOut);
  });
});
```

Also fwiw, some hooks that handle common use cases:
```
//call mount and unmount callbacks, when component is mounted and un-mounted, respectively.
void useLifecycles(Dispose Function() initWithDispose) {
  useEffect(initWithDispose, []);
}

void useMount(VoidCallback effect) {
  useLifecycles(() {
    effect?.call();
    return null;
  });
}

void useUnmount(VoidCallback effect) {
  useLifecycles(() => effect);
}
//
bool useFirstMountState() {
  ValueNotifier<bool> firstMount = useState(true);
  if (firstMount.value) {
    firstMount.value = false;
    return true;
  }
  return false;
}

// Ignores the first invocation (e.g. on mount). The signature is exactly the same as the useEffect hook.
void useUpdateEffect(Dispose Function() effect, [List<Object> keys]) {
  bool firstMount = useFirstMountState();
  useEffect(() {
    if (!firstMount) {
      return effect?.call();
    }
    return null;
  }, keys);
}
```

I think we're past the "Is this use case valid" phased tbh. Looking around last night, literally **every single** react hooks library has added these in. They must have use, it's pointless to argue against this. A more constructive conversation might be to to figure out how we can create a community driven repository of these, that is less strict and focuses on just collecting pragmatic 'non-core' hooks.

**Comment by esDotDev** [comment]
Found another[ set of extensions,](https://github.com/daniel-dx/nice-hooks) with similar rationale to what I'm saying:
![image](https://user-images.githubusercontent.com/736973/102826304-9eea1700-439d-11eb-8ccd-99d6810b4c3f.png)

**Comment by venkatd** [comment]
This may be valuable in some situations. But there is an argument to be made for keeping it out of the core lib. For example, the sample code is:

```js
  useLifeCycle({

    didMount() {
      // Do something after mounted
    },

    willUnmount() {
      // Do something when the component will be unmount
    },

    didUpdate() {
      // Do something after re-rendered.
    },
```

If a beginner were to use this hook, they might end up basically writing hooks class-based-component style in situations where a declarative approach is possible. This might be a matter of opinion though, because it seems even the React community doesn't agree on this.

**Comment by esDotDev** [comment]
I can see from a core POV how it would be a slippery slope here. But that ^ is just:
 ```
useEffect((){
  // Do something after mounted
  return () { // Do something when the component will be unmount }; 
}, []);
useEffect((){ // Do something after re-rendered. });
 ```
 If people can, and will do that, why not provide at least:
 ```
 useInitWithDispose((){
   // Do something after mounted
   return (){  // Do something when the component will be unmount  };
 })
 ```
 or, more often the case, since hooks handles teardown, I'dwant this simple intent to be shown:
 ```
 useInit((){
   // Do something when the component will mount
 })
 // Render
 ```

**Comment by esDotDev** [comment]
This line from the react docs clarifies a lot imo:
![image](https://user-images.githubusercontent.com/736973/103103457-6422f180-45de-11eb-9736-e4f33e191044.png)

The less common cases, are 'skip first build', and 'conditional build'.

So you have 1 single method, serving 5 use cases:
* Mount
* Unmount
* Build
* Just Update (skip first)
* Conditional-Build

Some might see this as a beautifully elegant API, but to me it's feels like a big mashup. I'd be way more swayed by this "don't think of lifecycles" if useEffect didn't have the `[]` hacks for binding to mount/unmount.

fwiw, the `skipFirst` is quite cludgy if I understand correctly:
```
bool isFirstRun = useState(false);
useEffect((){
   if(isFirstRun) return;
   // Do stuff
   return null; // yuck...but my linter will demand it.
});
```

**Comment by rrousselGit** [comment]
If your linter complains about returns, disable that lint rule. That's a false positive.

non-nullable types will likely fix it.

**Comment by esDotDev** [comment]
But I don't want to disable that linter rule? Why is this a false positive? I want it for all of the code across the app... if a method expects a return type, you should return it.
![image](https://user-images.githubusercontent.com/736973/103103837-1eb3f380-45e1-11eb-80ba-a4e10334d0de.png)
These are my standard rules fwiw:
```
analyzer:
  language:
    strict-inference: true
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
linter:
  rules:
    always-specify-types: true
    always_declare_return_types: true
    prefer-relative-imports: true
    avoid_types_on_closure_parameters: false
```

**Comment by rrousselGit** [comment]
This lint is removed with non-nullable types.

It exists because _at the moment_ the compiler is unable to know if not returning anything is valid. But with NNBD, the compiler knows it, so the lint will be removed.

**Comment by esDotDev** [comment]
I don't fully understand, but I trust you on it :) Thanks Remi!

**Comment by AlaaEldeenYsr** [comment]
@esDotDev 
```dart
useMounted((){
  // run animation only once after first render of current widget
  runAnimation();
});

useDidMountEffect(() {
    // after first render of current widget run animation and on every time dependency changes
  runAnimation();
}, [dependency]);
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

void useDidMountEffect(void Function()? Function() effect, [List<Object?>? keys]) {
  final didMount = useState(false);

  useEffect(() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      didMount.value = true;
    });
  }, []);

  useEffect(() {
    if (didMount.value) {
      effect();
    }
  }, [...?keys, didMount.value]);
}

void useMounted(VoidCallback func) {
  return useDidMountEffect(() {
    func();
  }, []);
}
```

**Comment by esDotDev** [comment]
Nice, that is certainly much more readable than using the `useEffect` directly imo

**Comment by roblframpton** [comment]
I know this is an old thread, but I found this issue as another newcomer confused by the `useEffect` behaviour.  To me this is nothing to do with declarative vs non-declarative or initState vs useEffect, it's just about plain readability.

Why not have a convenience function called `useEffectOnce` which just calls `useEffect` with the empty array argument?  This way there's a clean, readable user interface without a need a "magic" value that is meaningless unless you have the magic knowledge.

I'm aware this project aims to be a direct port of React hooks but IMO this was a poor design decision by React.  It's a common source of confusion, and it breaks fundamental principles of explicit, readable code - something that declarative functional programming is supposed to be good at!

**Comment by noga-dev** [comment]
> I know this is an old thread, but I found this issue as another newcomer confused by the `useEffect` behaviour.  To me this is nothing to do with declarative vs non-declarative or initState vs useEffect, it's just about plain readability.
> 
> Why not have a convenience function called `useEffectOnce` which just calls `useEffect` with the empty array argument?  This way there's a clean, readable user interface without a need a "magic" value that is meaningless unless you have the magic knowledge.
> 
> I'm aware this project aims to be a direct port of React hooks but IMO this was a poor design decision by React.  It's a common source of confusion, and it breaks fundamental principles of explicit, readable code - something that declarative functional programming is supposed to be good at!
> 
> 

Maybe someone could contribute to the docs by adding examples of hooks that replicate each behavior (initState, didChangeDependancies, onDispose, etc.) or even show how to create new hooks with the appropriate name and show them off in the docs?
