### ISSUE TITLE
Question: How to deal with complex state objects?

### ISSUE THREAD

**Issue by esDotDev** [rrousselGit/flutter_hooks#125]
Often in my apps, I want to work on some temporary object, that may have many fields. I can't seem to puzzle out how I can do that with hooks, without manually calling notifyListeners, or creating a ton of boilerplate.

```
class SomeProps {
  bool value1 = false;
//+ dozens more
}

class SomePropsEditor extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final settings = useState(SomeProps());
    SomeProps data = settings.value;
    return Column(
      children: <Widget>[
        Checkbox(
            value: data.value1,
            tristate: false,
            onChanged: (v) {
              data.value1 = v;
              settings.notifyListeners(); //How to make it work without this?
            }),
        RaisedButton(
          child: Text("SUBMIT"),
          //Send modified properties to whoever opened this page, so they can finish the job
          onPressed: () => Navigator.pop(context, data),
        )
      ],
    );
  }
}
```

**Comment by smiLLe** [comment]
```dart
/// this trigger a rebuild
settings.value = newSettings
```
You can use immutable state [freezed](https://github.com/rrousselGit/freezed) and make your SomeProps class immutable.
The ```onchanged``` method will then look like this:
```dart
onChanged: (v) {
  settings.value = data.copyWith(value1: v);
}),
```

or if you don't like immutable object you can make ```SomeProps``` extend ```ChangeNotifier``` and use ```useListenable``` instead of ```useState```
```dart
class SomeProps with ChangeNotifier {
  bool value1 = false;
  void setV1(bool v) { value1 = v; notifyListeners(); }
}

onChanged: (v) {
  settings.value.value1 = v
}),
```

**Comment by rrousselGit** [comment]
Closing this, since @smiLLe answered

**Comment by gskinner-shared** [comment]
Thanks, but rather than invasively scatter notifyListener calls throughout my data objects, exploding them with avvessors and boilerplate, I prefer to just subclass VelueNotifier, and expose a notify() function, so I can call that externally when I know something has changed.

**Comment by esDotDev** [comment]
Thanks, but rather than invasively scatter notifyListener calls throughout my data objects, exploding them with avvessors and boilerplate, I prefer to just subclass VelueNotifier, and expose a notify() function, so I can call that externally when I know something has changed.

Just make something like this and use instead:
```
class SimpleNotifier extends ChangeNotifier {
  void notify() => notifyListeners();
}

class SimpleValueNotifier<T> extends ValueNotifier<T> {
  SimpleValueNotifier(T value) : super(value);

  void notify() => notifyListeners();
}
```

Then it's:
```
onChanged: (v) {
  userNotifier.value.email = v;
  userNotifier.notify();
}),
```
