### ISSUE TITLE
Help me stop abusing your library

### ISSUE THREAD

**Issue by granmoe** [rrousselGit/flutter_hooks#127]
I am very new to Dart and Flutter, and I struggled for several hours to create a decent custom hook for my state machine library (https://pub.dev/packages/state_machina). My state machine class has the ability to register simple listeners, so I used that and came up with the following very hacky solution:

```dart
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:state_machina/state_machina.dart';

StateMachine useStateMachine(StateMachine state) {
  var current = useState(state.current);

  useEffect(() {
    var listener = (_current, _, __) {
      current.value = _current;
    };

    state.addListener(listener);

    return () {
      state.removeListener(listener);
    };
  }, []);

  return state;
}
```

Now, I could make my class use `ChangeNotifier` or something like that and then just call `notifyListeners()` where appropriate, but I'd rather keep this library agnostic of Flutter and open to all Dart use cases. Perhaps that is worth questioning in itself.

Is there a better way to do this without changing my library?

Thank you!

PS - flutter_hooks is an awesome library and has already improved my app's code immensely ☺️

**Comment by rrousselGit** [comment]
> so I used that and came up with the following very hacky solution:

What's hacky in that solution?

**Comment by granmoe** [comment]
I'm using the variable from `useState` only for the side-effect of triggering an update, which seems very indirect and not really what `useState` is meant for. I know that in the React world, I would consider this a smell. Yeah, it works, and it isn't too awful, but I was wondering if there's a better solution to be found 🙂

**Comment by rrousselGit** [comment]
Why don't you return the `current` instead of the parameter then?

**Comment by rrousselGit** [comment]
To me, it looks like your issue is that `StateMachine` is mutable.

**Comment by granmoe** [comment]
I tried that, but ran into issues. IIRC, `current` wasn't updating because I update it via `state` (`state.send` to be specific). I.e. I don't modify `current` directly, therefore `useState` doesn't trigger an update.

**Comment by granmoe** [comment]
> To me, it looks like your issue is that `StateMachine` is mutable.

What exactly does this mean? I am very new to both Dart and Flutter. I assumed that a class was a class and mutable vs immutable was not an option.

**Comment by granmoe** [comment]
Wait a second...I do remember seeing something about freezing properties of objects at some point, with `const`, for example. Hmm...

**Comment by granmoe** [comment]
So I guess if I took the immutable approach, I'd have to return a new instance of `StateMachine` every time its current state changes?

**Comment by rrousselGit** [comment]
> So I guess if I took the immutable approach, I'd have to return a new instance of `StateMachine` every time its current state changes?

Yes, and that's totally fine

**Comment by granmoe** [comment]
Awesome, I will play around with that and report back 👍

**Comment by granmoe** [comment]
So this morning I realized I shouldn't spend any more time on this right now. My current solution is working for my needs. I did get enough info to potentially explore some other options down the road, though, so thank you for that.
