### ISSUE TITLE
How to have hooks with tabController ? 

### ISSUE THREAD

**Issue by yelkamel** [rrousselGit/flutter_hooks#129]
Hello, first nice job what you did thanks for this tools :) 
and then I want to have, I want to create a useTabController who initiate the instance and give it to my model.

So I did something like that: 
```
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:navigation/widget/home/model.dart';
import 'package:provider/provider.dart';

ValueNotifier<TabController> useTabController<T>(
    BuildContext context, int lenght, int initialIndex) {
  final tinkerMixin = useSingleTickerProvider();
  final tabController = useState<TabController>(
      TabController(vsync: tinkerMixin, length: 3, initialIndex: initialIndex));

  useEffect(() {
    Provider.of<HomeModel>(context, listen: false)
        .setTabcontroller(tabController.value);
    return () {
      tabController.dispose();
    };
  }, []);

  return tabController;
}
```
But I got this: 
![Screenshot_1586707498](https://user-images.githubusercontent.com/10924422/79073669-239d7500-7ce8-11ea-8809-fb21d54f8a4d.png)

I check the code it's because TabController create an animateController in his constructor...

Do you have any idea of how I can achieve that ? :) 

Regards,

**Comment by rrousselGit** [comment]
Intead of `useState`, you probably want `useMemoized`

**Comment by rrousselGit** [comment]
Closing in the lack of answers. Feel free to make a new issue if you still have a problem.

**Comment by AhmedEzio47** [comment]
I have the same issue, would you please give us an example of how to use useSingleTickerProvider? @rrousselGit

**Comment by chanjungkim** [comment]
You can use like this `final tabController = useTabController(initialIndex: 0, initialLength: 5, vsync: useSingleTickerProvider());`

**Comment by IbrahimDeveloperA** [comment]
import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_percent_page.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_price_page.dart';

import '../../../generated/assets.dart';
import '../../../utils/utils.dart';

@RoutePage()
class AlertsOneTimePage extends HookWidget {
  const AlertsOneTimePage({super.key});

  //leading:
  @override
  Widget build(BuildContext context) {
    final tabController = useTabController(initialLength: 2);
    return Scaffold(
        appBar: AppBar(
          centerTitle: false,
          foregroundColor: Colors.white,
          scrolledUnderElevation: 0.0,
          toolbarHeight: 72.h,
          title: const Text(
            'Alert one time',
            style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.only(right: 22),
              child: SvgPicture.asset(Assets.imageAlertsSettingsIcon),
            ),
          ],
          elevation: 0,
          bottom: TabBar(
            controller: tabController,
            indicatorSize: TabBarIndicatorSize.tab,
            dividerColor: Colors.white10,
            tabs: listAlerts.map((String item) {
              return Container(
                padding: const EdgeInsets.only(bottom: 16),
                child: Text(
                  item,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        body: TabBarView(
            controller: tabController,
            children: [AlertsPercentPage(), AlertsPricePage()]));
  }
}


You can try it

**Comment by IbrahimDeveloperA** [comment]
`import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_percent_page.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_price_page.dart';

import '../../../generated/assets.dart';
import '../../../utils/utils.dart';

@RoutePage()
class AlertsOneTimePage extends HookWidget {
  const AlertsOneTimePage({super.key});

  //leading:
  @override
  Widget build(BuildContext context) {
    final tabController = useTabController(initialLength: 2);
    return Scaffold(
        appBar: AppBar(
          centerTitle: false,
          foregroundColor: Colors.white,
          scrolledUnderElevation: 0.0,
          toolbarHeight: 72.h,
          title: const Text(
            'Alert one time',
            style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.only(right: 22),
              child: SvgPicture.asset(Assets.imageAlertsSettingsIcon),
            ),
          ],
          elevation: 0,
          bottom: TabBar(
            controller: tabController,
            indicatorSize: TabBarIndicatorSize.tab,
            dividerColor: Colors.white10,
            tabs: listAlerts.map((String item) {
              return Container(
                padding: const EdgeInsets.only(bottom: 16),
                child: Text(
                  item,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        body: TabBarView(
            controller: tabController,
            children: [AlertsPercentPage(), AlertsPricePage()]));
  }
}
`

You can try it

**Comment by IbrahimDeveloperA** [comment]
`import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_percent_page.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_price_page.dart';

import '../../../generated/assets.dart';
import '../../../utils/utils.dart';

@RoutePage()
class AlertsOneTimePage extends HookWidget {
  const AlertsOneTimePage({super.key});

  //leading:
  @override
  Widget build(BuildContext context) {
    final tabController = useTabController(initialLength: 2);
    return Scaffold(
        appBar: AppBar(
          centerTitle: false,
          foregroundColor: Colors.white,
          scrolledUnderElevation: 0.0,
          toolbarHeight: 72.h,
          title: const Text(
            'Alert one time',
            style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.only(right: 22),
              child: SvgPicture.asset(Assets.imageAlertsSettingsIcon),
            ),
          ],
          elevation: 0,
          bottom: TabBar(
            controller: tabController,
            indicatorSize: TabBarIndicatorSize.tab,
            dividerColor: Colors.white10,
            tabs: listAlerts.map((String item) {
              return Container(
                padding: const EdgeInsets.only(bottom: 16),
                child: Text(
                  item,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        body: TabBarView(
            controller: tabController,
            children: [AlertsPercentPage(), AlertsPricePage()]));
  }
}
`

**Comment by IbrahimDeveloperA** [comment]
```dart
import 'package:auto_route/annotations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_percent_page.dart';
import 'package:mobile_hodler/ui/alerts/alerts_time/tabs/alerts_price_page.dart';

import '../../../generated/assets.dart';
import '../../../utils/utils.dart';

@RoutePage()
class AlertsOneTimePage extends HookWidget {
  const AlertsOneTimePage({super.key});

  //leading:
  @override
  Widget build(BuildContext context) {
    final tabController = useTabController(initialLength: 2);
    return Scaffold(
        appBar: AppBar(
          centerTitle: false,
          foregroundColor: Colors.white,
          scrolledUnderElevation: 0.0,
          toolbarHeight: 72.h,
          title: const Text(
            'Alert one time',
            style: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
          ),
          actions: [
            Padding(
              padding: const EdgeInsets.only(right: 22),
              child: SvgPicture.asset(Assets.imageAlertsSettingsIcon),
            ),
          ],
          elevation: 0,
          bottom: TabBar(
            controller: tabController,
            indicatorSize: TabBarIndicatorSize.tab,
            dividerColor: Colors.white10,
            tabs: listAlerts.map((String item) {
              return Container(
                padding: const EdgeInsets.only(bottom: 16),
                child: Text(
                  item,
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              );
            }).toList(),
          ),
        ),
        body: TabBarView(
            controller: tabController,
            children: [AlertsPercentPage(), AlertsPricePage()]));
  }
}
``` 

That's how it works for me
