### ISSUE TITLE
TextField loses text when it loses focus

### ISSUE THREAD

**Issue by Haidar0096** [rrousselGit/flutter_hooks#131]
So if I use `useTextEditingController()` inside `build()` method to get a controller and assign it to my `TextField`, then every time the `TextField` loses focus the `build()` will be called again, the controller is reset to a new instance, and the text that existed in the previous `TextField` is gone.

Now you said that a `HookWidget` can be a complete replacement for a `Statefulwidget` (in documentation of flutter_hooks),
now in `StatefulWidget` this can be solved by creating the `FocusNode` and `TextEditingCotnroller` as fields of `State` class, and intialize them in `initState()`,
while in `HookWidget` we can't do that.

so how do we solve this problem?

example of problem:

1. I run the app (it is minimal app nothing fancy)

2. I type some text in the `TextField`, then  I click on the recent apps buttons (on emulator), I can still see my app, I click on my app now, and the text is gone, and build method is not called again 

```
class Test extends HookWidget {
  @override
  Widget build(BuildContext context) {
    print('build');//build is not called again when app gains focus
    final focusNode = useFocusNode();
    final controller = useTextEditingController();
      return Scaffold(
      body: Center(
        child: Container(
          width: 200,
          height: 200,
          color: Colors.red,
          child: TextField(
            focusNode: focusNode,
            controller: controller,
          ),
        ),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
I am unable to run any Flutter apps for a few weeks, so I'll need more
information

I don't quite understand. Are you sure that the TextEditingController is
being recreated?
If you print the hashCode of both the controller, the focusNode, and the
context, what do you get when you lose your state?

Le sam. 25 avr. 2020 à 15:15, Haidar0096 <notifications@github.com> a
écrit :

**Comment by Haidar0096** [comment]
> I don't quite understand. Are you sure that the TextEditingController is
> being recreated?

No I can't confirm or deny that as I don't have a way to find if it is being recreated unless the build method is run again when my app regains focus (which is not happening as the print statement is not being executed)

> If you print the hashCode of both the controller, the focusNode, and the
> context, what do you get when you lose your state?

I don't know bcz as I said above the print statement is not executed when I re-click the app from recent apps list (which means build is not called and that's weird)

**Comment by rrousselGit** [comment]
If the build method is not re-executed, then the problem is likely not in
flutter_hooks

Are you sure that the same example but with a StatefulWidget using
initState doesn't fail?

**Comment by Haidar0096** [comment]
Ok now thats more weird, I noticed that even with stateful widget, if I press the recent apps when I am still focusing in the text field, and then get back to the app, the text is lost

on the other hand, if I type some text, close the keyboard (while I am still in the app),then press recent apps and then come back, the text stays there,
If then I add any text and with focus still on the text field,I press recent apps and come back, only the new text is gone but old one is still there 

Do you want me to screen record it if its not obvious?

**Comment by rrousselGit** [comment]
You can if you want to, but if that happen with StatefulWidget too, then
you should most likely make an issue on Flutter instead

Le sam. 25 avr. 2020 à 16:52, Haidar0096 <notifications@github.com> a
écrit :

**Comment by Haidar0096** [comment]
this is a gif of the same scenario that happens with hook widget and stateful widget:

![Screencast-from-04-25-2020-06_59_00-PM](https://user-images.githubusercontent.com/49842031/80284708-cadacd00-8728-11ea-87f8-121282ab3393.gif)

**Comment by Haidar0096** [comment]
I will close this issue here because I opened one on flutter repo as this is not only happening with flutter hooks

**Comment by lzzy12** [comment]
I am facing the exact issue with useFocusNode() but with StatefulWidget works fine for me

**Comment by rrousselGit** [comment]
You can't create globalKeys like that.
When this widget's parent rebuild, you will recreate the key which will destroy the widget tree.

Create your GlobalKey inside a useMemoized instead

**Comment by lzzy12** [comment]
> You can't create globalKeys like that.
> When this widget's parent rebuild, you will recreate the key which will destroy the widget tree.
> 
> Create your GlobalKey inside a useMemoized instead

Ah thanks! That fixed it
