### ISSUE TITLE
Clarify useFuture usage

### ISSUE THREAD

**Issue by fgblomqvist** [rrousselGit/flutter_hooks#132]
In #119 you mentioned that you are expected/have to use `useMemoized` with `useFuture` to prevent it from getting called multiple times. While I can sort of understand that, it's not made clear in the docs. More importantly, is there ever a time when you would want to `useFuture` without `useMemoized`? It seems to be that the most common usage would require `useMemoized`, and in that case, I feel like `useFuture` should have that "built-in" so-to-speak.

**Comment by fgblomqvist** [comment]
I ended up writing my own hook that combines `useFuture` and `useMemoized`, and also offers a way to refresh the future in an elegant fashion:

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

/// Stores an [AsyncSnapshot] as well as a reference to a function [refresh]
/// that should re-call the future that was used to generate the [snapshot].
class MemoizedAsyncSnapshot<T> {
  final AsyncSnapshot<T> snapshot;
  final Function() refresh;

  const MemoizedAsyncSnapshot(this.snapshot, this.refresh);
}

/// Subscribes to a [Future] and returns its current state in a
/// [MemoizedAsyncSnapshot].
/// The [future] is memoized and will only be re-called if any of the [keys]
/// change or if [MemoizedAsyncSnapshot.refresh] is called.
///
/// * [initialData] specifies what initial value the [AsyncSnapshot] should
///   have.
/// * [preserveState] defines if the current value should be preserved when
///   changing the [Future] instance.
///
/// See also:
///   * [useFuture], the hook responsible for getting the future.
///   * [useMemoized], the hook responsible for the memoization.
MemoizedAsyncSnapshot<T> useMemoizedFuture<T>(
  Future<T> Function() future, {
  List<Object> keys = const <dynamic>[],
  T initialData,
  bool preserveState = true,
}) {
  final refresh = useState(0);
  final result = useFuture(
    useMemoized(future, [refresh.value, ...keys]),
    initialData: initialData,
    preserveState: preserveState,
  );

  void refreshMe() => refresh.value++;

  return MemoizedAsyncSnapshot<T>(result, refreshMe);
}
```
I think this hook is the missing piece in the puzzle that is Flutter and memoization of futures (regardless of whether you use hooks or not, there doesn't seem to be a good pattern on how to manage refreshing of your futures?).

Here's how I use it (in a basic fashion):
```dart
final fetch = useMemoizedFuture(
  () => Provider.of<AccountsService>(context).getAccounts(),
);
```
If you want to refresh the future, e.g. when someone presses a button, or perhaps if someone comes back from a different route (i.e. `Navigator.pop`), you just call `fetch.refresh()` which will trigger an async refresh of the future.

For example:
```dart
IconButton(
  icon: const Icon(Icons.add),
  onPressed: () async {
    await Navigator.pushNamed(context, '/accounts/add');
    fetch.refresh();
  },
)
```
In this example, the user navigates to a page that allows them to add an account. Once they're done, the navigation stack is popped and they're taken back to the screen that lists all the accounts. Normally, using memoization, that list would now be outdated/not include the new account. However, as you can see, I can now easily force a refresh of that data. Furthermore, you could implement logic that only refreshes the data if the user successfully added an account (as opposed to canceling the adding), and so forth.

**Comment by rrousselGit** [comment]
The behavior of useFuture is that of FutureBuilder

They work the same, modulo that useFuture is a one liner. 

While I understand the idea, having built-in memorization would restrict the possibilities and increase complexity. 
The combination of useFuture + useMemoized should be more than enough

**Comment by fgblomqvist** [comment]
Yeah I realized the other day that FutureBuilder suffered from the same problem.

I think the goal should generally be to simplify for the common use-case, which I'd argue is to memoize the future (and provide a way to easily refresh it). Keeping the hooks separate might make sense, but I'd expect most developers to want to memoize their future and therefore to appreciate a hook like the one I wrote above. As with all simplifying layers, it certainly increases the complexity a tad and restricts the possibilities a tad, but so does most libraries, yet they still exist in order to speed up/simplify development.

Finally, I don't think it's particularly DRY to write `useFuture(useMemoization(...))` in tens if not hundreds of places (as the application grows).

Anyway, I can understand if you don't think something like the above should belong in flutter_hooks if you're just trying to mirror the native flutter state management. Feel free to close this issue.

**Comment by rrousselGit** [comment]
I would like to avoid making too many opinionated hooks inside flutter_hooks for now.

The purpose of hooks is that people can make custom ones if they need to. 

If people need both useFuture and useMemoized together a lot, they can wrap them in a function:

```dart
AsyncSnapshot<T> useExample(Future<T> create()) {
  final future = useMemoized(create, const []);
  return useFuture(future);
}
```

It's simple enough that there's not much value having it built-in

**Comment by rrousselGit** [comment]
Closing as per my previous answers
