### ISSUE TITLE
Add StatefulHookWidget

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#137]
Instead of:

```dart
class Example extends HookWidget {...}
```

We'd have:

```dart
class Example extends StatefulWidget with Hooks {...}

class Example extends StatelessWidget with Hooks {...}
```

This allows hooks to work on Statefulwidgets and allows linter to support hooks too (as it currently does not understand HookWidget).

**Comment by esDotDev** [comment]
This will really provide the best of both worlds. +1

**Comment by spideythewebhead** [comment]
Hello, recently I made a try to implement hooks with mixins, and now I saw your project and this issue and can't understand where you use hooks on an stateless widget?

Also i can add it to GitHub if you wanna take a look how I was thinking the impl with hooks, thanks.

**Comment by rrousselGit** [comment]
Actually, a `with Hooks`, while looking fancy, is probably not the correct solution, as it requires some work-around in `createElement` to support both `StatefulWidget` & `StatelessWidget` at once.

Instead, it should be up to the linter to understand that `HookWidget` == `StatelessWidget`.
And for `StatefulWidget`, we can have `StatefulHookWidget`.

**Comment by spideythewebhead** [comment]
Hmm yes, but how would you use a hook on a stateless widget? I mean an example why would use it there , if it's a stateless.

**Comment by smiLLe** [comment]
@spideythewebhead  you might want to have a look at the [examples](https://github.com/rrousselGit/flutter_hooks/blob/master/example/lib/use_state.dart)

In future, it seams that we are going from
```dart 
class MyWidget extends HookWidget  {}
```
to
```dart
class MyWidget extends StatelessWidget with Hooks {}
```

**Comment by spideythewebhead** [comment]
Yeah, but then an stateless widget for example could use useSteam hook? I mean is it really stateless then

**Comment by esDotDev** [comment]
Its stateless in the sense that it does not provide access to any of the lifecycle methods of StatefulWidget, or contains any ephemeral state, which I guess provides some clarity and promotes simplicity.

**Comment by spideythewebhead** [comment]
hmm makes sense in a way, but i think its more confusing, 'my stateless widget has actual state' that is not shared among others.
i think its wrong or at least confusing as a concept (or at least i cant get my head around it),
it makes more sense to have 
`
class MyWidget extends StatefulWidget { ... }
class MyWidgetState extends State<MyWidget> with Hooks { ... }
`
