### ISSUE TITLE
Having a mounted properties when using useState

### ISSUE THREAD

**Issue by jaumard** [rrousselGit/flutter_hooks#138]
One user of my package report me this https://github.com/mylisabox/flutter_mjpeg/issues/6 
Look like the ValueNotifier returned by useState is disposed by the time I want to change it. Having a `mounted` property would allow me to check if it's disposed or not before trying to modify it.

**Comment by rrousselGit** [comment]
You can make one yourself with `useEffect` + a mutable object

You can make a pull request if you want 🙂

**Comment by jaumard** [comment]
That's what I did as a workaround but I was thinking it will be a nice addition, I'll try make a PR :)

**Comment by davidmartos96** [comment]
I had the same requirement and I created the following hook. It could be a handy addition.
@rrousselGit Would you accept a PR with this implementation? It's like https://github.com/rrousselGit/flutter_hooks/issues/74#issuecomment-486391956 but as a reusable hook.

```dart
// Sample
Widget build(context) {
  final isMounted = useIsMounted();
  useEffect(() {
    someFuture.then(() {
       if (!isMounted()) return;
       // Else set state...
       // ...
    });
    return null;
  },[]);
  ...
}

///////////////////////////////////////////////////////////////////////////

IsMounted useIsMounted() {
  final mounted = IsMounted(true);
  useEffect(() {
    return () {
      mounted.setMounted(false);
    };
  }, []);
  return mounted;
}

class IsMounted {
  bool _mounted = true;

  void setMounted(bool v) => _mounted = v;

  IsMounted(this._mounted);

  bool call() {
    return _mounted;
  }
}

```
