### ISSUE TITLE
Widget Testing

### ISSUE THREAD

**Issue by kg551915** [rrousselGit/flutter_hooks#140]
I'm completely lost on how to test my HookWidget.   
Even calling just: `await tester.pumpWidget(myHookWidget());` causes an error.  

I simply have a:

> 
>
>      class myHookWidget extends HookWidget {  
>        @override  
>        Widget(BuildContext context {  
>           return MultiBlocProvider(
>               ...<Do some state stuff, call another hook widget based on state>...
>            );  
>          }  
>        }  

I've read through the flutter hooks tests but for some reason I cannot understand what I am not grasping here. Is there something special I have to do or understand to test flutter hooks?

**Comment by rrousselGit** [comment]
What error do you get?

**Comment by kg551915** [comment]
Upon further investigation it had nothing to do with Flutter Hooks, my bad.
