### ISSUE TITLE
Maybe hooks should be defined as an extension of HookWidget.

### ISSUE THREAD

**Issue by HeavenOSK** [rrousselGit/flutter_hooks#145]
## Problem
Hooks method only works inside of `HookWidget`.
But we can call hooks everywhere. For example, we can call hooks also inside `StatelessWidget` as following.

```dart
class SomeStatelessWidget extends StatelessWidget {
  const SomeStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final value = useProvider(someProvider);
    return Text(value.toString());
  }
}
```

The above code works fine at compile time, but it will cause a runtime error. 
Because hooks needs context of `HookElement`.

## Suggestion
I came up with one idea. We can define hooks method as instance method of `HookWidget`, then we can limit the way to call.
And also If we define hooks with extension of `HookWidget`, we can maintain extendability.
 
example code is as following.

```dart
extension UseProvider on HookWidget {
  T useProvider<T>(ProviderListenable<T> provider) {
    final owner = ProviderStateOwnerScope.of(useContext());
    return Hook.use(_ProviderHook<T>(owner, provider));
  }
}

```

**Comment by rrousselGit** [comment]
That would make https://github.com/rrousselgit/functional_widget stop working

This issue would be better solved by a custom linter (which will come at some point, when I find the time)

**Comment by HeavenOSK** [comment]
I see. I didn't know the functional_widget. It’s going to stop working if my suggestion is adopted.

Thank you for the reply 🙏
