### ISSUE TITLE
is it possible to have getter and setter in custom Hook without using Class ? 

### ISSUE THREAD

**Issue by simoneTheNewBlack** [rrousselGit/flutter_hooks#146]
Hi guys, 

coming from React, just wondering if it is possible to write something like below: 

```
ValueNotifier useModel (BuildContext context,){
	final count = useState(0);
	final string = useState('This is String');
	var addCount = () => count.value++;
	var lessCount = () => count.value--;
	return {
		'string': string.value,
		'count': count.value,
		'addCount': addCount,
		'lessCount': lessCount
	};
}


class App extends HookWidget {
        Widget build(BuildContext context) {
                 var model = useModel(context);
                  return Component(model: model)
        }
}
```

The code is error, but wanted to write similar style...
Thanks in advance

**Comment by rrousselGit** [comment]
Your code looks alright. What's wrong?

**Comment by simoneTheNewBlack** [comment]
@rrousselGit this is the error message

**A value of type 'Map<String, Object>' can't be returned from function 'useModel' because it has a return type of 'ValueNotifier<dynamic>'.**

**Comment by rrousselGit** [comment]
Change `ValueNotifier` to `Map` and your code will work.

**Comment by simoneTheNewBlack** [comment]
oh yes, thanks @rrousselGit . solved

can we put useProvider() inside the custom hooks?

**Comment by rrousselGit** [comment]
Sure. Hooks are hooks. You can use them normally
