### ISSUE TITLE
Integrate Widget Inspector

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#15]
`Hook` and `HookState` would gain a lot from inheriting `Diagnosticable`, so that the widget inspector allow debugging the hook state.

**Comment by rrousselGit** [comment]
A temporary solution may be to put everything at the same level as widget properties.

This is a bit confusing though.

**Comment by jaumard** [comment]
Did you open an issue on IntelliJ plugin for that ? Might worth it :)

**Comment by rrousselGit** [comment]
There is theorically no need to. It is done by overriding `debugFillProperties`

I got it to work already, just haven't published it yet

**Comment by rrousselGit** [comment]
It seems that Flutter team have made some enhancements about big diagnosticable trees. I'll try again to see if I can get something more readable
