### ISSUE TITLE
useEffect hook not working properly.

### ISSUE THREAD

**Issue by alirashid18** [rrousselGit/flutter_hooks#153]
In React,  useEffect hook works after first build. Bu in flutter_hooks, useEffect works before first render. That's why, make an operation with context object on useEffect(() { //operation using context }, []) makes following error:
Cannot listen to inherited widgets inside HookState.initState. Use HookState.build instead.

REACT HOOKS WORKING EXAMPLE
<img width="884" alt="Screen Shot 2020-07-12 at 13 58 40" src="https://user-images.githubusercontent.com/68184267/87243543-da280780-c447-11ea-8aa2-0599023307c2.png">

**Comment by gabrielvictorjs** [comment]
> In React, useEffect hook works after first build. Bu in flutter_hooks, useEffect works before first render. That's why, make an operation with context object on useEffect(() { //operation using context }, []) makes following error:
> Cannot listen to inherited widgets inside HookState.initState. Use HookState.build instead.
> 
> REACT HOOKS WORKING EXAMPLE
> <img alt="Screen Shot 2020-07-12 at 13 58 40" width="884" src="https://user-images.githubusercontent.com/68184267/87243543-da280780-c447-11ea-8aa2-0599023307c2.png">

show your implementation with flutter_hooks

**Comment by rrousselGit** [comment]
You cannot perform operation with the context API inside `useEffect` in React either.

That doesn't work:

```js
useEffect() => {
  useContext(MyContext); // not a valid usage
}, []);
```

**Comment by rrousselGit** [comment]
Although arguably, we could allow calling Provider's `context.read` inside `useEffect(() {...}, [])`

**Comment by alirashid18** [comment]
@rrousselGit For example.
I have config.json file in my assets folder. I need to read its data using DefaultAssetBundle. When I read data using loadString method (DefaultAssetBundle.of(context).loadString('assets/config.json')) it shows me an error.
After this error, I copied useEffect hook source code and changed it initHook method as follows:
  void initHook() {
    super.initHook();
    WidgetsBinding.instance.addPostFrameCallback((_) { scheduleEffect(); });
  }

Then I used this hook and it worked as expectedly.


<img width="719" alt="Screen Shot 2020-07-28 at 00 13 51" src="https://user-images.githubusercontent.com/68184267/88587775-892f2a80-d067-11ea-9ec9-ad05e5996ee7.png">

<img width="860" alt="Screen Shot 2020-07-28 at 00 12 42" src="https://user-images.githubusercontent.com/68184267/88587743-79afe180-d067-11ea-85a5-c8dc5dbcc666.png">

**Comment by rrousselGit** [comment]
`Whatever.of` is equivalent to `useContext(Whatever)`.
It is normal that this code is not allowed.

Instead do:

```dart
final bundle = DefaultAssetBundle.of(context);

useEffect(() {
  bundle.loadString('...').then(...);
}, [bundle]);
```

**Comment by alirashid18** [comment]
It works, thanks @rrousselGit .

**Comment by danielmahon** [comment]
@rrousselGit What's the proper way to use a `StateProvider` inside `useEffect` without `Future.microtask`? Or is it required?

I get this error without it:
```
[VERBOSE-2:ui_dart_state.cc(171)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
```

```dart
@freezed
abstract class AppState with _$AppState {
  const factory AppState({
    @Default(false) bool hasOnboarded,
    Widget fab,
    @Default([]) List<DepartmentModel> favorites,
  }) = _AppState;
}

final stateProvider = StateProvider((_) => const AppState());

final stateController = useProvider(stateProvider);

useEffect(() {
  // Future.microtask(() {
  stateController.state = stateController.state.copyWith(
    fab: FloatingActionButton(
      backgroundColor: theme.accentColor,
      onPressed: () {},
      child: const Icon(Icons.share),
    ),
  );
  // });
  return () {
    // Future.microtask(() {
    stateController.state = stateController.state.copyWith(fab: null);
    // });
  };
}, [stateController]);
```

**Comment by rrousselGit** [comment]
> Or is it required

It is required. The exception was implemented on purpose to prevent modifying a provider without the microtask because that is dangerous.

**Comment by danielmahon** [comment]
I figured, thanks. Pretty trivial to add my own `useAsyncEffect`. Loving riverpod + hooks by the way! Do you think it's worth revisiting adding a built-in `useAsyncEffect` to `flutter_hooks`?

```dart
void useAsyncEffect(
  FutureOr<dynamic> Function() effect,
  FutureOr<dynamic> Function() cleanup, [
  List<Object> keys,
]) {
  useEffect(() {
    Future.microtask(effect);
    return () {
      if (cleanup != null) {
        Future.microtask(cleanup);
      }
    };
  }, keys);
}
```

**Comment by fdietze** [comment]
This is my version of `useAsyncEffect`:
(It tries to keep the signature similar to `useEffect`)
```dart
void useAsyncEffect(Future<Dispose?> Function() effect, [List<Object?>? keys]) {
  useEffect(() {
    final disposeFuture = Future.microtask(effect);
    return () => disposeFuture.then((dispose) => dispose?.call());
  }, keys);
}
```

**Comment by rrousselGit** [comment]
Closing since everything is working as expected.

I don't plan on adding a `useAsyncEffect` for now. You shouldn't need such a thing and it's likely a sign of code smell (such as modifying a state in the wrong place)

**Comment by najibghadri** [comment]
@rrousselGit Can you elaborate please why is _this_ a sign of code smell?

I have many places in my code where a firs-time useEffect calls an async function.. some might use the context too. Why is this bad? 🙂

**Comment by rrousselGit** [comment]
Because if your problem is "can't call setState", the solution isn't to silence the error by using a hacky workaround of delaying the update by a frame

You should refactor your code such that the update is performed before all listeners of the object were built.

**Comment by najibghadri** [comment]
Oh okay, I thought calling async funcs in useEffect is considered bad.. 😅  Thanks @rrousselGit!

**Comment by shtse8** [comment]
> Because if your problem is "can't call setState", the solution isn't to silence the error by using a hacky workaround of delaying the update by a frame
> 
> You should refactor your code such that the update is performed before all listeners of the object were built.

Thanks for your explanation.
Does it mean there is nothing wrong with `useAsyncEffect`?
What if I want to do something in async while there is any changes on values?
For example, in splash screen, there is a login process (async) when entering the page. after logging in successfully, user will be  routed to another page. What is the correct implementation without `useAsyncEffect`?
