### ISSUE TITLE
useDisposable - new hook idea

### ISSUE THREAD

**Issue by JulianKowalczuk** [rrousselGit/flutter_hooks#154]
Hi there,
by using Your package I found out, that most hooks I created had really simple structure - similar to useAnimationController one.
Since this package goal is decrease amount of boilerplate code - why don't create this one? All this hook should do was calling dispose() method on object we passed as our hook argument.

Example:

```dart
final calendarController = useDisposable(CalendarController(today: DateTime.now()));
```

In case You are busy, I can make PR for this feature.

**Comment by rrousselGit** [comment]
Wouldn't you want to make a useCalendarController instead?

**Comment by JulianKowalczuk** [comment]
But it's creating another file per hook. It's better to use hook which may be used with many controllers from many packages, that's the code:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

T useDisposable<T>(T disposable) {
  return Hook.use(_DisposableHook(disposable));
}

class _DisposableHook<T> extends Hook<T> {
  final T disposable;

  _DisposableHook(this.disposable);

  @override
  _DisposableHookState<T> createState() => _DisposableHookState();
}

class _DisposableHookState<T> extends HookState<T, _DisposableHook<T>> {
  @override
  T build(BuildContext context) {
    return hook.disposable;
  }

  @override
  void dispose() {
    (hook.disposable as dynamic).dispose();
  }
}
```

**Comment by rrousselGit** [comment]
You can do:

```dart
final controller = useMemoized(() => CalendarController());
useEffect(() => controller.dispose, [controller]);
```

**Comment by JulianKowalczuk** [comment]
Ok, it's short enough XD

**Comment by scopendo** [comment]
> You can do:
> 
> ```dart
> final controller = useMemoized(() => CalendarController());
> useEffect(() => controller.dispose, [controller]);
> ```

@rrousselGit – just some feedback that for those new to Flutter Hooks, particularly without experience with Flutter Hooks, this is, in my opinion, an important example to highlight as it makes it clear how to dispose of an arbitrary controller for which there isn't currently a hook function.
