### ISSUE TITLE
Add useCompleter Hook

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [rrousselGit/flutter_hooks#156]
Recently my team and I started using BLoC state management. The BLoC documentation suggests using a Completer to manage the RefreshIndicator widget: https://bloclibrary.dev/#/flutterweathertutorial (search 'Completer' for a quick reference).

We decided to try out a useCompleter hook, and it seems to be working correctly.

Implementation:
```
Completer<void> useCompleter() {
  return use(_CompleterHook());
}

class _CompleterHook extends Hook<Completer> {
  @override
  _CompleterHookState createState() => _CompleterHookState();
}

class _CompleterHookState extends HookState<Completer, _CompleterHook> {
  Completer _completer;

  @override
  void initHook() {
    _completer = Completer<void>();

    super.initHook();
  }

  @override
  Completer build(BuildContext context) => _completer;
}
```

*Potential issue* - the bloc docs example have this part in:
```
child: BlocConsumer<WeatherBloc, WeatherState>(
          listener: (context, state) {
            if (state is WeatherLoadSuccess) {
              _refreshCompleter?.complete();
              _refreshCompleter = Completer();
            }
          },
```

which means the hook needs to be created as such `var _completer = useCompleter()`. This makes me uneasy, I'm not sure if it's correct. Can you explain whether we should be doing something differently? I'd prefer to use `final` for creating the hook.

And then if everything is in order...would you consider merging it into the hooks package? With more people using BLoC it might become a popular use case 😄

**Comment by Ferdzzzzzzzz** [comment]
@rrousselGit Felix Angelov just told me that a Completer isn't necessary...apparently he's busy redoing tutorials for BLoC v6. Guess this idea might not pick up much then. You can just give this comment a reaction if you're happy for me to close the issue 😄

**Comment by rrousselGit** [comment]
You should do "useMemoized(() => Completer())" instead.
There's no need to create a custom hook

**Comment by Ferdzzzzzzzz** [comment]
Aaah great, thanks 🔥
