### ISSUE TITLE
Make HookContext.use a static method, and migrate hooks as static

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#16]
Having to type `context.useState` is kind of redundant.
`useState` is more than enough.

Since hooks can only be accessed during `build`, only one `HookContext` at a time can access hooks. We can, therefore, simplify the syntax by exposing it statically.

**Comment by szotp** [comment]
I actually liked the HookContext approach more, because having it ensures that you are inside a hook widget's method. Would you accept a PR that brings it back and enables both approaches?

**Comment by rrousselGit** [comment]
It's technically still there, just private.

I don't quite like the idea of making part of the public API, as I may change the implementation. 
But if you want, you can make it "public but not exported" and import the implementation file.

**Comment by szotp** [comment]
Alright, thanks. I will test the standard approach first and see how it goes.
