### ISSUE TITLE
Add child property to HookBuilder

### ISSUE THREAD

**Issue by nesbocaj** [rrousselGit/flutter_hooks#161]
Most of Flutter's `Builder` widgets (should be all of them really) optionally take a `child` parameter alongside the `builder` itself for performance optimization. As explained in the [documentation for `AnimatedBuilder`](https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html#performance-optimizations):

> If your `builder` function contains a subtree that does not depend on the animation, it's more efficient to build that subtree once instead of rebuilding it on every animation tick.
> 
> If you pass the pre-built subtree as the `child` parameter, the `AnimatedBuilder` will pass it back to your `builder` function so that you can incorporate it into your build.
> 
> Using this pre-built `child` is entirely optional, but can improve performance significantly in some cases and is therefore a good practice.

I don't see why `HookBuilder` would not benefit from this kind of performance optimization too.

**Comment by rrousselGit** [comment]
This comment is a bit misleading, as you do not need such a parameter for the optimization.

My general recommendation is to not use `HookBuilder` then and to straight-up make a `HookWidget`


```dart
class MyHookWidget extends HookBuilder {
  const MyHookWidget({Key key, this.child}): super(key: key);

  final Widget child;

  @override
  Widget build(context) {
     useState(false);

     return child;
   }
}
```

But if you insist on using `HookBuilder`, you can do:

```dart
final child = Container();

return HookBuilder(
  builder: (context) {
    useState(false);
    return child;
  }
);
```

which is equivalent to the `child` parameter

**Comment by nesbocaj** [comment]
I don't see how my personal opinion can be misleading. But anyway, I would argue that the explicit `child` parameter helps with  discoverability of a possibly more performant way of doing things, as opposed to the naive implementation of just doing everything in the `builder`.

Also why the `useState(false);`, what does that do in this context?

**Comment by rrousselGit** [comment]
Sorry, I wasn't talking about your opinion, but Flutter's documentation. Saying that this property allows optimization is misleading. The property does nothing at all.

I understand your point but:
- such change is a breaking change
- people wanting such optimizations can subclass `HookWidget`
- few people need `child`
- some were confused by `child` on provider's `Consumer`, wondering how they could use it when they have a list of children.

If you want to, you can make your own `HookBuilder`. It is quite straightforward


> Also why the useState(false);, what does that do in this context?

Just that you can use hooks, nothing special.
