### ISSUE TITLE
Destroying HookWidget?

### ISSUE THREAD

**Issue by AAverin** [rrousselGit/flutter_hooks#169]
Am I doing something wrong? I keep getting odd memory leaks with my HookWidgets and I assume that I just need to clean things up when widget is destroyed, but there are no methods available.

Here is some code:
```
class StaticMapWidget extends HookWidget {
  Spot spot;

  _VM vm;

  StaticMapWidget(this.spot) {
    vm = _VM(spot);
  }
}

class _VM {
  Spot spot;
  VM(this.spot);

  //some helper methods
}
```

Am I allowed to do this with HookWidgets, passing parameters and having local instances of classes?
Do I need to clean them up when widget is destroyed or unused references would be just GC-ed from memory?

**Comment by rrousselGit** [comment]
You shouldn't create your objects VM object like this.

What you're looking for is probably what is described here https://github.com/rrousselGit/flutter_hooks/issues/154#issuecomment-657799908

**Comment by AAverin** [comment]
Thanks for the tip. Should help with other cases, but this specific one is still leaking.
```
class StaticMapWidget extends HookWidget {
  Spot spot;

  StaticMapWidget(this.spot);

  @override
  Widget build(BuildContext context) {
    final vm = useMemoized(() => _VM(spot));
    final Completer<MapboxMapController> _controller = useMemoized(() => Completer());
    useEffect(() => vm.dispose(), [vm]);
   
    ..building widgets
 }
```
I guess I should do `useEffect` to somehow dispose MapBox instance or whatever else that is leaking. Just can't find what is the cause of the leak, it wasn't _VM after all.

**Comment by rrousselGit** [comment]
In that case, it is likely that your leak is somewhere else.

If you used a StatefulWidget, you probably would still have the leak

**Comment by AAverin** [comment]
@rrousselGit what would be the equivalent for `useCallback`? I have some async methods called on MapBox that would probably benefit from something like that to make sure they don't leak

**Comment by rrousselGit** [comment]
```dart
final cb = useMemoized(() => (int value) {...}, [...]);
```

**Comment by AAverin** [comment]
Scaling it down to 
```
class StaticMapWidget extends HookWidget {
  Spot spot;

  StaticMapWidget(this.spot);

  @override
  Widget build(BuildContext context) {
    final Completer<MapboxMapController> _controller = useMemoized(() => Completer());

    return Container(
      height: 300,
      child: Text("Map"),
    );
  }
}
```
I still get a single instance leak. Should I somehow dispose this Completer?

**Comment by rrousselGit** [comment]
What's the leak

**Comment by AAverin** [comment]
This I have no idea because Flutter DevTools Memory View is completely useless in showing what is exactly leaking.
I just see that if I don't use HookWidget, there is no instance of my parent class present.
If I use HookWidget with the code above, there is a single instance of `StaticMapWidget` kept in memory.

Here is how I use StaticMapWidget
```
class SpotDetailsMapWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return StaticMapWidget(data.spot);
  }
}

```

**Comment by rrousselGit** [comment]
You mean that you destroyed `SpotDetailsMapWidget` and don't see it in memory anymore but still see `StaticMapWidget`?

**Comment by AAverin** [comment]
Having this code:
```
class SpotDetailsMapWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return StaticMapWidget(data.spot);
  }
}

class StaticMapWidget extends HookWidget {
  Spot spot;

  StaticMapWidget(this.spot);

  @override
  Widget build(BuildContext context) {
    final Completer<MapboxMapController> _controller = useMemoized(() => Completer());

    return Container(
      height: 300,
      child: Text("Map"),
    );
  }
}
```
I get a single instance of each kept in memory even if I open the screen with widgets 3 times.

If I change to 
```
class SpotDetailsMapWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Container(child: Text('Map'));
  }
}
```
I get no instance of `SpotDetailsMapWidget` kept in memory if I open the screen 3 times.

So having an almost empty `StaticMapWidget` that extends HookWidget somehow causes the leak to be there

**Comment by AAverin** [comment]
I went further and removed _completer from the code.

Now I have:
```
class SpotDetailsMapWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return StaticMapWidget(data.spot);
  }
}

class StaticMapWidget extends HookWidget {
  Spot spot;

  StaticMapWidget(this.spot);

  @override
  Widget build(BuildContext context) {

    return Container(
      height: 300,
      child: Text("Map"),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/1481332/90546695-b5cbf300-e18a-11ea-9e27-bfe1119f8876.png)

You can see the leak on the screenshot.

Could this be related to HookWidget itself or my Spot parameter that I pass through?
Spot is just a basic class with data backed by Hive library.

**Comment by rrousselGit** [comment]
But `SpotDetailsMapWidget` is there too, so that's logical?

**Comment by AAverin** [comment]
@rrousselGit not really, because the screen where `SpotDetailsMapWidget` is displayed is already popped from the stack and now showing on the screen.
I will try to look into if my basic data class can be a cause of the leak, which is something I completely didn't expect in the beginning

**Comment by AAverin** [comment]
I am pushing this widget to a navigator via MaterialPageRoute. I open and close the route 4 times.

extending StatelessWidget, I still see 1 instance.
extending HookWidget, I see all 4 instances kept in memory.

```
class TestWidget extends StatelessWidget {

  TestWidget();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: Text('MAP'),
    );
  }
}
```

**Comment by AAverin** [comment]
I think my leak issue is not related directly to HookWidget. But I should still use better approaches on how to memoise and deallocate controllers that I use via hooks.
Do you think it would make sense to highlight all those best practices and receipes in docs?
I have experience with both React and Android native, but I totally forgot that with React Hooks you need to return a callback out of `useEffect` to mimic `ComponentWillUnmount` behaviour. Just didn't think the same would apply for Flutter Hooks too.
