### ISSUE TITLE
Add a HookBuilder

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/flutter_hooks#174]
A simple `HookBuilder` may provide less friction in adoption since it could be inserted in existing stateless or stateful widgets.

```dart
typedef Widget HookWidgetBuilder(BuildContext context);

class HookBuilder extends HookWidget {
  const Example({
     Key key, 
     @required this.builder,
   }) : super(key: key);

  final HookWidgetBuilder builder;

  @override
  Widget build(BuildContext context) {
    return builder(context);
  }
}
```

Usage :

```dart
@override
Widget build(BuildContext context) {
    return HookBuilder(
        builder: (context) {
             final value = setState(0);
             /// ...
        },
    );
}
```

**Comment by davidmartos96** [comment]
@aloisdeniel I think you are looking for this, which is already implemented 😄

https://pub.dev/documentation/flutter_hooks/latest/flutter_hooks/HookBuilder-class.html

**Comment by aloisdeniel** [comment]
Oh damn, so cool! 👍 

I don't know how I missed that. It would be great to make it a bit more visible, I'm pretty sure that it would trigger more adoption.
