### ISSUE TITLE
Request: Rename useContext to useBuildContext

### ISSUE THREAD

**Issue by sesam** [rrousselGit/flutter_hooks#179]
Since react's useContext is about a context related to component (widget) state https://reactjs.org/docs/hooks-reference.html#usecontext I think it would be more clear if the flutter BuildContext would be accessed through useBuildContext. If there needs to be a useContext it would probably be useful to have it supply a functionality more similar to react's useContext.

Pretty please? PRs welcome? :)

**Comment by rrousselGit** [comment]
Is it really an issue?
React's useContext _is_ BuildContext, with Theme.of(context)

I'm not sure what we would expect from a _useContext_ otherwise.

**Comment by normancarcamo** [comment]
@rrousselGit what are the tradeoff of using the root context instead of the hook provided by the package?

**Comment by rrousselGit** [comment]
I don't understand your question.
What is the goal in using only the root context?

**Comment by normancarcamo** [comment]
Mm sorry, maybe with an example would be more clear:
```dart
  // skipped by brevity
  Widget build(BuildContext context) { // <-- root?
    final _context = useContext(); // <-- hook?
  }
```
Why is a hook for the context when the build method has its own?

**Comment by davidmartos96** [comment]
The context provided by the hook is the context  of the HookWidget being built. You can use useContext() when creating your own hooks. For example:

```dart
bool useIsDarkTheme() {
    final context = useContext ();
    final theme = Theme.of(context);
    return theme.brightness == Brightness.dark;
```

**Comment by rrousselGit** [comment]
@davidmartos96 is right.

**Comment by normancarcamo** [comment]
Thanks guys, now I understood better.

**Comment by rrousselGit** [comment]
Closing as there is no answer to https://github.com/rrousselGit/flutter_hooks/issues/179#issuecomment-681117542

If you still want this and disagree with that comment, feel free to comment and I will reopen the issue

**Comment by felipe-xavier** [comment]
> @normancarcamo The context provided by the hook is the context of the HookWidget being built. You can use useContext() when creating your own hooks. For example:
> 
> ```dart
> bool useIsDarkTheme() {
>     final context = useContext();
>     final theme = Theme.of(context);
>     return theme.brightness == Brightness.dark;
> }
> ```

@davidmartos96 where exactly would this code be written? inside the InitHook or inside the build of the custom hook ?

**Comment by normancarcamo** [comment]
This is something old 😅, 3 years ago I deliver the project and all good.

Thanks btw.

**Comment by normancarcamo** [comment]
> > @normancarcamo The context provided by the hook is the context of the HookWidget being built. You can use useContext() when creating your own hooks. For example:
> 
> > 
> 
> > ```dart
> 
> > bool useIsDarkTheme() {
> 
> >     final context = useContext();
> 
> >     final theme = Theme.of(context);
> 
> >     return theme.brightness == Brightness.dark;
> 
> > }
> 
> > ```
> 
> 
> 
> @davidmartos96 where exactly would this code be written? inside the InitHook or inside the build of the custom hook ?

This is something old 😅, 3 years ago I deliver the project and all good.

Thanks btw.

**Comment by davidmartos96** [comment]
> > @normancarcamo The context provided by the hook is the context of the HookWidget being built. You can use useContext() when creating your own hooks. For example:
> > 
> > ```dart
> > bool useIsDarkTheme() {
> >     final context = useContext();
> >     final theme = Theme.of(context);
> >     return theme.brightness == Brightness.dark;
> > }
> > ```
> 
> @davidmartos96 where exactly would this code be written? inside the InitHook or inside the build of the custom hook ?

That is already a custom hook. The convention is to start the function with "use". 
Hooks can be defined as functions or via the Hook class.

**Comment by felipe-xavier** [comment]
@davidmartos96 man I totally forgot about the function hooks, thanks!
