### ISSUE TITLE
Discussion: which primitive and which advanced hooks would be welcomed in this repo?

### ISSUE THREAD

**Issue by sesam** [rrousselGit/flutter_hooks#180]
After looking through some of these lists of hooks

- https://usehooks.com/
- https://github.com/streamich/react-use

I was starting to think it could be nice to have a plan for which hooks are welcome as PRs here. Please can we make
 - [ ] a wish-list
 - [x] and tick off any hooks already included?

There are several react hooks-aficionados curious to try flutter who might come and contribute here with a little push.

PS. Do you have any plans already for #hacktoberfest ?

**Comment by rrousselGit** [comment]
Hooks with no dependency on plug-ins that have a clearly described use-case are more than welcome.

I'd recommend making a PR per hook so that we can discuss about each of them individually.

Alternatively you are free to make a package built on the top of hooks

**Comment by davidmartos96** [comment]
Implementing some of the hooks mentioned by Remi here https://github.com/flutter/flutter/issues/51752#issuecomment-669626522 could be a great start as well.

**Comment by rrousselGit** [comment]
Closing for now.

If you want to suggest hooks, please make a separate issue for each individual hook you want to see added in the library.
Adding new hooks is totally fine, but we need a more focused issue.
