### ISSUE TITLE
build method uncertainty to have optimized animations

### ISSUE THREAD

**Issue by normancarcamo** [rrousselGit/flutter_hooks#183]
I am doing some optimizations on the app that I am working on, sometimes I have to redo the logic of some widget classes using the best of this package (I really love it), but I have a really a big concern about the optimization.

In the following link from flutter dev docs "[controlling build cost](https://flutter.dev/docs/perf/rendering/best-practices#controlling-build-cost)" we can see that they recommend avoid having to much logic on this method, I'm refactoring some classes that around the build method have several methods and property declarations, some of them are handled very well when I make use of **useMemoize** hook, so that way I avoid having to destruct the variables but also allows me controlling their destruction by the keys, sometimes I do make use of **useEffect** to add listeners and remove them, etc. 

What advices or best practices would you recommend me when using hooks?

honestly, I am a react developer and this is something great to see on flutter, I rather to use hooks instead of having to manually control each AnimationController registered on widgets classes for basic but very basic needs, it's really straightforward, but again, I'm trying to have a balance here 👍

**Comment by rrousselGit** [comment]
Honestly, good practices here are the same as in the React world.

Unless you have a specific problem in mind, I'm not quite sure what to say.

**Comment by rrousselGit** [comment]
Closing as this issue appears to be stale.
