### ISSUE TITLE
useFocusNode doesn't have onKey argument

### ISSUE THREAD

**Issue by normancarcamo** [rrousselGit/flutter_hooks#184]
Hello there!, 

I would like to know if there's a way to listen on **onKey** event from a FocusNode using the hook that you provide?

I would like to know if I can do the same [outlined here](https://github.com/flutter/flutter/issues/48076#issuecomment-578133973) using hooks.

**Comment by rrousselGit** [comment]
This was added as part of 0.14.0 earlier today 🥰
