### ISSUE TITLE
How to use it in a form?

### ISSUE THREAD

**Issue by edisonywh** [rrousselGit/flutter_hooks#185]
I'm trying to use hooks within my form, my approach looks like this:

```dart
class MyWidget extends HookWidget {
  build(context) {
    final _formKey = useMemoized(() => GlobalKey<FormState>());

    final email = useState("");
    final password = useState("");

    _handleSubmit() {
      if (_formKey.currentState.validate()) {
        _formKey.currentState.save();
      }
    }

    return Form(
      key: _formKey,
      child: Flex(
        children: [
          TextFormField(onSaved: (value) => email.value = value),
          TextFormField(onSaved: (value) => password.value = value),
          Button(onPressed: _handleSubmit),
        ]
      )
    )
  }
}
```

The problem is, when I click submit, my email field becomes empty, but my password field remains unchanged, why is that? I'm pretty sure I'm missing something obvious here..

I simplified my code a bit, so I may or may not have left out anything important, but this is the gist of it.

**Comment by rrousselGit** [comment]
That code looks alright to me. Make sure onSaved is called

**Comment by edisonywh** [comment]
Yeah it is called, but my email field still gets reset to empty after form submission. I'm not sure what's going on here..

I figured a workaround though, if I pass in `initialValue: email.value` into my `TextFormField`, my email remains after clicking the button. It kinda feels more like a Flutter Form behavior rather than Flutter Hooks at this point?

**Comment by rrousselGit** [comment]
It appears that your widget is recreated on submit, so it looses its state.

Maybe you're temporarily removing it from the tree to show a loading indicator

**Comment by edisonywh** [comment]
Ah mhm. I use flutter_bloc, but my form fields are not rendered conditionally, seems strange that Bloc tosses the whole state and rebuilds it?

Also doesn't really explain why it's only happening to my email field, but not the password field.. 🤔

**Comment by normancarcamo** [comment]
Have you tried memoizing this function?

```dart
_handleSubmit() {
      if (_formKey.currentState.validate()) {
        _formKey.currentState.save();
      }
    }
```

**Comment by edisonywh** [comment]
@normancarcamo do you mean to move it out of `build`? I can give it a try (I needed context in the function so I put it inside build)

**Comment by normancarcamo** [comment]
> @normancarcamo do you mean to move it out of `build`? I can give it a try (I needed context in the function so I put it inside build)

No, I mean, moving the handler into a memoized function, you don't need to recreate it every time the build method is called.
I have several forms working using the same approach. 

Example of a snippet I have:

```dart
final _isLoading = useState(false);
final _isLoginConfirmed = useState(false);
final _isBackgroundImageVisible = useState(false);
final _isRequesting = _isBackgroundImageVisible.value ||
    _isLoading.value ||
    _isLoginConfirmed.value;

final _onSubmit = useMemoized(
  () => () {
    if (_formKey.currentState.validate()) {
      FocusScope.of(context).unfocus();
      Future.delayed(Duration(milliseconds: 500), () {
        _isBackgroundImageVisible.value = true;
        _isLoading.value = true;
        Future.delayed(Duration(milliseconds: 500), () {
          StoreProvider.of<AppState>(context).dispatch(LoginUserAction(
            email: _emailController.text,
            password: _passwordController.text,
            completer: Completer()
              ..future.then((v) {
                _exception.value = null;
                _isLoading.value = false;
                _isLoginConfirmed.value = true;
              }).catchError((e) {
                _exception.value = e as AppException;
                _isLoading.value = false;
              }),
          ));
        });
      });
    }
  },
  [_formKey],
);
```

**Comment by normancarcamo** [comment]
> @normancarcamo do you mean to move it out of `build`? I can give it a try (I needed context in the function so I put it inside build)

No, I mean, moving the handler into a memoized function, you don't need to recreate it every time the build method is called.
I have several forms working using the same approach. 

Example of a snippet I have:

```dart
final _onSubmit = useMemoized(
  () => () {
    if (_formKey.currentState.validate()) {
      // ...
    }
  },
  [_formKey],
);
```

**Comment by rrousselGit** [comment]
Do you still have this problem?

**Comment by edisonywh** [comment]
I have not tried out the solution suggested yet (memoize the function), but I just set my initial attribute and that works for now (so it's not an issue with provider keeping state, but rather Flutter form widget), so you can close this issue. Thanks anyway!

**Comment by dorontal** [comment]
I've been using a slightly different answer to this question, taking the `_formKey` outside of the `build()` method instead of calling `useMemoised()` inside the `build()` method. To me, this is slightly clearer, but if you see something less desirable about this version as opposed to the one above, please share your thoughts:

```dart
class MyWidget extends HookWidget {
  final _formKey = GlobalKey<FormState>();

  build(context) {
    final email = useState("");
    final password = useState("");

    _handleSubmit() {
      if (_formKey.currentState.validate()) {
        _formKey.currentState.save();
      }
    }

    return Form(
      key: _formKey,
      child: Flex(
        children: [
          TextFormField(onSaved: (value) => email.value = value),
          TextFormField(onSaved: (value) => password.value = value),
          Button(onPressed: _handleSubmit),
        ]
      )
    )
  }
}
```

**Comment by noga-dev** [comment]
> I've been taking the `_formKey` outside of the `build()` method instead of calling `useMemoised()` inside the `build()` method. To me, this is slightly clearer, but if you see something less desirable about this version as opposed to the one above, please share your thoughts:
> 
> ```dart
> class MyWidget extends HookWidget {
>   final _formKey = GlobalKey<FormState>();
> 
>   build(context) {
>     final email = useState("");
>     final password = useState("");
> 
>     _handleSubmit() {
>       if (_formKey.currentState.validate()) {
>         _formKey.currentState.save();
>       }
>     }
> 
>     return Form(
>       key: _formKey,
>       child: Flex(
>         children: [
>           TextFormField(onSaved: (value) => email.value = value),
>           TextFormField(onSaved: (value) => password.value = value),
>           Button(onPressed: _handleSubmit),
>         ]
>       )
>     )
>   }
> }
> ```

Take _handleSubmit out of build. Redundant iterations.

**Comment by rrousselGit** [comment]
You need to memoize the GlobalKey:

```dart
class MyWidget extends HookWidget {
  build(context) {
    final _formKey = useMemoized(GlobalKey<FormState>.new, const []);
    ...
  }
}
```

**Comment by noga-dev** [comment]
> You need to memoize the GlobalKey:
> 
> ```dart
> class MyWidget extends HookWidget {
>   build(context) {
>     final _formKey = useMemoized(GlobalKey<FormState>.new, const []);
>     ...
>   }
> }
> ```

Interesting; I usually keep keys like this at file level as a private global final since even memoizing it feels like adding unnecessary iterations in build.

Would keeping _formKey at class level be bad because it would get disposed along with the class? Would it matter if it's not used outside the class anyway?

**Comment by rrousselGit** [comment]
Keeping it at the file level can cause problems if the route is multiple time in the navigation history. You'll get a duplicate GlobalKey error

**Comment by noga-dev** [comment]
> Keeping it at the file level can cause problems if the route is multiple time in the navigation history. You'll get a duplicate GlobalKey error

What about class level like in @dorontal 's example above?

**Comment by rrousselGit** [comment]
Then if an ancestor of the form rebuilds, you'll recreate the GlobalKey, causing lots of problems.

**Comment by ivankasalo** [comment]
> Maybe you're temporarily removing it from the tree to show a loading indicator

I have a similar thing and found some workarounds for this scenario where I need loading indicator. So one question rises to me. 
What would be the best practises when we need to recreate the widget to show loading indicator, for example in the scenario above ?

**Comment by dganzella** [comment]
> Then if an ancestor of the form rebuilds, you'll recreate the GlobalKey, causing lots of problems.

I have a question. Why should we use UseMemoized for global keys instead of useRef?
