### ISSUE TITLE
Comment utiliser flutter_hooks avec les blocs dans un formulaire

### ISSUE THREAD

**Issue by maxime-aubry** [rrousselGit/flutter_hooks#186]
Bonjour.

Je suis débutant avec Flutter.
Je découvre la technologie et quelques librairies comme blocs et flutter_hooks.
J'aimerais utiliser ces 2 techno, en complément de ma propre librairie flutter_model_form_validation, pour gérer des formulaires.
Avez-vous imaginé une solution pour l'utilisation des hooks avec blocs ?
Ça m'aiderait pour un bon point de départ.
Merci.

voici ma librairie si vous voulez y jeter un coup d'oeil : [https://pub.dev/packages/flutter_model_form_validation](https://pub.dev/packages/flutter_model_form_validation)

**Comment by rrousselGit** [comment]
Bonjour

Le plus simple serait de s'inspirer de "useStream", voir utiliser ce dernier directement

**Comment by rrousselGit** [comment]
Closing as `useStream` should be enough. If not, you can make your own hook
