### ISSUE TITLE
demande d'aide

### ISSUE THREAD

**Issue by maxime-aubry** [rrousselGit/flutter_hooks#187]
bonjour.

je cherche une documentation complète de votre librairie.
je me suis plongé dedans aujourd'hui, et c'est assez obscure pour moi je trouve.
je cherche par exemple à effectuer une redirection vers un autre écran après x secondes, je ne sais pas comment m'y prendre.
avez-vous entrepris de créer des tutoriaux ?

merci, et désolé si ce n'est pas le meilleur endroit pour poster cette question.

**Comment by rrousselGit** [comment]
Hello!
Mon conseil serait de lire les tutoriels de React si possible.

Sinon, dans ton cas, ce serait useEffect:

```dart
useEffect(() {
  final timer = Timer(Duration(seconds: x), () {
    Navigator.pushNamed('/hello');
  });
  return timer.cancel;
}, const []);
```

**Comment by maxime-aubry** [comment]
merci !
