### ISSUE TITLE
Support for non-nullable (NNBD) Dart

### ISSUE THREAD

**Issue by leecommamichael** [rrousselGit/flutter_hooks#189]
**Is your feature request related to a problem? Please describe.**
I wanted to enable the non-nullable experiment and was conflicted on the best way to migrate hooks. `useEffect` requires a non-null function to be returned, even when there is no tear-down logic for that effect. Hook dependencies arrays require non-null values.

**Describe the solution you'd like**
I'd like to know what the plan is for NNBD support. Additionally, to be able to have `useEffect` function-bodies optionally end without a `return` (Though that may be hard without union types).

**Comment by rrousselGit** [comment]
I will not start the migration before the beta status of NNBD is announced (as I have other priorities)

useEffect does not require a teardown callback.
You can safely return `null` or not return at all.
