### ISSUE TITLE
useContext hook

### ISSUE THREAD

**Issue by PavelPZ** [rrousselGit/flutter_hooks#19]
Thanks for including hooks to flutter. I thing that React hooks are nothing less than a revolution in (not only) React world...

Do you have a intention of including useContext (including createContext) too? I thing that it is very important hook primitive, which can in many use cases replace BLoC.

**Comment by rrousselGit** [comment]
There's no need for it. That's the default behavior of `InheritedWidget`
A hook wouldn't change anything in flutter, as opposed to React which uses render props pattern.

We currently can do the following:

```
final widdget =  context.inheritedFromWidgetOfExactType(SomeType);
```

**Comment by PavelPZ** [comment]
... plus StatefulWidget and its state (which rebuilds InheritedWidget ) as I can see in https://www.didierboelens.com/2018/06/widget---state---context---inheritedwidget/

Am I right?

**Comment by rrousselGit** [comment]
Somehow, yes. But not exactly, as `ancestorStateOfType` doesn't rebuilds the widgets that depends on it when the state changes.

`InheritedWidget` is literally the `useContext` in all its aspects.

**Comment by PavelPZ** [comment]
OK, thank you
