### ISSUE TITLE
Desktop (linux) support

### ISSUE THREAD

**Issue by ytitov** [rrousselGit/flutter_hooks#195]
**Is your feature request related to a problem? Please describe.**
When developing for flutter desktop, I get a run-time error saying I am not following the rules.  

**Describe the solution you'd like**
Are there any plans to support flutter desktop?

**Describe alternatives you've considered**
Not using flutter hooks, but that would be sad.

**Additional context**
```
flutter 1.24.0-3.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 2783f8e2e1 (5 days ago) • 2020-10-22 09:36:06 -0700
Engine • revision defa8be2b1
Tools • Dart 2.11.0 (build 2.11.0-242.0.dev)

[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Linux, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

**Comment by rrousselGit** [comment]
All platforms are supported.
If you have an error, this is unrelated to the platform and you instead made a mistake somewhere
