### ISSUE TITLE
How notifyValueChangeListener outside build method

### ISSUE THREAD

**Issue by VickyBOSS** [rrousselGit/flutter_hooks#197]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
Could you please fill the issue template?

**Comment by rrousselGit** [comment]
Closing as this issue appears to be stale.
