### ISSUE TITLE
Publish usePageController Hook

### ISSUE THREAD

**Issue by Elias8** [rrousselGit/flutter_hooks#198]
**Is your feature request related to a problem? Please describe.**
There is no `usePageController` hook for PageController  in the current released `flutter_hooks ` version on [pub.dev](https://pub.dev/packages/flutter_hooks).

**Describe the solution you'd like**
I checked the [repository](https://github.com/rrousselGit/flutter_hooks/blob/master/lib/src/page_controller.dart), and it's already done a few weeks ago, so you just need to publish it to pub.dev, I think.

**Comment by rrousselGit** [comment]
Oopsy, done
