### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by DevNico** [rrousselGit/flutter_hooks#200]
Null safety is in the second technical preview stage with flutter core support it's therefore time to start migrating packages. I'd be happy to open a PR for Null Safety if it isn't already in the works.

**Comment by harkairt** [comment]
Any update on this?

**Comment by devj3ns** [comment]
Hey @DevNico. If you have some free time I would be really happy if you could migrate the Package to null safety or start doing it😀
I wish you a great evening :)

**Comment by DevNico** [comment]
I actually migrated the package itself but then work and exams came in the way. I have some free time tonight will migrate the tests / example and open a PR.

**Comment by DevNico** [comment]
PR opened #211.

**Comment by derolf** [comment]
@DevNico 

Nice work, just trying it out.

But, IMHO, it should be:

`final List<Object?>? keys;`

not 

`final List<Object>? keys;`

Otherwise it's impossible to pass `null` as a key, which people quite often do...

**Comment by DevNico** [comment]
That obviously makes sense I just didn't have this in the codebase I tested with. Will change that when I'm at my Mac later.

**Comment by derolf** [comment]
@DevNico I forked your forked and will push a PR in a few minutes...

**Comment by DevNico** [comment]
A null safe version has been releases.
