### ISSUE TITLE
What's the recommended way to use HookWidget's method?

### ISSUE THREAD

**Issue by jeiea** [rrousselGit/flutter_hooks#201]
**Describe what scenario you think is uncovered by the existing examples/articles**
Originally asked [here](https://stackoverflow.com/questions/64924141).
I want to call the callback from `useMemoized` from outside of the widget.

**Describe why existing examples/articles do not cover this case**
I can achieve this with `GlobalKey<T>.currentState` outside of `StatefulWidget`, but there's no visible `State` in `HookWidget`. So I have a difficulty to do same task.

**Additional context**
If it were react, I would use `useImperativeHandle`.

**Comment by rrousselGit** [comment]
You don't. This is a bas practice and should not be done

Lift the state up instead
