### ISSUE TITLE
useEffect requires return function

### ISSUE THREAD

**Issue by KrallXZ** [rrousselGit/flutter_hooks#202]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6277709/100800432-e3ca0000-3426-11eb-85af-50f6da8a3c52.png)

`useEffect()` usage requires the function to be returned from callback, but the documentation says:

> That effect may **optionally** return a function, which will be called when the effect is called again or if the widget is disposed.

**To Reproduce**
Just call useEffect with callback not returning anything.

**Expected behavior**
It shouldn't be required or the docs should be changed.

**Comment by MichalSal** [comment]
Same issue

**Comment by rrousselGit** [comment]
It isn't required.

This warning is a false positive from the analyzer. Either disable "missing_return", wait for non-nullable types, or return "null"
