### ISSUE TITLE
useReducer example in repository does not rebuild

### ISSUE THREAD

**Issue by kcrossfitter** [rrousselGit/flutter_hooks#208]
**Describe the bug**
I'm new to flutter_hooks. To understand it well, I ran the examples in the repository. 

However, in the useReducer example, even if I press a floating action button several times, the  next Text widget is not rebuilt again.

`Text('Button tapped ${_store.state.counter.toString()} times')`

However, the comment of the example is as follows.

```
// Next, invoke the `useReducer` function with the reducer function and initial state to create a
// `_store` variable that contains the current state and dispatch. Whenever the value is
// changed, this Widget will be rebuilt!
final _store = useReducer(_reducer, initialState: State());
```

I tried to print the value of _store. The value of _store is printed only when build is first called.

In the useState example, the value of counter is printed every time I pressed floating action button.

**To Reproduce**

userReducer example in repository

**Expected behavior**
Whenever the floating action button is pressed, it should be rebuilt.

**Comment by rrousselGit** [comment]
Fixed in https://github.com/rrousselGit/flutter_hooks/pull/211
