### ISSUE TITLE
Hooks can only be called from the build method of a widget that mix-in `Hooks`.

### ISSUE THREAD

**Issue by jnknewaj** [rrousselGit/flutter_hooks#210]
**Describe the bug**
Even though I called `useState` from inside `build` method, I get this error : Hooks can only be called from the build method of a widget that mix-in `Hooks`.

**To Reproduce**

I am using a `BottomNavigationBar` where pages are `HookWidget`. I noticed first page of the bar is ok, but the other pages (2nd, 3rd) show the error even though I called Hook at the very beginning of `build()` method.

Here is my `HomePage` which has the `BottomNavigationBar` : 

```
class HomePage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final currentTab = useState(0);
    
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        items: [items...],
        currentIndex: currentTab.value,
        onTap: (index) {
          currentTab.value = index;
        },
      ),
      body: IndexedStack(
        index: currentTab.value,
        children: [
          EntriesOverviewPage(),
          ExpensesPage(),
          IncomesPage(),
        ],
      ),
    );
  }
}
```
Here all the 3 childrens are almost similar and all are `HookWidget'. 1st child is ok, but others show the error. Here is 2nd page : 

```
class ExpensesPage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    // will call hook later
    return SafeArea(
      child: Scaffold(
        body: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(child: ExpenseTopUi()),
            EntryListUi(),
          ],
        ),
      ),
    );
  }
}
```
Here is `ExpenseUI` which is actually creating the error: 
```
class ExpenseTopUi extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final date = useState(DateTime.now());
    return Container(...);
  }
}
```

**Comment by rrousselGit** [comment]
Sorry for the delay. Could you provide a small repo that can be executed to reproduce the error? Thanks!

**Comment by rrousselGit** [comment]
Closing as this issue appears to be stale

**Comment by tony123S** [comment]
same issue here...

https://github.com/rrousselGit/flutter_hooks/issues/401
