### ISSUE TITLE
How can I test the state of a HookWidget?

### ISSUE THREAD

**Issue by normancarcamo** [rrousselGit/flutter_hooks#214]
I have a TextFormField with a suffix icon, it toggles the whole suffix icon by another special widget, or in some cases, it just changes the color, from grey to blue when the length of the input is valid or not.

Summary of the state that I need to track:
1. length is lower than 6 chars: `_isValid.value = false;` - it displays an arrow icon with grey color
2. length is greater than 6 chars: `_isValid.value = true;` - it displays an arrow icon with blue color
3. input is submitting: `_isSubmitting.value = true;` - arrow icon is replaced by a different widget.
4. error on request: `_hasErrors.value = true;` - arrow icon or loader icon is replaced by a help/warning icon with red color.

The problem is when I change to `_isSubmitting.value = true;` to check if the animation is happening the build method never gets called.

`input.dart`

```dart
void onSubmit(String value) async {
  if (_isInputValid.value && _error.value == null) {
    _focusNode.unfocus();
    _isSubmitting.value = true;

    if (onSearch != null) {
      _error.value = await onSearch(_service.value, value);
      if (_error.value != null) {
        _isSubmitting.value = false;
        _isInputValid.value = false;
      }
    } else {
      await Future.delayed(Duration(milliseconds: 500));
    }

    _isSubmitting.value = false;
  }
}
```
Do you think I am doing something wrong?

`input_test.dart`

```dart
testWidgets('should display loader icon when input is submitting',
    (tester) async {
  await tester.pumpWidget(MaterialApp(
    home: MySelector(
      options: {
        'NAH': {
          'image': null,
          'description': 'blah blah blah blah blah',
        },
      },
    ),
  ));

  /// We have to wait for the slide up animation once it gets mounted:
  await tester.pumpAndSettle();

  final Finder service = find.byType(MySelectorService);
  expect(service, findsOneWidget);

  await tester.tap(service);
  await tester.pumpAndSettle();
  final Finder input = find.byType(TextFormField);
  expect(input, findsOneWidget);

  await tester.enterText(input, '1234567');
  await tester.pumpAndSettle();

  final Finder arrowIconFinder = find.byIcon(Icons.arrow_right_alt);
  final Icon arrowIcon = arrowIconFinder.evaluate().first.widget;
  expect(notNull(arrowIcon.color), false);

  await tester.tap(arrowIconFinder);
  print('======> ${find.byKey(MySelector.loaderInputIcon)}');
  await tester.pump(Duration(milliseconds: 500));

  final list = tester.stateList(find.byType(MySelector));
  print('--------------------------');
  print(list.toList());
  print('--------------------------');
});
```

**Comment by rrousselGit** [comment]
Are you sure that your onSubmit called and the line that modified the state is reached? Did you put a print inside a function and it showed in the test?

**Comment by normancarcamo** [comment]
@rrousselGit I think I am close to having a better idea of how all these things are working.

I took the log of my test file and also a test of the user interaction (manual testing using the emulator) to compare both and it surprises me that when testing the build method is not called as when I do it manually.

**Manual testing:**
### Log file
<details>
<summary>/Users/norman/.npm/_logs/2018-09-04T05_25_29_875Z-debug.log</summary>
<pre style="white-space:nowrap;">
flutter:    >>>>>>>>> build - isSubmitting? false.
flutter:    >>> _status.value = ServiceStatus.SELECTED;
flutter:    >>> _service.value = AAA;
flutter:    >>> _focusNode.requestFocus();
flutter:    >>>>>>>>> build - isSubmitting? false.
flutter:    >>> onFocusListener() -> _focusNode.hasFocus
flutter:    >>>>>>>>> build - isSubmitting? false.
flutter:    >>> onFocusListener() -> _focusNode.hasFocus -> _keyboardHeight.value 301.0
flutter:    >>> onFocusListener() -> _focusNode.hasFocus -> _error.value null
flutter:    >>>>>>>>> build - isSubmitting? false.
flutter:    >>>>>>>>> build - isSubmitting? false.
flutter:    >>> onSubmit! value: 876876876876876, ===> true ==> null
flutter:    >>> onSubmit(String value) -> _focusNode.unfocus();
flutter:    >>> onSubmit(String value) -> _isSubmitting.value = true;
flutter:    >>> onFocusListener() -> _keyboardHeight.value = 0.0;
flutter:    >>>>>>>>> build - isSubmitting? true.
flutter: Persistor debug: Starting save...
flutter: Persistor debug: Running save transformations
flutter: Persistor debug: Serializing
flutter: Persistor debug: Running save raw transformations
flutter: Persistor debug: Saving to storage
flutter: Persistor debug: Done saving!
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Exception: Error retrieving...
flutter: ----------------------------------------------------
flutter: [INFO] LoggingMiddleware: {Action: Instance of ...}
flutter:    >>> onSubmit(String value) -> _isSubmitting.value = false;
flutter:    >>>>>>>>> build - isSubmitting? false.
[log] Executed GraphQL call 'Retrieve...' in 2765ms with variables {service: AAA, serialNumber: 876876876876876}
flutter:    >>>>>>>>> build - isSubmitting? false.
</pre>
</details>

**flutter test:**

<details>
<summary>/Users/norman/.npm/_logs/2018-09-04T05_25_29_875Z-debug.log</summary>
<pre style="white-space:nowrap;">
00:04 +5 ~5: ServiceSelector input should display a loader icon when input is submitting
1. mount the widget...
   >>>>>>>>> build - isSubmitting? false.
2. wait for the animation...
3. tap on Service...
   >>> _status.value = ServiceStatus.SELECTED;
   >>> _service.value = AAA;
   >>> _focusNode.requestFocus();
4. await...
   >>>>>>>>> build - isSubmitting? false.
   >>> onFocusListener() -> _focusNode.hasFocus
   >>> onFocusListener() -> _focusNode.hasFocus -> _keyboardHeight.value 0.0
   >>> onFocusListener() -> _focusNode.hasFocus -> _error.value null
5. show keyboard
6. enterText... 876876876876876
7. await...
   >>>>>>>>> build - isSubmitting? false.
8. Tap on arrow icon:
   >>> onSubmit! value: 876876876876876, ===> true ==> null
   >>> onSubmit(String value) -> _focusNode.unfocus();
   >>> onSubmit(String value) -> _isSubmitting.value = true;
   >>> onSubmit(String value) -> else -> await Future.delayed(Duration(milliseconds: 500))
   >>> onSubmit(String value) -> _isSubmitting.value = false;
   >>> onFocusListener() -> _keyboardHeight.value = 0.0;
9. await...
   >>>>>>>>> build - isSubmitting? false.
00:05 +6 ~6: All tests passed!
</pre>
</details>

```dart
@override
Widget build(BuildContext context) {
  // `onOptionPressed` is called when the user presses an option from a list:
  void onOptionPressed(String id, ServiceStatus status) {
    if (status == ServiceStatus.NORMAL) {
      _status.value = ServiceStatus.SELECTED;
      print('   >>> _status.value = ${_status.value};');
    } else {
      _status.value = ServiceStatus.NORMAL;
      _textSerialController.clear();
      _isInputValid.value = false;
      _keyboardHeight.value = 0.0;
    }

    _service.value = id;
    print('   >>> _service.value = ${_service.value};');

    if (_service.value != null && _service.value.isNotEmpty) {
      print('   >>> _focusNode.requestFocus();');
      _focusNode.requestFocus();
    }
  }

  // `onFocusListener` used as an effect:
  void Function() onFocusListener() {
    void listener() async {
      if (_focusNode.hasFocus) {
        print('   >>> onFocusListener() -> _focusNode.hasFocus');
        // await 200 milliseconds for keyboard animation:
        await Future.delayed(Duration(milliseconds: 200));
        _keyboardHeight.value = MediaQuery.of(context).viewInsets.bottom;
        print('   >>> onFocusListener() -> _focusNode.hasFocus -> _keyboardHeight.value ${_keyboardHeight.value}');
        _error.value = null;
        print('   >>> onFocusListener() -> _focusNode.hasFocus -> _error.value ${_error.value}');
      } else {
        _keyboardHeight.value = 0.0;
        print('   >>> onFocusListener() -> _keyboardHeight.value = 0.0;');
      }
    }

    _focusNode.addListener(listener);
    return () => _focusNode.removeListener(listener);
  }

  // `onSubmit` The following snippet is used when the user presses the right arrow icon, 
  // the behavior expected to test is to check when the form is submitting, 
  // a different icon is set, otherwise, just keep it.
  void onSubmit(String value) async {
    print('   >>> onSubmit! value: $value, ===> ${_isInputValid.value} ==> ${_error.value}');
    if (_isInputValid.value && _error.value == null) {
      print('   >>> onSubmit(String value) -> _focusNode.unfocus();');
      _focusNode.unfocus();
      _isSubmitting.value = true;
      print('   >>> onSubmit(String value) -> _isSubmitting.value = true;');

      if (onSearch != null) {
        _error.value = await onSearch(_service.value, value);
        if (_error.value != null) {
          _isSubmitting.value = false;
          _isInputValid.value = false;
        }
      } else {
        print('   >>> onSubmit(String value) -> else -> await Future.delayed(Duration(milliseconds: 500))');
        // await Future.delayed(Duration(milliseconds: 500));
      }

      _isSubmitting.value = false;
      print('   >>> onSubmit(String value) -> _isSubmitting.value = false;');
    } else {
      print('2...............................');
    }
  }

  print('   >>>>>>>>> build - isSubmitting? ${_isSubmitting.value}.');

  return ...
}
```

Is this enough code to have a better idea of my case?

**Comment by rrousselGit** [comment]
There's too much code to make any reasonable conclusion. 
Unless you have a self-contained minimalist example, I don't think I can help you.

**Comment by rrousselGit** [comment]
Closing as this issue appears to be stale.
