### ISSUE TITLE
A TabController was used after being disposed.

### ISSUE THREAD

**Issue by AAverin** [rrousselGit/flutter_hooks#216]
I am trying to rebuild my `tabController` depending on some feature flags being on or off.

```
final featureFlags = useState(database.getFeatureFlags());
database.featureFlagsBox.watch(key: "feature_flags").listen((event) {
      featureFlags.value = event.value;
    });
final allPages = useMemoized(() {
      return _buildPages(featureFlags.value);
    }, [featureFlags.value]);
final _ticker = useSingleTickerProvider();
final _tabController = useTabController(initialLength: allPages.length, vsync: _ticker, keys: [featureFlags.value]);
```

Doing that results in and error:

```
The following assertion was thrown building CollectionsPage(dirty, dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#13ef1], _InheritedTheme], useState<FeatureFlags>: Instance of 'FeatureFlags', useMemoized<List<PageViewDescription>>: [Instance of 'PageViewDescription'], useSingleTickerProvider):
A TabController was used after being disposed.

Once you have called dispose() on a TabController, it can no longer be used.
The relevant error-causing widget was: 
  CollectionsPage .../lib/components/screens/home/HomeScreen.dart:44:67
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:212:12)
#3      TabController.dispose (package:flutter/src/material/tab_controller.dart:299:11)
#4      _TabControllerHookState.dispose (package:flutter_hooks/src/tab_controller.dart:57:33)
```

Probably related to https://github.com/rrousselGit/flutter_hooks/issues/81

**Comment by rrousselGit** [comment]
Sorry for the late reply. Could you share a complete snippet and steps to reproduce the problem?

The code you gave isn't enough to reproduce it.

**Comment by AAverin** [comment]
Wow, ok, this was a long time ago =) I have either found a fix or a workaround, or removed flags.
I will try to dig into my code to find some details.

**Comment by rrousselGit** [comment]
Haha thanks!

**Comment by codewithbek** [comment]
I also faced this problem.


I/flutter (19792): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19792): The following assertion was thrown building ModalProgressHUD:
I/flutter (19792): A TabController was used after being disposed.
I/flutter (19792): Once you have called dispose() on a TabController, it can no longer be used.
I/flutter (19792):
I/flutter (19792): The relevant error-causing widget was:
I/flutter (19792):   ModalProgressHUD
I/flutter (19792):   ModalProgressHUD:file:///C:/Udevs/yapona_mama_client_mobile/lib/ui/main/home/home_page.dart:131:33
I/flutter (19792):
I/flutter (19792): When the exception was thrown, this was the stack:
I/flutter (19792): #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
I/flutter (19792): #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
I/flutter (19792): #2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:238:27)
I/flutter (19792): #3      _VerticalScrollableTabViewState.initState (package:vertical_scrollable_tabview/vertical_scrollable_tabview.dart:157:27)
I/flutter (19792): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
I/flutter (19792): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
I/flutter (19792): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
I/flutter (19792): #7      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
I/flutter (19792): #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
I/flutter (19792): ...     Normal element mounting (15 frames)
I/flutter (19792): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
I/flutter (19792): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3701:20)
I/flutter (19792): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
I/flutter (19792): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
I/flutter (19792): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
I/flutter (19792): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
I/flutter (19792): #29     Element.updateChildren (package:flutter/src/widgets/framework.dart:3834:32)
I/flutter (19792): #30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
I/flutter (19792): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
I/flutter (19792): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
I/flutter (19792): #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
I/flutter (19792): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
I/flutter (19792): #35     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
I/flutter (19792): #36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
I/flutter (19792): #37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
I/flutter (19792): #38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
I/flutter (19792): #39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
I/flutter (19792): #40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
I/flutter (19792): #41     _invoke (dart:ui/hooks.dart:170:13)
I/flutter (19792): #42     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
I/flutter (19792): #43     _drawFrame (dart:ui/hooks.dart:140:31)


import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:scroll_to_index/scroll_to_index.dart';
import 'package:vertical_scrollable_tabview/vertical_scrollable_tabview.dart';
import 'package:yapona_mama_client_mobile/base/base_functions.dart';
import 'package:yapona_mama_client_mobile/controller/home/home_controller.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/custom_android_ios_indicator.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/custom_circular_progress_indicator.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/flappy_searchbar/flappy_search_bar.dart'
    as flappy;
import 'package:yapona_mama_client_mobile/core/custom_widgets/modal_progress_hud.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_colors.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_icons.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_text_style.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_utils.dart';
import 'package:yapona_mama_client_mobile/data/models/category_v2_response.dart'
    as t;
import 'package:yapona_mama_client_mobile/data/models/product_by_id_response.dart';
import 'package:yapona_mama_client_mobile/routes/app_pages.dart';
import 'package:yapona_mama_client_mobile/routes/args/product_detail_page_arguments.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/category_item.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/product_list_widget.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/search_item.dart';

import '../../../data/models/products_v2_response.dart';
import 'widgets/banner_widget.dart';

class HomePage extends GetView<HomeController> {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) => GetBuilder<HomeController>(
        builder: (ctr) => Scaffold(
          appBar: AppBar(
            centerTitle: false,
            scrolledUnderElevation: 0,
            title: InkWell(
              borderRadius: AppUtils.kBorderRadius8,
              onTap: () {
                Get.toNamed<void>(AppRoutes.deliveryTypeMap);
                return;
              },
              child: Ink(
                padding: AppUtils.kAllPadding2,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (ctr.deliveryAddress != null || ctr.pickUpBranch != null)
                      Text(ctr.deliveryAddress != null
                          ? 'delivery'.tr
                          : 'self_call'.tr),
                    AppUtils.kBoxHeight2,
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(
                          AppIcons.location,
                          size: 16,
                        ),
                        AppUtils.kBoxWidth8,
                        Flexible(
                          child: ConstrainedBox(
                            constraints: BoxConstraints(
                              maxWidth: Get.width * 0.8,
                            ),
                            child: ctr.deliveryAddress != null ||
                                    ctr.pickUpBranch != null
                                ? Text(
                                    ctr.deliveryAddress != null
                                        ? ctr.deliveryAddress?.addressName ?? ''
                                        : ctr.pickUpBranch?.branchName ?? '',
                                    overflow: TextOverflow.ellipsis,
                                    semanticsLabel: 'current_address',
                                    style: AppTextStyles.blackText15,
                                  )
                                : Text(
                                    'add_address'.tr,
                                    style: AppTextStyles.blackText15,
                                  ),
                          ),
                        ),
                        AppUtils.kBoxWidth8,
                        const Icon(
                          Icons.keyboard_arrow_down_outlined,
                          color: AppColors.black3,
                          size: 16,
                        )
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
          body: flappy.SearchBar<Products>(
            onError: (error) => Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  AppUtils.kBoxHeight2,
                  const Image(
                    image: AssetImage(
                      'assets/png/ic_paper_bag.png',
                    ),
                    width: 120,
                    height: 120,
                  ),
                  Text(
                    'not_found'.tr,
                    style: stySearchNotFound,
                  )
                ],
              ),
            ),
            hintText: 'search'.tr,
            hintStyle: stySearchItem.copyWith(color: AppColors.grey),
            textStyle: stySearchItem,
            searchBarPadding: const EdgeInsets.only(
              right: 12,
              left: 12,
              bottom: 16,
            ),
            focusNode: FocusNode(),
            cancellationWidget: Text(
              'cancel'.tr,
              maxLines: 1,
              style: stySearchItem,
              textAlign: TextAlign.center,
            ),
            placeHolder: GetBuilder<HomeController>(
              builder: (ctr) => ModalProgressHUD(
                inAsyncCall: ctr.isLoading.value,
                child: ctr.tabController == null
                    ? AppUtils.kBox
                    : VerticalScrollableTabView(
                        physics: const BouncingScrollPhysics(),
                        listItemData: ctr.categories,
                        eachItemChild: (o, index) => ProductListWidget(
                          category: o as t.Categories,
                        ),
                        tabController: ctr.tabController!,
                        keyboardDismissBehavior:
                            ScrollViewKeyboardDismissBehavior.onDrag,
                        autoScrollController: ctr.autoScrollController,
                        slivers: [
                          SliverAppBar(
                            pinned: true,
                            expandedHeight: 0,
                            floating: true,
                            toolbarHeight: 0,
                            elevation: 0,
                            titleSpacing: 0,
                            bottom: PreferredSize(
                              preferredSize: const Size.fromHeight(66),
                              child: TabBar(
                                unselectedLabelColor: AppColors.assets,
                                padding: AppUtils.kPadding1241212,
                                labelPadding: AppUtils.kHorizontalPadding4,
                                isScrollable: true,
                                indicator: const BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: AppUtils.kBorderRadius16,
                                  border: Border.fromBorderSide(
                                    BorderSide(
                                      color: AppColors.assets,
                                      width: 1.4,
                                    ),
                                  ),
                                  boxShadow: [
                                    BoxShadow(
                                      color: AppColors.grey300,
                                      spreadRadius: 2,
                                      blurRadius: 8,
                                      offset: Offset(0, 7),
                                    ),
                                  ],
                                ),
                                controller: ctr.tabController,
                                tabs: List.generate(
                                  ctr.categories.length,
                                  (index) => Tab(
                                    height: 48,
                                    child: CategoryItem(
                                      text: BaseFunctions.getTranslateLanguage(
                                        ctr.categories[index].title,
                                      ),
                                      image: ctr.categories[index].image ?? '',
                                    ),
                                  ),
                                ),
                                onTap: (index) {
                                  ctr.autoScrollController
                                      .scrollToIndex(
                                    index,
                                    duration: const Duration(milliseconds: 100),
                                    preferPosition: AutoScrollPosition.begin,
                                  )
                                      .then((value) {
                                    ctr.tabIndex = index;
                                    ctr.tabController!.index = index;
                                  });

                                  VerticalScrollableTabBarStatus.setIndex(
                                    index,
                                  );
                                },
                              ),
                            ),
                          ),
                          CustomAndroidIosIndicator(
                            onRefreshAndroid: () async {
                              await ctr.refreshCategoryWithProductsV2();
                              return;
                            },
                            onRefreshIos: () async {
                              await ctr.refreshCategoryWithProductsV2();
                              return;
                            },
                          ),
                          const SliverToBoxAdapter(child: BannerWidget()),
                        ],
                      ),
              ),
            ),
            onItemFound: (product, index) => SearchItem(
              product: product,
              onTap: () {
                Get.toNamed<void>(
                  AppRoutes.productDetail,
                  arguments: ProductDetailPageArguments(
                    product: ProductByIdResponse(
                      id: product?.id,
                      image: product?.image,
                      title: product?.title,
                      description: product?.description,
                    ),
                  ),
                );
              },
            ),
            onSearch: ctr.searchProductV2,
            listPadding: AppUtils.kAllPadding12,
            loader: const Center(child: CustomCircularProgressIndicator()),
          ),
        ),
      );
}

**Comment by codewithbek** [comment]
I also faced this problem.

I/flutter (19792): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19792): The following assertion was thrown building ModalProgressHUD:
I/flutter (19792): A TabController was used after being disposed.
I/flutter (19792): Once you have called dispose() on a TabController, it can no longer be used.
I/flutter (19792):
I/flutter (19792): The relevant error-causing widget was:
I/flutter (19792): ModalProgressHUD
I/flutter (19792): ModalProgressHUD:file:///C:/Udevs/yapona_mama_client_mobile/lib/ui/main/home/home_page.dart:131:33
I/flutter (19792):
I/flutter (19792): When the exception was thrown, this was the stack:
I/flutter (19792): #0 ChangeNotifier.debugAssertNotDisposed. (package:flutter/src/foundation/change_notifier.dart:179:9)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/1 ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/2 ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:238:27)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/3 _VerticalScrollableTabViewState.initState (package:vertical_scrollable_tabview/vertical_scrollable_tabview.dart:157:27)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/4 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430:55)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/5 ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273:5)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/6 Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/7 MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6569:36)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/8 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6581:32)
I/flutter (19792): ... Normal element mounting (15 frames)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/23 Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182:16)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/24 Element.updateChild (package:flutter/src/widgets/framework.dart:3701:20)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/25 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/26 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/27 ProxyElement.update (package:flutter/src/widgets/framework.dart:5628:5)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/28 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/29 Element.updateChildren (package:flutter/src/widgets/framework.dart:3834:32)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/30 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6594:17)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/31 Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/32 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322:16)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/33 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/34 Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/35 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/36 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/37 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/38 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/39 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/40 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/41 _invoke (dart:ui/hooks.dart:170:13)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/pull/42 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
I/flutter (19792): https://github.com/rrousselGit/flutter_hooks/issues/43 _drawFrame (dart:ui/hooks.dart:140:31)

**Comment by codewithbek** [comment]
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:scroll_to_index/scroll_to_index.dart';
import 'package:vertical_scrollable_tabview/vertical_scrollable_tabview.dart';
import 'package:yapona_mama_client_mobile/base/base_functions.dart';
import 'package:yapona_mama_client_mobile/controller/home/home_controller.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/custom_android_ios_indicator.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/custom_circular_progress_indicator.dart';
import 'package:yapona_mama_client_mobile/core/custom_widgets/flappy_searchbar/flappy_search_bar.dart'
    as flappy;
import 'package:yapona_mama_client_mobile/core/custom_widgets/modal_progress_hud.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_colors.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_icons.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_text_style.dart';
import 'package:yapona_mama_client_mobile/core/theme/app_utils.dart';
import 'package:yapona_mama_client_mobile/data/models/category_v2_response.dart'
    as t;
import 'package:yapona_mama_client_mobile/data/models/product_by_id_response.dart';
import 'package:yapona_mama_client_mobile/routes/app_pages.dart';
import 'package:yapona_mama_client_mobile/routes/args/product_detail_page_arguments.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/category_item.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/product_list_widget.dart';
import 'package:yapona_mama_client_mobile/ui/main/home/widgets/search_item.dart';

import '../../../data/models/products_v2_response.dart';
import 'widgets/banner_widget.dart';

class HomePage extends GetView<HomeController> {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) => GetBuilder<HomeController>(
        builder: (ctr) => Scaffold(
          appBar: AppBar(
            centerTitle: false,
            scrolledUnderElevation: 0,
            title: InkWell(
              borderRadius: AppUtils.kBorderRadius8,
              onTap: () {
                Get.toNamed<void>(AppRoutes.deliveryTypeMap);
                return;
              },
              child: Ink(
                padding: AppUtils.kAllPadding2,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    if (ctr.deliveryAddress != null || ctr.pickUpBranch != null)
                      Text(ctr.deliveryAddress != null
                          ? 'delivery'.tr
                          : 'self_call'.tr),
                    AppUtils.kBoxHeight2,
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Icon(
                          AppIcons.location,
                          size: 16,
                        ),
                        AppUtils.kBoxWidth8,
                        Flexible(
                          child: ConstrainedBox(
                            constraints: BoxConstraints(
                              maxWidth: Get.width * 0.8,
                            ),
                            child: ctr.deliveryAddress != null ||
                                    ctr.pickUpBranch != null
                                ? Text(
                                    ctr.deliveryAddress != null
                                        ? ctr.deliveryAddress?.addressName ?? ''
                                        : ctr.pickUpBranch?.branchName ?? '',
                                    overflow: TextOverflow.ellipsis,
                                    semanticsLabel: 'current_address',
                                    style: AppTextStyles.blackText15,
                                  )
                                : Text(
                                    'add_address'.tr,
                                    style: AppTextStyles.blackText15,
                                  ),
                          ),
                        ),
                        AppUtils.kBoxWidth8,
                        const Icon(
                          Icons.keyboard_arrow_down_outlined,
                          color: AppColors.black3,
                          size: 16,
                        )
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
          body: flappy.SearchBar<Products>(
            onError: (error) => Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  AppUtils.kBoxHeight2,
                  const Image(
                    image: AssetImage(
                      'assets/png/ic_paper_bag.png',
                    ),
                    width: 120,
                    height: 120,
                  ),
                  Text(
                    'not_found'.tr,
                    style: stySearchNotFound,
                  )
                ],
              ),
            ),
            hintText: 'search'.tr,
            hintStyle: stySearchItem.copyWith(color: AppColors.grey),
            textStyle: stySearchItem,
            searchBarPadding: const EdgeInsets.only(
              right: 12,
              left: 12,
              bottom: 16,
            ),
            focusNode: FocusNode(),
            cancellationWidget: Text(
              'cancel'.tr,
              maxLines: 1,
              style: stySearchItem,
              textAlign: TextAlign.center,
            ),
            placeHolder: GetBuilder<HomeController>(
              builder: (ctr) => ModalProgressHUD(
                inAsyncCall: ctr.isLoading.value,
                child: ctr.tabController == null
                    ? AppUtils.kBox
                    : VerticalScrollableTabView(
                        physics: const BouncingScrollPhysics(),
                        listItemData: ctr.categories,
                        eachItemChild: (o, index) => ProductListWidget(
                          category: o as t.Categories,
                        ),
                        tabController: ctr.tabController!,
                        keyboardDismissBehavior:
                            ScrollViewKeyboardDismissBehavior.onDrag,
                        autoScrollController: ctr.autoScrollController,
                        slivers: [
                          SliverAppBar(
                            pinned: true,
                            expandedHeight: 0,
                            floating: true,
                            toolbarHeight: 0,
                            elevation: 0,
                            titleSpacing: 0,
                            bottom: PreferredSize(
                              preferredSize: const Size.fromHeight(66),
                              child: TabBar(
                                unselectedLabelColor: AppColors.assets,
                                padding: AppUtils.kPadding1241212,
                                labelPadding: AppUtils.kHorizontalPadding4,
                                isScrollable: true,
                                indicator: const BoxDecoration(
                                  color: Colors.white,
                                  borderRadius: AppUtils.kBorderRadius16,
                                  border: Border.fromBorderSide(
                                    BorderSide(
                                      color: AppColors.assets,
                                      width: 1.4,
                                    ),
                                  ),
                                  boxShadow: [
                                    BoxShadow(
                                      color: AppColors.grey300,
                                      spreadRadius: 2,
                                      blurRadius: 8,
                                      offset: Offset(0, 7),
                                    ),
                                  ],
                                ),
                                controller: ctr.tabController,
                                tabs: List.generate(
                                  ctr.categories.length,
                                  (index) => Tab(
                                    height: 48,
                                    child: CategoryItem(
                                      text: BaseFunctions.getTranslateLanguage(
                                        ctr.categories[index].title,
                                      ),
                                      image: ctr.categories[index].image ?? '',
                                    ),
                                  ),
                                ),
                                onTap: (index) {
                                  ctr.autoScrollController
                                      .scrollToIndex(
                                    index,
                                    duration: const Duration(milliseconds: 100),
                                    preferPosition: AutoScrollPosition.begin,
                                  )
                                      .then((value) {
                                    ctr.tabIndex = index;
                                    ctr.tabController!.index = index;
                                  });

                                  VerticalScrollableTabBarStatus.setIndex(
                                    index,
                                  );
                                },
                              ),
                            ),
                          ),
                          CustomAndroidIosIndicator(
                            onRefreshAndroid: () async {
                              await ctr.refreshCategoryWithProductsV2();
                              return;
                            },
                            onRefreshIos: () async {
                              await ctr.refreshCategoryWithProductsV2();
                              return;
                            },
                          ),
                          const SliverToBoxAdapter(child: BannerWidget()),
                        ],
                      ),
              ),
            ),
            onItemFound: (product, index) => SearchItem(
              product: product,
              onTap: () {
                Get.toNamed<void>(
                  AppRoutes.productDetail,
                  arguments: ProductDetailPageArguments(
                    product: ProductByIdResponse(
                      id: product?.id,
                      image: product?.image,
                      title: product?.title,
                      description: product?.description,
                    ),
                  ),
                );
              },
            ),
            onSearch: ctr.searchProductV2,
            listPadding: AppUtils.kAllPadding12,
            loader: const Center(child: CustomCircularProgressIndicator()),
          ),
        ),
      );
}
