### ISSUE TITLE
widget not rebuild after set value 

### ISSUE THREAD

**Issue by tazik561** [rrousselGit/flutter_hooks#218]
I am using Hook widget to create my custom widget. In my widget I have TextFormField to user add password. I added FlutterPasswordStrength to my project. I want to check user's password strong and show to user that what your password is strong:

      @override
      Widget build(BuildContext context) {
        final _formKey = useMemoized(() => GlobalKey<FormState>());
        final _toogleShowPass = useState(true);
        final _strungPass = useState("requierd");
        final password = useState("");
        return Form(
          key: _formKey,
          child: Column(
          ....
          TextFormField(
          obscureText: _toogleShowPass.value,
          onChanged: (value) {
               password.value = value;
          },
          Row(
          children: [
              Container(
                 width: 100,
                 child: Text(
                 _strungPass.value,
                 style: TextStyle(color: Colors.white),
                  ),
               ),
               Expanded(
                  child: FlutterPasswordStrength(
                  password: password.value,
                  height: 5,
                  radius: 10,
                  strengthCallback: (strength) {
                        debugPrint(strength.toString());
                        if (strength < 0.25) {
                                _strungPass.value = "weak";
                              } else if (strength < 0.5) {
                                _strungPass.value = "not bad";
                              } else if (strength < 0.75) {
                                _strungPass.value = "alright";
                              } else {
                                _strungPass.value = "strong";
                                print('This passsword is strong!');
                              }
                            },
                          ),
                        ),
                      ],
                    ),

But when I am trying to add password I got This error:

    ════════ Exception caught by foundation library ════════════════════════════════
    The following assertion was thrown while dispatching notifications for ValueNotifier<String>:
    setState() or markNeedsBuild() called during build.
    
    This MainTextFormFileds widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
    The widget on which setState() or markNeedsBuild() was called was: MainTextFormFileds
        dependencies: [_LocalizationsScope-[GlobalKey#3dcb7]]
        useMemoized<GlobalKey<FormState>>: [LabeledGlobalKey<FormState>#9b2d2]
        useState<bool>: true
        useState<String>: weak
        useState<String>: 1
    The widget which was currently being built when the offending call was made was: Expanded
        flex: 1
    When the exception was thrown, this was the stack
    #0      Element.markNeedsBuild.<anonymous closure>
    package:flutter/…/widgets/framework.dart:4292
    #1      Element.markNeedsBuild
    package:flutter/…/widgets/framework.dart:4307
    #2      HookState.setState
    package:flutter_hooks/src/framework.dart:299
    #3      _StateHookState._listener
    package:flutter_hooks/src/primitives.dart:264
    #4      ChangeNotifier.notifyListeners
    package:flutter/…/foundation/change_notifier.dart:226
    ...
    The ValueNotifier<String> sending notification was: ValueNotifier<String>#57a88(weak)

When User add first character,`_strungPass.value` in `FlutterPasswordStrength` initialized but the problem is here!!! When `_strungPass.value` get it's value, The build method not rebuild and I got error.

**Comment by rrousselGit** [comment]
"strengthCallback" appears to be called in initState/build

As such it cannot be used to modify its parent's state. 

You'll have to refactor your widgets to not rely on "strengthCallback"

**Comment by tazik561** [comment]
> "strengthCallback" appears to be called in initState/build
> 
> As such it cannot be used to modify its parent's state.
> 
> You'll have to refactor your widgets to not rely on "strengthCallback"

FlutterPasswordStrength get a string and after doing some operation, return result. What is your idea about refactoring strengthCallback? How can I implemented so that parent's state triggered and  strengthCallback can be returned value?

**Comment by rrousselGit** [comment]
That's up to you to figure out. But one thing is certain: The issue is with `FlutterPasswordStrength`, not flutter_hooks.
