### ISSUE TITLE
useState should handle unmounted automatically

### ISSUE THREAD

**Issue by adam-ashored** [rrousselGit/flutter_hooks#219]
**Is your feature request related to a problem? Please describe.**
I find myself constantly writing code that looks like this:

```
 const working = useState(false);
 const isMounted = useIsMounted(false);

 Future<void> doSomething() async {
    working.value = true;
    await someFuture();
    if(isMounted()) working.value = false;
 }
```
Because if I don't do an `isMounted` check then I might get an unhandled exception:

`Once you have called dispose() on a ValueNotifier<...>, it can no longer be used.`

**Describe the solution you'd like**
I would like `useState` to take care of this boilerplate logic for me. In React, we get a warning about updating state on an unmounted component being a noop.

Yeah, I understand this might require changing the value returned from `useState`, but not necessarily the interface. 

Spitballing, I came up with this, although it does look a bit verbose:

```
import 'package:flutter/foundation.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class UseMountedSafeState<T> extends ValueNotifier<T> {
  final ValueNotifier<T> _value;
  final bool Function() _isMounted;

  set value(T value) {
    if (_isMounted()) {
      _value.value = value;
      super.value = value;
      return;
    }

    print('Attempting to set a value $value in an unmounted widget');
  }

  UseMountedSafeState(this._value, this._isMounted) : super(_value.value);
}

UseMountedSafeState<T> useMountedSafeState<T>([T initialData]) =>
    useValueNotifier(
      UseMountedSafeState(
        useState(initialData),
        useIsMounted(),
      ),
    ).value;
```

**Describe alternatives you've considered**
Writing a lot of boilerplate code.

**Additional context**
N/A

**Comment by adam-ashored** [comment]
On further inspection of similar issues, I realize the best place to convert all these exceptions to warnings (if that's desirable) is probably down in individual hooks. Instead of returning a raw `ValueNotifier`, return a class that extends `ValueNotifier` that performs an `isMounted` check.

**Comment by rrousselGit** [comment]
The current behavior is expected

It behaves like setState. And setState throws on purpose. 

This exception exists so that instead of checking "mounted" to avoid calling setState, you should refactor your code to cancel pending requests.

**Comment by adam-ashored** [comment]
@rrousselGit thanks for the reply!

Firstly, I want to thank you for the port of hooks to flutter, it's been a breeze ramping up on flutter coming from a react world with the help of this library.

My personal opinion is that throwing when calling `setState` was a poor design decision by the flutter team when a warning would've served the purpose. Maybe I'm biased because I like the way react handles this scenario. 

The alternative creating custom, reusable, hooks like this (simplified, of course):

```
final Something useMyCustomHook(dynamic someArg) {
    final isMounted = useIsMounted();
    final fetching = useState(false);
    final error = useState(false);
    final response = useState();

    final Future<dynamic> fetch() async {
           fetching.value = true;
           try {
               final val = await someExternalApi(someArg);
               if(isMounted()) response.value = val; // check to see if we're still mounted
           } catch(e) {
               if(isMounted()) error.value = true; // check to see if we're still mounted
          } finally {
              if(isMounted()) fetching.value = false; // check to see if we're still mounted
          }
    
    }

    return Something(
        fetch,
        fetching.value,
        error.value,
        response.value,
    );
}
```

is to just set the future as state and then use `FutureBuilder` everywhere and let it handle the mounted logic. Ultimately, **something** handles the mounted logic for async stuff, it could be `FutureBuilder`, or it could be a `useMountedSafeState`, or it could be something else. Also, by using `FutureBuilder`, instead of the above, it decreases the ability to create good reusable custom hooks that you can use across various components.

I've written a good number of reusable hooks like this, and the constant `isMounted` checks are tiresome.

**Comment by davidmartos96** [comment]
@adam-ashored Have you tried useFuture? Is a "flat" version of FutureBuilder. So you get the AsyncSnapshot that you can use to handle the loading and error states.

**Comment by rrousselGit** [comment]
As I said, checkign `mounted` is not the correct approach. Instead you should cancel your pending requests.

But to begin with, what you're doing is already taken care of by `useFuture`


You could do:


```dart
final future = useState<Future<Response>>();
final snapshot = useFuture(future.value);

return ElevatedButton(
  onPressed: () => future.value = dio.get('api')
)
```

**Comment by adam-ashored** [comment]
@rrousselGit  and @davidmartos96 you got it, `useFuture` does it. Thanks for the education!
