### ISSUE TITLE
useEffect hook not working properly

### ISSUE THREAD

**Issue by abahnj** [rrousselGit/flutter_hooks#220]
**Describe the bug**
I am trying to use a useEffect hook to register a listener on a scroll controller but I also need to ensure that it is attached and has dimensions before I pull values from it. Because of the conditional it doesn't update properly

**To Reproduce**

```dart
useEffect(() {
      listener = () {
        if (_scrollController.position.haveDimensions) {
          final dimension =
              _scrollController.position.maxScrollExtent / (8 - 2);
          _physics ??= CustomScrollPhysics(itemDimension: dimension);
          _position.value = _scrollController.position.pixels / dimension;

        }
      };
      _scrollController..addListener(listener);

      return () {
        _scrollController.removeListener(listener);
      };
    }, [_scrollController]);

```
**Expected behavior**
That the useEffect gets recalled when the scroll controller value changes and it has positions

**Comment by rrousselGit** [comment]
useEffect issue the issue here.
You need to separately listen to `controller.position`

```dart
_scrollController.position.addListener(...)
```

**Comment by abahnj** [comment]
Really sorry to be a bother, but also attaching a listener straight to the positions in the useEffect hook isn't possible cause it the scroll controller doesn't have any clients yet and making it dependent on when it has clients also leads to the same effect. Any suggestions or am I doing something wrong?

**Comment by Agondev** [comment]
> Really sorry to be a bother, but also attaching a listener straight to the positions in the useEffect hook isn't possible cause it the scroll controller doesn't have any clients yet and making it dependent on when it has clients also leads to the same effect. Any suggestions or am I doing something wrong?

```dart
useEffect(() {
      void listener() {
        var index = (useListScrollController.offset / _itemExtent).round() + 1;
        print(index);
      }

      if (WidgetsBinding.instance != null &&
          useListScrollController.hasClients) {
        WidgetsBinding.instance!.addPostFrameCallback(
            (_) => useListScrollController.addListener(listener));
        // WidgetsBinding.instance!.addPostFrameCallback(
        //     (_) => useListScrollController.position.addListener(listener));
      }

      return () => useListScrollController.position.removeListener(listener);
    }, [
      useListScrollController.hasClients,
      useListScrollController,
      WidgetsBinding.instance
    ]);
```
This works for me.
Both useScrollController.addListener as well as useScrollController.position.addListener work using this.

**Comment by abahnj** [comment]
Thanks a lot
