### ISSUE TITLE
Invalid error message for useSingleTickerProvider

### ISSUE THREAD

**Issue by Serjlee** [rrousselGit/flutter_hooks#223]
**Is your feature request related to a problem? Please describe.**
I attempted to use `flutter_hooks` in a place where I had a `TickerProviderMixin`, but `flutter_hooks` only provides a `useSingleTickerProvider`. Attempting to use the latter throws an error which gives an unhelpful advice:

> If a TickerProvider is
> used for multiple AnimationController objects, or if it is passed to other objects and those objects
> might use it more than one time in total, then instead of using useSingleTickerProvider, use a
> regular useTickerProvider.

(I guess that comes from some copy-paste from the `SingleTickerProviderMixin`)

**Describe the solution you'd like**
A `useTickerProvider` hook that works like `TickerProviderMixin`, in the same way `useSingleTickerProvider` replaces `SingleTickerProviderMixin`

**Describe alternatives you've considered**
I attempted to cobble together a hook while a) barely understanding the concept of Tickers b) just tipping my toes in `flutter_hooks`. It works, but I kinda don't know how ¯\\_(ツ)_/¯:
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

/// Creates a full-fledged [TickerProvider].
///
/// See also:
///  * [TickerProviderStateMixin]
TickerProvider useTickerProvider({List<Object?>? keys}) {
  return use(
    keys != null ? _TickerProviderHook(keys) : const _TickerProviderHook(),
  );
}

class _TickerProviderHook extends Hook<TickerProvider> {
  const _TickerProviderHook([List<Object?>? keys]) : super(keys: keys);

  @override
  _TickerProviderHookState createState() => _TickerProviderHookState();
}

class _TickerProviderHookState
    extends HookState<TickerProvider, _TickerProviderHook>
    implements TickerProvider {
  Set<Ticker>? _tickers;

  @override
  Ticker createTicker(TickerCallback onTick) {
    _tickers ??= <_HookTicker>{};
    final _HookTicker result =
        _HookTicker(onTick, this, debugLabel: 'created by $this');
    _tickers!.add(result);
    return result;
  }

  void _removeTicker(_HookTicker ticker) {
    assert(_tickers != null);
    assert(_tickers!.contains(ticker));
    _tickers!.remove(ticker);
  }

  @override
  void dispose() {
    assert(() {
      if (_tickers != null) {
        for (final Ticker ticker in _tickers!) {
          if (ticker.isActive) {
            throw FlutterError.fromParts(<DiagnosticsNode>[
              ErrorSummary('$this was disposed with an active Ticker.'),
              ErrorDescription(
                  '$runtimeType created a Ticker via its useTickerProvider, but at the time '
                  'dispose() was called on the mixin, that Ticker was still active. All Tickers must '
                  'be disposed before calling super.dispose().'),
              ErrorHint('Tickers used by AnimationControllers '
                  'should be disposed by calling dispose() on the AnimationController itself. '
                  'Otherwise, the ticker will leak.'),
              ticker.describeForError('The offending ticker was'),
            ]);
          }
        }
      }
      return true;
    }());
    super.dispose();
  }

  @override
  TickerProvider build(BuildContext context) {
    if (_tickers != null) {
      for (final Ticker ticker in _tickers!) {
        ticker.muted = !TickerMode.of(context);
      }
    }
    return this;
  }

  @override
  String get debugLabel => 'useTickerProvider';

  @override
  bool get debugSkipValue => true;
}

class _HookTicker extends Ticker {
  _HookTicker(TickerCallback onTick, this._creator, {String? debugLabel})
      : super(onTick, debugLabel: debugLabel);

  final _TickerProviderHookState _creator;

  @override
  void dispose() {
    _creator._removeTicker(this);
    super.dispose();
  }
}
```

**Additional context**
If there a way to leverage using just `useSingleTickerProvider`? My current use case is simply a list with animated items, I can try to extract a minimal example, if useful

**Comment by rrousselGit** [comment]
You can use `useSingleTickerProvider` multiple times. You're not limited to one per widget

So I'm not sure this would be useful

**Comment by modulovalue** [comment]
@rrousselGit useSingleTickerProvider can result in runtime errors if accidentally used multiple times. A useTickerProvider would not have this issue. That is very useful.

**Comment by Serjlee** [comment]
(sorry for the late reply!)

Indeed, I had a screen where many requests could cause multiple animations at the same time. Since it was wanted, a "full" TickerProvider was very handy to handle the issue. Other solutions are of course possible, but I think using a `TickerProvider` is a fairly common one

@rrousselGit if you don't plan to add `useTickerProvider` I don't mind, but I'd at least fix [the error message that's telling you to use it](https://github.com/rrousselGit/flutter_hooks/blob/6d590cd3204f0978b3d9cdc23435a5e279c73f55/packages/flutter_hooks/lib/src/animation.dart#L176), since it caused me to shuffle through the source history for quite a bit looking for the phantom hook
