### ISSUE TITLE
Add postBuild event

### ISSUE THREAD

**Issue by jaumard** [rrousselGit/flutter_hooks#225]
**Is your feature request related to a problem? Please describe.**
I want to create a custom hook to replace `Observer` from mobx to his hook equivalent, from our discussion on slack you told me it was not possible until hooks have postBuild event. 

So I would like to work on this and make a PR, can you give me more details of what need to be done in order to add that event ? Some specs so I don't start wrong :) 

Thanks! Really love hooks!

**Comment by jaumard** [comment]
I've seen this https://stackoverflow.com/questions/51216448/is-there-any-callback-to-tell-me-when-build-function-is-done-in-flutter 

So I'm wondering if the postBuild you referring is like this:
```
WidgetsBinding.instance.addPostFrameCallback((_) {
  hook.postBuild();
})
```

**Comment by rrousselGit** [comment]
That won't work, because it is no longer "when the build method completed" but rather "when all widgets finished building"

**Comment by jaumard** [comment]
Yeah I continued my search after finding that and created the PR with my new findings and it's indeed not using the  `addPostFrameCallback`

**Comment by rrousselGit** [comment]
Closing as I don't plan on making such life-cycle after-all
