### ISSUE TITLE
useState() return ValueNotifier, which may not response object change

### ISSUE THREAD

**Issue by peterweb2005** [rrousselGit/flutter_hooks#230]
eg:
ValueNotifier does not notify listeners when modifying a list #29958
https://github.com/flutter/flutter/issues/29958

which needs
```
notifyListeners()
```
to trigger rebuild,
but notifyListeners() has compiler warning, as marked protected

is there more propery way? 
eg: other than useState() or my usage of useState() is bad?

**Comment by EdwynZN** [comment]
This has always been a documentation problem related to ValuenNotifier

final myState = useState(<int>[1, 2, 3]);
.....

```
myState.value[0] = 7; // won't rebuild
var list = myState.value;
list[0] = 9;
myState.value = list;
```

This is because the notifylistener() is inside the setter of `value` and won't trigger when you use the operator `[]` of a list. The other option is to create your own hook with a change notifier to have more control on your state

**Comment by peterweb2005** [comment]
yes

and btw
there is state_notifier which also created by the creator
https://github.com/rrousselGit/state_notifier

**Comment by EdwynZN** [comment]
Yeah but state_notifier suffers the same problem, using [] won't rebuild, only updating from the setter, this is to avoid dangerous situations where objects change attributes without calling notify listeners

**Comment by peterweb2005** [comment]
Thanks

so this case need stream?

**Comment by EdwynZN** [comment]
You can use that or simply use my example changing the list and then using the setter to notify, it's fairly simple

**Comment by peterweb2005** [comment]
yes, i currently turn to reducer, seems well

but did initialAction "required"? cant the state start with data?
```
Store<State, Action> useReducer<State, Action>(
  Reducer<State, Action> reducer, {
  required State initialState,
  required Action initialAction,
}) {
```

**Comment by peterweb2005** [comment]
also wonder if reducer is necessary,
why has useState()

**Comment by rrousselGit** [comment]
@EdwynZN You should not mutate collections

Instead of:

```dart
final myState = useState(<int>[1, 2, 3]);
myState.value[0] = 7; // won't rebuild
```

do:

```dart
final myState = useState(<int>[1, 2, 3]);
myState.value = [...myState.value, 7];
```

**Comment by peterweb2005** [comment]
not collection, just object change

now has this separated file (eg: hook.dart) for the notify change purpose

```
import 'package:flutter/material.dart';

@immutable
class ItemState {
  final dynamic item;

  const ItemState({this.item});
}

class ItemUpdateAction {
  final dynamic item;

  const ItemUpdateAction({this.item});
}

ItemState reducer(ItemState state, ItemUpdateAction action) =>
    ItemState(item: action.item);
```

when notify
```
        store.dispatch(ItemUpdateAction(item: item));
```

**Comment by rrousselGit** [comment]
Closing as this was answered
