### ISSUE TITLE
[optimization] HookState could be made a LinkedListEntry so that no wrapper is needed.

### ISSUE THREAD

**Issue by modulovalue** [rrousselGit/flutter_hooks#231]
Hello Remi,

This issue is about the following wrapper:

https://github.com/rrousselGit/flutter_hooks/blob/6d590cd3204f0978b3d9cdc23435a5e279c73f55/packages/flutter_hooks/lib/src/framework.dart#L304-L307

its sole purpose is to contain HookState objects.

HookState itself could be made a LinkedListEntry. This would reduce the memory overhead of flutter hooks. (Not that it's big as it is, it's just that it would improve a little bit)

This isn't urgent and the memory improvements wouldn't be groundbreaking, but if you find the time, or if you'll be doing some work on flutter hooks, It would be great if you could consider this suggestion.

**Comment by rrousselGit** [comment]
That would lead to HookState, a public API, now implementing
LinkedListEntry, which is an implementation detail.

This is undesired as I could refactor hooks to not even use a linked list,
and that should have no impact.
But with such change, that would be a breaking change

**Comment by modulovalue** [comment]
Oh wait your right, it's _that_ HookState. I mistook it for some some internal HookState.
I asked too hastily, should've checked twice, sorry for that!
