### ISSUE TITLE
Add an example on how to implement a useInterval or useTimer

### ISSUE THREAD

**Issue by ebraminio** [rrousselGit/flutter_hooks#233]
**Describe what scenario you think is uncovered by the existing examples/articles**
This is one common, basic and educational need from hooks, the first example on https://github.com/ra1028/SwiftUI-Hooks/blob/9b1b3ff26327ed178ab7a0efcd94a205c18efee9/README.md#introducing-hooks and a lengthy post by Dan Abramov, https://overreacted.io/making-setinterval-declarative-with-react-hooks/ but

**Describe why existing examples/articles do not cover this case**
At least I couldn't find one using delay, interval and periodic keywords or in StackOverflow

**Additional context**
Based on Dan Abramov post, I've reached to something like this,
```dart
// UPDATE: DON'T USE THIS EXAMPLE, use the one on the below comment by @davidmartos96 or others
void useInterval(Function() callback, Duration delay) {
  final savedCallback = useState(callback);
  useEffect(() {
    savedCallback.value = callback;
  });
  useEffect(() {
    return Timer.periodic(delay, (_) => savedCallback.value()).cancel;
  }, [delay]);
}
```
It looks correct but I fear about that save mechanism not being efficient enough or maybe not, or maybe there are better mechanism given flutter hooks features, guess it could be a bit time saving if something like this was provided as an example like the mentioned links.

Thanks!

**Comment by davidmartos96** [comment]
@ebraminio I'd say there is a better way to save the callback. You are using `setState`, and Dan has used `useRef`, which is not available with that name in `flutter_hooks`. You can use `useValueNotifier` instead, which is a way to hold a value and change it anytime without causing a rebuild.
Also, the first useEffect you created will run on everytime the build gets called. You missed the dependency list.
Haven't tested it but it would end up as something as this:

```dart
void useInterval(VoidCallback callback, Duration delay) {
  final savedCallback = useValueNotifier(callback);
  
  useEffect(() {
    savedCallback.value = callback;
  }, [callback]);

  useEffect(() {
    final timer = Timer.periodic(delay, (_) => savedCallback.value());
    return timer.cancel;
  }, [delay]);
}
```

**Comment by ebraminio** [comment]
Great! I was worried about that part also and this is was what exactly I was looking for, so could be nice if that is added in some documentation I think also. Thanks!

**Comment by rrousselGit** [comment]
@davidmartos96 's code is correct.

Although I've added `useRef`, so you could do:

```dart
void useInterval(VoidCallback callback, Duration delay) {
  final savedCallback = useRef(callback);  
  savedCallback.value = callback;

  useEffect(() {
    final timer = Timer.periodic(delay, (_) => savedCallback.value());
    return timer.cancel;
  }, [delay]);
}
```
