### ISSUE TITLE
No any notes about preserving HookWidget state when changing the parent

### ISSUE THREAD

**Issue by nailgilaziev** [rrousselGit/flutter_hooks#235]
**Describe what scenario you think is uncovered by the existing examples/articles**
There is no clear and concise description of how to preserve the state when widget change the parent.
If this is not possible with **flutter_hooks**, then there should be a notice in the documentation about it.

**Describe why existing examples/articles do not cover this case**
`GlobalKeys` when used with `StatefullWidget` allow widgets to change parents anywhere in app without losing state. 
But `HookWidget extends StatelessWidget` and using `GlobalKey` with it is not possible and doesn't make sense.

**Additional context**
Parent change may be needed if implementing for example master detail UI pattern . 

- portrait mode - master detail pages show individually by pushing detail page to Navigator over master page.
- landscape mode - master and details pages are displayed side by side in 2 column fashion.

When rotating device new UI builds and moving HookWidget with state from one parent to another parent is required.

**Comment by davidmartos96** [comment]
You could do an `useMemoized`.

```dart
final GlobalKey key = GlobalKey();
```
would be equivalent to

```dart
final key = useMemoized(() => GlobalKey());
```

**Comment by nailgilaziev** [comment]
@davidmartos96 I understand how you can get and memorize the key. How you will use it next? )
If just using it as key parameter to HookWidget after changing parent I get `Duplicate GlobalKey detected in widget tree`

**Comment by davidmartos96** [comment]
@nailgilaziev Could you share a simple example? I'm not following exactly

**Comment by nailgilaziev** [comment]
I created a simple example for sharing with you and just realize that I was wrong :)  GlobalKeys used with HookWidged in exactly the same way as with regular StatefulWidget. [simple project](https://github.com/nailgilaziev/test_parent_changing_hw)

But in bigger project (where I apparently got confused in abstractions lol) I meet `Duplicate GlobalKey detected in widget tree` error.
This is apparently connected with something else, but I still cannot understand why. 

<details>
  <summary>I get this error</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Form(state: FormState#2c45d):
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 135 pos 12: '_route == ModalRoute.of(context)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Form file:///Users/ng/cross/testscheck/vmngr/lib/ui/pages/details/account.dart:173:14
When the exception was thrown, this was the stack: 
#2      _WillPopScopeState.didUpdateWidget (package:flutter/src/widgets/will_pop_scope.dart:135:12)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4682:57)
#4      Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
...
====================================================================================================
flutter: 11:28:48.56 vrb/       AppRouterDelegate  .currentConfiguration() = /accounts/2.edit
flutter: 11:28:48.56 vrb/          AppRouteParser  .restoreRouteInformation(/accounts/2.edit)

======== Exception caught by widgets library =======================================================
Duplicate GlobalKey detected in widget tree.
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/rendering/object.dart': Failed assertion: line 2388 pos 12: 'attached': is not true.
====================================================================================================

======== Exception caught by scheduler library =====================================================
'package:flutter/src/rendering/object.dart': Failed assertion: line 2388 pos 12: 'attached': is not true.
====================================================================================================
```

</details>

So issue can be closed. thanks and sorry for interruption. I need to investigate more my case.

**Comment by nailgilaziev** [comment]
I will create another simplified example for understanding core problem. 
Hint: without Navigator 2.0 works normally, but with it...

**Comment by nailgilaziev** [comment]
I cut off most of the project, deleted all sensitive data and just left the main structure to show the problem
This [example repo](https://github.com/nailgilaziev/test_navigator_hookwidget_global_key) demonstrate the `Duplicate GlobalKey detected in widget` problem when using with navigator 2.0

core problem located in `lib/routing/router_delegate.dart` **AppRouterDelegate**

build method
```
return Scaffold(
      drawer: app.layoutMode != LayoutMode.medium ? null : LeftDrawer(),
      body: Stack(
        children: [
          Navigator(
            key: navigatorKey,
            onPopPage: _handleNavigatorPop,
            pages: [
              if (showSplash)
                SplashPage()
              else
                // Model pages
                ...getPages(context)                        <--------------------page build delegation
            ].map(_wrapContentInPage).toList(),
          )
        ],
      ),
    );
```
using `GlobalKey itemPanelKey = GlobalKey();`

```/// delegate page creation to ModelHolder object
  List<Widget> getPages(BuildContext context) {
    l.v('.getPages(_)');
    final details = context.read(detailsModeProvider);
    final layoutMode = app.layoutMode;
    final showDetails =
        details.maybeWhen(nothing: () => false, orElse: () => true);
    final pages = <Widget>[
      AccountsPage(),
      if (showDetails)
        ...details.when(
          nothing: () => [const NoSelectionPage()],
          unparsable: () => [const NotFoundPage()],
          item: (int? id, bool editing) => [
            if (id != null)
              ProviderScope(
                  overrides: [idScopedProvider.overrideWithValue(id)],
                  child: AccountBrowsing()),
            if (editing)
              ProviderScope(
                  overrides: [idScopedProvider.overrideWithValue(id)],
                  child: AccountEditing(key: itemPanelKey))     <-------------Here global key used
          ],
        ),
    ];
    if (app.layoutMode == LayoutMode.narrow) {
      /// use navigator pages
      return pages;
    } else {
      /// use master detail panels
      return [
        Row(
          children: [
            Expanded(
              flex: 1,
              child: pages[0],
            ),
            if (pages.length > 1)
              Expanded(
                flex: 1,
                /// last is browse or editing. simultaneously in multi panel mode their not shown
                child: pages.last,
              ),
          ],
        )
      ];
    }
  }
```

**Comment by nailgilaziev** [comment]
Select item and open editing page where _TextEditingFields_ located
then you can:

You can run on web and just shrinking the page to a minimum
or run on you device and rotate the screen to catch the error

**Comment by nailgilaziev** [comment]
I created a much simpler [example](https://github.com/nailgilaziev/test_nav2_master_detail_hw) 
Navigator 2.0 and master detail implementation to support state preservation when HookWidget changes his parent.
```
List<Widget> getPages() {
    final id = context.read(selectedStateProvider).state;
    final showDetails = id != null;
    final pages = [
      MasterList(),
      if (showDetails) DetailEditorHW(key: itemPanelKey),      <--------global key here
    ];
    if (!twoPanelMode) return pages;
    return [
      Row(
        children: [
          Expanded(child: pages[0]),
          Expanded(
              child: pages.length > 1 ? pages[1] : const NoSelectionPage()),     <-----it moves here. pages[1]
        ],
      )
    ];
  }
```
I did not understand the core problem yet. but 
as I understand it for now, the problem is that this approach with global key is not friendly with mechanisms of Navigator routing. 
Error that pappens now sligtly different 
```Multiple widgets used the same GlobalKey.```

**Comment by nailgilaziev** [comment]
https://user-images.githubusercontent.com/2749021/114285613-34024000-9a61-11eb-99be-5f96e8e9266c.mov

**Comment by rrousselGit** [comment]
flutter_hooks does not change the behavior of GlobalKeys.  
If you are losing your state when using GlobalKeys with flutter_hooks, you'd also lose your state if you used a StatefulWidget.

In any case, I wouldn't recommend relying on GlobalKey. Consider instead moving the state in a common ancestor and pass it down with InheritedWidgets.
Relocating widgets with GlobalKeys is quite inefficient.

**Comment by nailgilaziev** [comment]
I also came to this conclusion yesterday. Thank you!
