### ISSUE TITLE
Disposing listeners on tabController

### ISSUE THREAD

**Issue by AAverin** [rrousselGit/flutter_hooks#237]
What would be a good way to dispose a listener attached to tabController?

```
class W extends HookWidget {

  @override
  Widget build() { 
     _tabChanged() async {
     }
     
     final tabController = useTabController();
     tabController.addListener(_tabChanged);
  }

}
```

tabController doesn't expose a way to dispose and will only dispose internally.

**Comment by davidmartos96** [comment]
@AAverin Take a look at the useEffect hook. You shouldn't add a listener in the build method like that because it will be a memory leak

```dart
final tabController = useTabController();
useEffect(() {
    _tabChanged() async {
    };
    tabController.addListener(_tabChanged);
    return () => tabController.removeListener(_tabChanged);
}, [tabController]);
```

**Comment by AAverin** [comment]
@davidmartos96 
I see, thanks.
It took me quite some time to get into React hooks, but Flutter hooks I still can't fully grasp =)

**Comment by scopendo** [comment]
@AAverin – the listener is just a callback function – are you sure that you need to explicitly remove it?

**Comment by AAverin** [comment]
@scopendo there is no such thing as `just callback function`. Everything depends on what you do inside and which context use and hold on to.
