### ISSUE TITLE
useReducer without initialAction

### ISSUE THREAD

**Issue by PiN73** [rrousselGit/flutter_hooks#240]
How can `useReducer` hook be used without `initialAction`, i.e. if I want its first state to be simply `initialState`?

**Comment by rrousselGit** [comment]
You can make the action nullable, pass `null`, and have the reducer handle null actions:

```dart
useReducer<State, Action?>((state, action) {
  if (action == null) return state;
  ...
});
```

**Comment by PiN73** [comment]
I think it makes the code less expressive and types become less speaking. Also afaik it's uncommon to require initial action in flux/redux approach. Is it any technical reasons why initialAction need to be required?

**Comment by rrousselGit** [comment]
This avoid unnecessary null-checks if `Action` is non-nullable and an initialAction is provided.

**Comment by mazino-dev** [comment]
I think there is a trade off here. You can do the the null checks inside library or users of the library will have to do it everwhere in their reducer functions.
