### ISSUE TITLE
useRef proposal

### ISSUE THREAD

**Issue by TanaseHagi** [rrousselGit/flutter_hooks#242]
**Is your feature request related to a problem? Please describe.**
The current implementation of useRef hook is not useful to me as it is implemented now.

**Describe the solution you'd like**
I suggest this implementation that is more closer to what I'm using right now with react hooks.
```dart
import 'package:flutter_hooks/flutter_hooks.dart';

class ObjectRef<T> {
  ObjectRef(this.value);

  T value;
}

ObjectRef<T> useRef<T>(T initialValue) {
  return useMemoized(() => ObjectRef<T>(initialValue));
}

```

Any pros and cons?

**Comment by rrousselGit** [comment]
Sounds good. I'm open to pull-requests :)

**Comment by TanaseHagi** [comment]
Great!

https://github.com/rrousselGit/flutter_hooks/pull/244
