### ISSUE TITLE
useTextEditingController(text: "foo") initializes without the text

### ISSUE THREAD

**Issue by gysipos** [rrousselGit/flutter_hooks#245]
**Describe the bug**
Hi!
I use hooks_riverpod, and when creating a `TextEditingController` with `useTextEditingController`, it seems like the `text:` optional argument does not have any effect, it always gives back a TextEditingController with an initial value of ""

**To Reproduce**

inside the build method of a HookWidget:
`
String? foo = "foo";
final fooController = useTextEditingController(text: foo);
print(fooController.text);
`
prints ""

**Expected behavior**
I would expect it to print `"foo"`

**Comment by Agondev** [comment]
Just pasted your snippet into a demo barebone project I have open and it's working as expected, so can't reproduce.

![image](https://user-images.githubusercontent.com/2067558/130330233-77b5966a-1e5c-4b17-a0cf-3a1677e6d80a.png)

**Comment by gysipos** [comment]
Hy!

Thank you for checking this out! I did some messing around, cleaned up a bit, and it looks like some of my poorly written code around the build method was at the root of the issue. Thank you again for your help!
