### ISSUE TITLE
Provide a child parameter in HookBuilder

### ISSUE THREAD

**Issue by fabiancrx** [rrousselGit/flutter_hooks#252]
Currently the implementation of `HookBuilder` just provides a key and the builder callback
```dart
  const HookBuilder({
    required this.builder,
    Key? key,
  }) : super(key: key);
```

But is a common optimization in flutter to pass a child widget to avoid its rebuild in the builder callback itself. Does this pattern makes sense to HookBuilder too?

```dart
  const HookBuilder({
    required this.builder,
    this.child,
    Key? key,
  }) : super(key: key);
```

**Comment by rrousselGit** [comment]
Closing as I don't plan on implementing this, since it'd be a breaking change with little value
