### ISSUE TITLE
Multiple rebuild widget

### ISSUE THREAD

**Issue by pishguy** [rrousselGit/flutter_hooks#255]
in my application i have `SplashScreen` and `BackerStatus` screens, after navigate from `SplashScreen` to `BackerStatus`, navigated screen rebuild twice

`SplashScreen` class:

```dart
class SplashScreen extends HookWidget{
  @override
  Widget build(BuildContext context) {
    _routeNavigation();

    return Scaffold(
      body: Container(),
    );
  }

  void _routeNavigation() async{
    Routes.seafarer.navigate('/backer_status');
  }
}
```

`BackerStatus` screen:

```dart
class BackerStatus extends HookWidget {
  @override
  Widget build(BuildContext context) {

    print('REBUILD');

    return Scaffold(
      body: Container(),
    );
  }
}
``` 

log:

```
I/flutter ( 7447): REBUILD
I/flutter ( 7447): REBUILD
```

**Comment by rrousselGit** [comment]
This is not specific to flutter_hooks and would happen anyway.

**Comment by Agondev** [comment]
I think I can drop [this](https://stackoverflow.com/questions/64834702/why-build-function-gets-called-twice-when-hot-restarting) SO link and [this](https://api.flutter.dev/flutter/widgets/State-class.html) doc explanation here and this issue can be closed.
