### ISSUE TITLE
Widget not rebuilding while useState is used with List<bool>

### ISSUE THREAD

**Issue by jnknewaj** [rrousselGit/flutter_hooks#256]
In my `HookWidget`, my state variable is a `List<bool>`. I want to rebuild the widget when any item of the list changed. But the widget is not rebuilding.

**To Reproduce**

```
class _TempWidget extends HookWidget {
  const _TempWidget();
  @override
  Widget build(BuildContext context) {
    final myValue = useState([true, true]);

    return Column(
      children: [
        Text('1. --> ${myValue.value[0]}'),
        Text('2. --> ${myValue.value[1]}'),
        TextButton(
          onPressed: () {
            myValue.value[0] = !myValue.value[0];
            myValue.value[1] = !myValue.value[1];
          },
          child: const Text('Press This'),
        ),
      ],
    );
  }
}
```

**Expected behavior**
When `TextButton` is pressed, the `Text` widgets should show the updated value.

**Comment by davidmartos96** [comment]
List is a mutable object and mutating will not trigger a rebuild.
You need to recreate the list to do that

final current = myValue.value;
myValue.value = [ !current[0], !current[1] ];

**Comment by jnknewaj** [comment]
Got It.
