### ISSUE TITLE
UseEffect doesn't fire after render

### ISSUE THREAD

**Issue by sasarivera** [rrousselGit/flutter_hooks#257]
I'm trying to convert this code to hooks:

`@override
void initState(){
  super.initState();
  WidgetsBinding.instance.addPostFrameCallback((_){
     .... // code after first render
    );
  });
}`

when I convert this to hooks:

`useEffect(() {
        WidgetsBinding.instance!.addPostFrameCallback((_) => ...// code after render;
}, [VARIABLE_TRIGGERS_HOOK]);`

it runs "BEFORE" the render. I tried adding delays but still the same problem

**Comment by sasarivera** [comment]
sorry. I forgot to change the labels

**Comment by rrousselGit** [comment]
I am not quite following. You mean that the addPostFrameCallback executes before the render?

**Comment by sasarivera** [comment]
yes. that is what I mean. if I remove the useEffect, it runs after each render, but I need it to run after just the first render, that is why I added the useEffect. But the useEffect only executes before the render

**Comment by Agondev** [comment]
Dupe of #220

@sasarivera check my solution there

**Comment by rrousselGit** [comment]
What do you mean by "it runs before render" concretely?

**Comment by rrousselGit** [comment]
This issue seems to be stale, so I'll close it
