### ISSUE TITLE
useTextEditingController - listnere triggered twice

### ISSUE THREAD

**Issue by petrnymsa** [rrousselGit/flutter_hooks#261]
**Describe the bug**
Following usage of useTextEditingController trigger listener twice if the field is already in focus and tapped again. 

**To Reproduce**

```dart
Widget build(BuildContext context) {
    final controller = useTextEditingController();

    void onControllerChange() {
      print('OnControllerChange - ${controller.value.text}');
    }

    useEffect(() {
      controller.addListener(onControllerChange);

      return () => controller.removeListener(onControllerChange);
    }, [controller]);

    return TextFormField(
      controller: controller,
    );
  }
```

**Expected behavior**
Version with Full state widget works as expected - listener is triggered only for text change not for refocusing.

**Comment by Agondev** [comment]
Can't reproduce on my end.

Also you should move the func definition inside the useEffect, as it's otherwise called every single build, which, unless I'm mistaken, in worst case scenario could introduce a memory leak or at the very least make for redundant tick iteration.

```dart
Widget build(BuildContext context) {
    final controller = useTextEditingController();

    useEffect(() {
      void onControllerChange() {
        print('OnControllerChange - ${controller.value.text}');
      }

      controller.addListener(onControllerChange);

      return () => controller.removeListener(onControllerChange);
    }, [controller]);

    return TextFormField(
      controller: controller,
    );
  }
```

**Comment by petrnymsa** [comment]
> Can't reproduce on my end.
> 
> Also you should move the func definition inside the useEffect, as it's otherwise called every single build, which, unless I'm mistaken, in worst case scenario could introduce a memory leak or at the very least make for redundant tick iteration.
> 
> ```dart
> Widget build(BuildContext context) {
>     final controller = useTextEditingController();
> 
>     useEffect(() {
>       void onControllerChange() {
>         print('OnControllerChange - ${controller.value.text}');
>       }
> 
>       controller.addListener(onControllerChange);
> 
>       return () => controller.removeListener(onControllerChange);
>     }, [controller]);
> 
>     return TextFormField(
>       controller: controller,
>     );
>   }
> ```

Moving function inside useEffect does not help. 

1. tap on the field
2. write something (notice printed changes, that's OK)
3. Tap on the field again - listener fired
4. tap "Done" button on the keyboard - listener fired again


Tested on Android (emulator) and Real device. Android version 11. 

Flutter version 
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by Agondev** [comment]
Ah, since I was using desktop I couldn't reproduce but I tried on physical device and looks to be reproducible. Seems like what you actually want is to listen on the onChanged of the TextFormField rather than listening to the controller. Just a workaround though.

**Comment by rrousselGit** [comment]
flutter_hooks is unrelated to this behavior. It is only creating/disposing the controller. It never deals with the controller's listeners. If you want this behavior to change, you should likely raise an issue on the Flutter repo instead

**Comment by petrnymsa** [comment]
@rrousselGit 

> flutter_hooks is unrelated to this behavior. It is only creating/disposing the controller. It never deals with the controller's listeners. If you want this behavior to change, you should likely raise an issue on the Flutter repo instead

@rrousselGit  Is it really that case? Like I said, same example with "standard" StatefullWidget works as expected.

**Comment by rrousselGit** [comment]
Do you have an example for side-by-side comparison? Because as I mentioned, flutter_hooks is not doing anything with the controller besides disposing it. 

Without a clear example, I'd be tempted to think that what happened is, you tested stateful widget vs hooks in different conditions – fixing the issue implicitly.

**Comment by petrnymsa** [comment]
> Do you have an example for side-by-side comparison? Because as I mentioned, flutter_hooks is not doing anything with the controller besides disposing it.
> 
> Without a clear example, I'd be tempted to think that what happened is, you tested stateful widget vs hooks in different conditions – fixing the issue implicitly.

I've re-tested and you are right. The behavior is the same - 
-tap on the field
-write something (notice printed changes, that's OK)
-Tap on the field again - listener fired
-tap "Done" button on the keyboard - listener fired again

So sorry about confusion and thank you.

**Comment by rrousselGit** [comment]
No problem!
