### ISSUE TITLE
`HookWidget with more/less hooks than previously` seems to be not allowed

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/flutter_hooks#262]
**Describe what scenario you think is uncovered by the existing examples/articles**

> It is now allowed to rebuild a HookWidget with more/less hooks than previously. Example:
https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/CHANGELOG.md#0110

It seems that this isn't allowed in fact as mentioned here: https://github.com/rrousselGit/river_pod/discussions/711

**Describe why existing examples/articles do not cover this case**

**Additional context**

The note deleted at https://github.com/rrousselGit/flutter_hooks/commit/ecbffc75c6280e9ec1992f5b9360c9b89b018869#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5, should be re-added.

**Comment by rrousselGit** [comment]
Actually this doc update was correct. 

On the other hand it still isn't allowed to use hooks within loops.
