### ISSUE TITLE
useEffect not called when keys are changed

### ISSUE THREAD

**Issue by TudorIoanMarin** [rrousselGit/flutter_hooks#267]
Hi there,

I'm trying out the flutter hooks with a small example, and can't seem to make it to work.
```
    bool shouldRefresh = false;

    useEffect(() {
      print('Effect is called');
    }, [shouldRefresh]);
    ...
    floatingActionButton: FloatingActionButton(
      onPressed: () {
        shouldRefresh = !shouldRefresh;
      },
    ),
```
The use effect is called only when the widget is rendered and not on button press.
Any idea what I am doing wrong? I can't seem to find a simple example with keys anywhere.

**Comment by AAverin** [comment]
@rrousselGit What if one of the keys is not in the state and is rather a value notifier? I would like my `useCallback` to rebuild any time value in the ValueNotifier changes, but I can't put that ValueNotifier into the state – it's a controller of a heavy map object and if I put into the state this results in heavy map rebuilds.
