### ISSUE TITLE
in hooks_riverpod: ^1.0.0 I face this problem The method 'useStreamController' isn't defined for the type

### ISSUE THREAD

**Issue by Abouassi98** [rrousselGit/flutter_hooks#272]
![image](https://user-images.githubusercontent.com/53384802/143285353-4da558df-3382-4bee-86bc-c7e83b205c97.png)

**Comment by rrousselGit** [comment]
Make sure to run `dart pub upgrade` and to import `flutter_hooks`. Considering your example uses `HookConsumerWidget` it's likely that you forgot to import `flutter_hooks`
