### ISSUE TITLE
Why useListenable doesn't accept null?

### ISSUE THREAD

**Issue by jeiea** [rrousselGit/flutter_hooks#275]
**Is your feature request related to a problem? Please describe.**
```useListenable(this.propValue);```

When that `propValue` is `ValueNotifier<T>?`, I have trouble with using it with `useListenable` because `useListenable` doesn't allow nullable parameter. So I have a question about why it is not permitted.

**Describe the solution you'd like**
Allow null in `useListenable`.

**Describe alternatives you've considered**
There are some detours with the current signature.
-  Use`useValueNotifier()` for a placeholder listenable.
-  Separate as another hook widget and use that only if the listenable is not null.

But I think the above require tedious work in using that.

**Comment by rrousselGit** [comment]
No particular reason. Feel free to make a PR if you need it
