### ISSUE TITLE
Performance differences?

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/flutter_hooks#286]
Hi thanks for the wonderful lib! I wonder whether how much performance penalty does it have? IMHO it looks like a wrapper around original stateful widgets. In addition, it store objects in arrays instead of storing in fields, so the compiler may not be able to optimize that much.

**Comment by fzyzcjy** [comment]
More information: I see some people saying React hooks result in some performance penalty. But I am not sure whether Flutter has the same problem - since Dart is AOT language while javascript is not.

**Comment by rrousselGit** [comment]
I don't like the word "performance issue", since I doubt that most people would ever notice the difference.

There is definitely a performance difference with doing things in a more manual way. Although the real question is whether that penalty has any visible impact or not.  
The performance cost should be fairly minor/invisible. But I can't deny that it's there.


I do hope that at some point, metaprogramming will allow implementing hooks in a way that has no impact though. But the current metaprogramming proposal does not allow that sadly. Maybe in the future

**Comment by fzyzcjy** [comment]
> I don't like the word "performance issue", since I doubt that most people would ever notice the difference.

Title edited ;)

> There is definitely a performance difference with doing things in a more manual way. Although the real question is whether that penalty has any visible impact or not.
The performance cost should be fairly minor/invisible. But I can't deny that it's there.

Well I am a bit worried: `build` is called at 60FPS while initState/dispose is very sparse. We are adding a lot of logic to `build`... 

> I do hope that at some point, metaprogramming will allow implementing hooks in a way that has no impact though. But the current metaprogramming proposal does not allow that sadly. Maybe in the future

Sounds interesting! Also looking forward to the metaprogramming

**Comment by ayushin** [comment]
i'm wondering if this could be implemented via templates and build runner instead at the compile time

**Comment by rrousselGit** [comment]
> Well I am a bit worried: `build` is called at 60FPS while initState/dispose is very sparse. We are adding a lot of logic to `build`...


`build` isn't the slow part of updating your UI. It's the layout/painting phase.
`build` is also typically not called 60times a second. It's objectively fairly rare. Most of your widget tree never changes

So it's really unlikely to cause performance issues.

It's also important to note that hooks make it easier to implement some performance optimizations, such as `useMemoized`. For example, it can be used to cache widgets, reducing how often their `build` method is called – kind of like `const` but with dynamic parameters.

So hooks may as well _improve_ performances

**Comment by fzyzcjy** [comment]
Sounds reasonable. Thanks!
