### ISSUE TITLE
Add rebuild method call to trigger build on HookWidget.

### ISSUE THREAD

**Issue by safield** [rrousselGit/flutter_hooks#287]
I have the usecase where I want a button to enable when a text field is not empty. To do this with flutter hooks, I have to create a superfluous state, using useState. When following the single source of truth principle, the only state I need to refer to is the textEditController.text.isNotEmpty to achieve the behaviour.

Observe the current implementation...

```
  Widget build(BuildContext context) {
    var ctrl = useTextEditingController();
    var superfluousCode = useState(0);
    ctrl.addListener(()=> superfluousCode.value++);
    VoidCallback? onPressed;
    if (ctrl.text.isNotEmpty) {
      onPressed = () => print("Pressed!");
    }
    return Scaffold(
      body: Column(
        children: [
          TextField(
            controller: ctrl,
          ),
          ElevatedButton(onPressed: onPressed, child: Text("Button")),
        ],
      )
    );
  }

```

In this example I need to create 'state' that is not needed, and would infact be code smell if I actually referred to the state instead of the actual source of truth which is 'ctrl.text.isNotEmpty'.

Ideally a HookWidget could just expose a method rebuild() to solve this issue.

**Comment by ronnieeeeee** [comment]
Hi @safield ,
I don't know if this is the code you are expecting, but I wrote this code to enable the button widget when the text field is not empty. How do you like it?

```dart
class Example extends HookWidget {
  const Example({Key? key}) : super(key: key);


  @override
  Widget build(BuildContext context) {
    var ctrl = useTextEditingController();
    final textIsNotEmpty = useIsNotEmptyTextField(ctrl);
    return Scaffold(
        body: Column(
      children: [
        TextField(
          controller: ctrl,
        ),
        ElevatedButton(
            onPressed: textIsNotEmpty ? () => print("Pressed!") : null,
            child: Text("Button")),
      ],
    ));
  }
}


bool useIsNotEmptyTextField(TextEditingController textEditingController) {
  final hasNotEmpty = useState(textEditingController.text.isNotEmpty);


  useEffect(() {
    void l() {
      hasNotEmpty.value = textEditingController.text.isNotEmpty;
    }


    textEditingController.addListener(l);
    return () => textEditingController.removeListener(l);
  }, [textEditingController]);


  return hasNotEmpty.value;
}
```

For more information, please try this repository in run "main.dart" .
https://github.com/ronnieeeeee/flutter_hooks287

**Comment by safield** [comment]
@ronnieeeeee That seems EXCEPTIONALLY verbose to me. So much so that Stateful widget would just be a better solution...

**Comment by davidmartos96** [comment]
> @ronnieeeeee That seems EXCEPTIONALLY verbose to me. So much so that Stateful widget would just be a better solution...

Just so you know, you could simply do

useListenable(textController);

It will automatically rebuild whenever the text changes (that includes the value of isNotEmpty)

Also, note that you shouldn't do addListener in the build method

**Comment by ronnieeeeee** [comment]
Oops, forgot about that one!
Thank you david.

```dart
class Example extends HookWidget {
  const Example({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var ctrl = useTextEditingController();
    useListenable(ctrl);
    return Scaffold(
        body: Column(
      children: [
        TextField(
          controller: ctrl,
        ),
        ElevatedButton(
            onPressed: ctrl.text.isNotEmpty ? () => print("Pressed!") : null,
            child: Text("Button")),
      ],
    ));
  }
}
```

**Comment by rrousselGit** [comment]
useListenable is correct

The proposed useIsTextNotEmpty would be slightly better, since it wouldn't rebuild the widget unless that state has changed

Although chances are there's a way to make a more generic variant of this hook like:

```
final isEmpty = useListenableMap(controller, () => controller.text.isEmpty)
```

**Comment by rrousselGit** [comment]
In any case this was answered so I'm closing this.

The code smell here was desired, since the original code shown has a bug. Adding listeners inside the build method like that is going to cause problems

**Comment by ronnieeeeee** [comment]
> ```
> final isEmpty = useListenableMap(controller, () => controller.text.isEmpty)
> ```

Oh, Remi's suggestion of useListenableMap is interesting! It is beneficial😄

**Comment by rrousselGit** [comment]
On that note, if someone wants to have a go at implementing this useListenableMap, I'd be happy to see it merged in flutter_hooks 😊

It sounds useful overall.

**Comment by ronnieeeeee** [comment]
I would like to try to implement useListenableMap!
I'll post a pull request when I'm finished implementing, so please take a look when you have time.
