### ISSUE TITLE
Build rebuild multiple times

### ISSUE THREAD

**Issue by Kerimkullov** [rrousselGit/flutter_hooks#296]
**Describe the bug**
I found strange behavior of hook, if in hookWidget we use context and when we focus  textfield, build rebuild multiple times

**To Reproduce**

1) Create HookWidget, with TextField
2) Add print method in Build 
3) Use context
For example: 
final screenWidth = MediaQuery.of(context).size.width;
4) Tap on textField to focus on

It will rebuild build method multiple times

**Expected behavior**
It shouldn't rebuild build method

**Comment by ronnieeeeee** [comment]
Could you share a runnable full example?
I wrote the code for a similar situation and may be able to help you.

**Comment by rrousselGit** [comment]
Could you include an example to reproduce the issue?

**Comment by Kerimkullov** [comment]
import 'package:first_app/constants/news_colors.dart';
import 'package:first_app/model/user_model.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: FirstScreen(),
    );
  }
}

class FirstScreen extends HookWidget {
  const FirstScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final text = useTextEditingController();

    /// For example
    final width = MediaQuery.of(context).size.width;

    print('Build PRINT');
    return Scaffold(
      body: SizedBox(
        width: width,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: TextField(
                  controller: text,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

How to test? 
1) Run the project
2) Tap on textField
3) Open mobile keyboard and close
4) See debug console

**Comment by rrousselGit** [comment]
This is unrelated to flutter_hooks. This has to do with `MediaQuery.of`

Using `MediaQuery.of` listens to multiple things, including the screen height. And the screen height changes when the keyboard opens. As such, the widget rebuilding is logical and not caused by flutter_hooks.
