### ISSUE TITLE
[Feature Request] useLayoutEffect hook

### ISSUE THREAD

**Issue by mazino-dev** [rrousselGit/flutter_hooks#299]
**Is your feature request related to a problem? Please describe.**
I wish to replicate the functionality of useLayoutEffect hook found in React ecosystem where the widget rebuild is delayed.

**Describe the solution you'd like**
Would like following hook to be added.
[https://reactjs.org/docs/hooks-reference.html#uselayouteffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)

**Describe alternatives you've considered**
I looked at existing hooks in the api docs, I dont think any provides this functionality.

**Additional context**
[https://kentcdodds.com/blog/useeffect-vs-uselayouteffect](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect)

**Comment by rrousselGit** [comment]
flutter_hook's use_effect is a useLayoutEffect

**Comment by mazino-dev** [comment]
Oh.. thanks.
