### ISSUE TITLE
useAnimationController

### ISSUE THREAD

**Issue by Solido** [rrousselGit/flutter_hooks#3]
The code example useAnimationController is not available currently.
Can you provide and example that demonstrate Hook and HookState ?
Thx !

**Comment by rrousselGit** [comment]
This api in currently in merge request and will be available by tomorrow actually

**Comment by rrousselGit** [comment]
But there's an example that _don't_ use them in the example folder

**Comment by Solido** [comment]
Already read all the implementation my point is just we need more documentation on real case to help adoption. Most users will just copy / paste or look for easy examples.

**Comment by rrousselGit** [comment]
Let's talk on slack! :p
