### ISSUE TITLE
I added a new useModel API

### ISSUE THREAD

**Issue by fangkyi03** [rrousselGit/flutter_hooks#301]
Because I prefer the two-way binding mode of VUE, I changed it to the following effect
<img width="797" alt="image" src="https://user-images.githubusercontent.com/30390014/166155948-4ae4ea87-d3c4-45f6-b9c8-f9afc26d7bce.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/30390014/166155958-b6014718-7746-4776-a352-b5cea8584a5d.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/30390014/166156064-4cf441ea-977f-42a3-9c3b-19b0627924fc.png">

Later, we can write a simple script to automatically generate model templates so that we can not only use its syntax hints and type hints, but also more convenient maintenance without the need to write a bunch of refresh pages

**Comment by rrousselGit** [comment]
Hello!

Could you explain exactly what you want? I don't know what this is about

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/166245958-6703f857-62e3-4602-b2db-de800abceed8.png)

**Comment by rrousselGit** [comment]
You can probably use `ChangeNotifier`:

```dart
class MyModel with ChangeNotifier {
  int count = 0;
  void increment() {
    count++;
    notifyListeners();
  }
}

Model useModel<Model extends ChangeNotifier>(Model Function() cb) {
  final model = useMemoized(cb);
  useEffect(() => model.dispose, [model]);
  useListenable(model);
  return model;
}
```

**Comment by rrousselGit** [comment]
I'm open to discussion, but for now I don't plan on implementing this. As such I'll close this issue :)
