### ISSUE TITLE
Latest changes in Flutter pull cause listener related tests to fail

### ISSUE THREAD

**Issue by Jstuff36** [rrousselGit/flutter_hooks#322]
With the changes in this [flutter](https://github.com/flutter/flutter/pull/108931) commit, three hook tests related to calling hasListeners are failing: [use_focus_node](https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/test/use_focus_node_test.dart#L36), useState [here](https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/test/use_state_test.dart#L39) and [here](https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/test/use_state_test.dart#L73), and useValueNotifier [here](https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/test/use_value_notifier_test.dart#L70) and [here](https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/test/use_value_notifier_test.dart#L112).

Raising this bug to track. I can fix in a few weeks when I wrap up my current project and was planning on spending more time with this package.

**Comment by droidbg** [comment]
@rrousselGit if it is fixed, can you close this issue
