### ISSUE TITLE
HookWidget and didChangeMetrics

### ISSUE THREAD

**Issue by dodatw** [rrousselGit/flutter_hooks#329]
How can I listen didChangeMetrics in HookWidget ?
I saw it already support useAppLifecycleState for listen WidgetsBindingObserver.

**Comment by rrousselGit** [comment]
I'd suggest looking into the source of the observer binding: https://github.com/rrousselGit/flutter_hooks/blob/master/packages/flutter_hooks/lib/src/widgets_binding_observer.dart

You can fork it to do the same thing with any lifecycle of your choice
