### ISSUE TITLE
How to add a Parameter in HookWidget but don't trigger rebuild when value change

### ISSUE THREAD

**Issue by dodatw** [rrousselGit/flutter_hooks#334]
Flutter hooks is a very useful package for me when implementing flutter apps, I love it.

I have a question.
Sometimes I need a parameter in the HookWidget but I don't want to rebuild the widget when this value changes.

If I use `useState` it triggers a build.
The current workaround is that I use `useValueNotifier` to keep the value. It doesn't trigger `build` when value change as I expect.

Is there any best practice for this use case?

**Comment by rrousselGit** [comment]
You can use `useRef` for this
