### ISSUE TITLE
useErrorBoundary

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#35]

**Comment by Solido** [comment]
Just learned the concept yesterday. We really need more docs and examples on those features !

**Comment by rrousselGit** [comment]
Hum do you mind explain g what you're talking about?
What I'm doing here is not in Flutter yet from my experience

**Comment by Solido** [comment]
No it's not.

I've read the doc on React as you talked about it yesterday and I'll be glad to have some examples on how to use those concept in Flutter.

**Comment by rrousselGit** [comment]
I see!
Actually, I'm not certain that this is doable in its entirety. This works if an exception is thrown synchronously. But if a descendant does a `setState` _then_ throws, I'm not sure.

**Comment by rrousselGit** [comment]
The biggest blocker to this is that `FlutterErrorDetails` do not contain the origin `Element`. 
I'll have to make a PR to Flutter directly to add this information in a subclass. But it's obviously not ideal

**Comment by rrousselGit** [comment]
Won't do.
