### ISSUE TITLE
How to watch redux store change inside useEffect?

### ISSUE THREAD

**Issue by Lenny4** [rrousselGit/flutter_hooks#350]
I'm using [`flutter_hooks`][1] and [`flutter_redux`][2]

Here is my widget:

```dart
class Root extends HookWidget {
  const Root({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final store = StoreProvider.of<AppState>(context);

    useEffect(() {
      print('useEffect print: ${store.state.init}');
      if(store.state.init == false) {
        store.dispatch({'init': true});
      }
    }, [store.state.init]);

    return Container();
  }
}
```
Current ouput:
```
useEffect print: false
```

Expected ouput:
```
useEffect print: false
useEffect print: true
```
Why does `useEffect` hook is not trigger when I update the state of the store ?

In react i can do something like this:
```typescript
const MyComponent = React.memo(() => {
  const dispatch = useAppDispatch();
  const init = useAppSelector((state: RootState) => state.globalState.init);

  React.useEffect(() => {
    console.log("init state: " + init);
    if (init === false) {
      dispatch(set({ init: true }));
    }
  }, [init]);

  return <Box />;
});

export default MyComponent;
```
output:
```
init state: false
init state: true
```
### Notive that the `useEffect` function has been call twice in React and 1 time in flutter.

I have opened an issue on `flutter_redux` [here](https://github.com/brianegan/flutter_redux/issues/244), the maintainer told me to use another third party package to handle this case, but none I found on internet seems to work.

Do you plan to implement a feature which will allow to use `useEffect` to watch `store` changes ?

  [1]: https://pub.dev/packages/flutter_hooks
  [2]: https://pub.dev/packages/flutter_redux

**Comment by Lenny4** [comment]
Hi @rrousselGit, thank for your reply.

> It's unclear to me that this is handled correctly, so my assumption is that useEffect works but your reducer/store doesn't.

If I modify my dart code like this:
```diff
class Root extends HookWidget {
  const Root({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final store = StoreProvider.of<AppState>(context);

+   store.onChange.listen((AppState appState) {
+      print('store.onChange print: ${store.state.init}');
+   });

    useEffect(() {
      print('useEffect print: ${store.state.init}');
      store.dispatch({'init': true});
    }, [store.state.init]);

    return Container();
  }
}
```
I got this output:
```
useEffect print: false
store.onChange print: true
```
As you can see my store.onChange is trigger. So my reducer/store seems to work correctly.

Do you agree ?

**Comment by rrousselGit** [comment]
That's up to the redux package to do so here. For example `StoreProvider.of<AppState>(context)` could cause the dependent widget to listen to the app state.
