### ISSUE TITLE
Making the `keys` optional for the `useCallback` hook

### ISSUE THREAD

**Issue by jezsung** [rrousselGit/flutter_hooks#368]
Maybe I'm missing something, but why does the `keys` property on the `useCallback` have to be required? The `useMemonized` has its `keys` optional and it defaults to an empty list.

Below is the current implementation of the `useCallback` hook:
```dart
T useCallback<T extends Function>(
  T callback,
  List<Object?> keys,
) {
  return useMemoized(() => callback, keys);
}
```

I wonder if we could change the `keys` property optional and default to an empty list like the following:
```dart
T useCallback<T extends Function>(
  T callback, [
  List<Object?> keys = const <Object>[],
]) {
  return useMemoized(() => callback, keys);
}
```

**Comment by rrousselGit** [comment]
Sure. Fancy making a PR?

**Comment by jezsung** [comment]
@rrousselGit Sure, I'll make a PR asap
