### ISSUE TITLE
Callback listeners for the `useStream` hook

### ISSUE THREAD

**Issue by jezsung** [rrousselGit/flutter_hooks#370]
I'd like to listen to a `Stream` and call a callback but the current `useStream` hook doesn't seem to expose methods to register callbacks.

I want something like the below:
```dart
useStream(
  stream, 
  onData: (data) { ... },
)
```

Or is there another way to achieve the same thing?

**Comment by rrousselGit** [comment]
We probably want to offer a `useStreamListener` instead to be consistent with other hooks and not have the widget rebuild when the stream updates.

But otherwise, LGTM

Fancy making a PR?

**Comment by jezsung** [comment]
@rrousselGit Yeah a new PR arrived, please check it out :)

**Comment by mattermoran** [comment]
@rrousselGit I think this can be closed. the PR https://github.com/rrousselGit/flutter_hooks/pull/373 was merged but issue was not linked so this is still hanging here :)
