### ISSUE TITLE
Missing hook for `ExpansionTileController`

### ISSUE THREAD

**Issue by bartekpacia** [rrousselGit/flutter_hooks#375]
There's a [`ExpansionTileController`](https://api.flutter.dev/flutter/material/ExpansionTileController-class.html) class. I'd like to have a hook like `useExpansionTileController()` :)

**Comment by rrousselGit** [comment]
Feel free to make a PR if you wish :)

**Comment by droidbg** [comment]
@rrousselGit I like to pick this up.
