### ISSUE TITLE
show dialog/snackbar etc

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/flutter_hooks#38]
Hi, great lib, i love it :D!

I am wondering what is the best/recommended way to show a dialog/navigate in response to some state change.
`
int state = useStream(myStream);
if (state == 5) {
showDialog(context: context ....);
}
`

**Comment by smiLLe** [comment]
i could do 
`useEffect(() {  if (state == 5) { showDialog( context:context ); } }, [state] );`
is it valid to use context in useEffect?

**Comment by rrousselGit** [comment]
No this won't do. 
We need a `useAsyncEffect`, which calls the callback _after_ the build finished. 

A lazy implementation could be:

```dart
void useAsyncEffect(VoidCallback cb, [List<dynamic> keys]) {
  useEffect(() => Future.microtask(cb), keys);
}
```

**Comment by smiLLe** [comment]
WidgetsBinding.instance.addPostFrameCallback(); won't work, i guess :)?

**Comment by rrousselGit** [comment]
It will. There's nothing wrong with it.

You can use `context` too.
