### ISSUE TITLE
`when` for `AsyncSnapshot`

### ISSUE THREAD

**Issue by dickermoshe** [rrousselGit/flutter_hooks#413]
**Is your feature request related to a problem? Please describe.**
Dealing with all the possible states of `AsyncSnapshot` are very tiresome.

When using a `Future`, you need to _only_ need to handle three cases.

```dart
if (snapshot.hasError){
  // 1. Error
} else if (snapshot.hasData){
  // 2. Data
} else {
  // 3. Loading
}
```

It gets much more confusing once you are working with a stream.
You then have to start dealing with `ConnectionState`, with **7** possible states.
This results in a pretty ugly result:
```dart
switch (snapshot.connectionState) {
  case ConnectionState.none:
  // 1. Handle null future
  case ConnectionState.waiting:
  // 2. Handle waiting for data
  case ConnectionState.active:
  // Handle data, but more data might come in
    if (snapshot.hasError) {
  // 4. Handle error
    } else {
  // 5. Handle data
    }
  case ConnectionState.done:
  // Handle completed data
    if (snapshot.hasError) {
  // 6. Handle error
    } else {
  // 7. Handle data
    }
}
```

**Describe the solution you'd like**
The way that `riverpod` deals with this is really nice.
The `when` [extension ](https://pub.dev/documentation/hooks_riverpod/latest/hooks_riverpod/AsyncValueX/when.html)on `AsyncValue` is amazing. Having it here would be fantastic.

```
snapshot.when(
  data: (data,isCompleted) => buildData(data,completed),
  error: (error, stack) => buildError(error, stack),
  loading: () => buildLoading(),
);
```
The only change I would advise is adding a `isCompleted` to the `data` handler, which will be true if `ConnectionState.done`

**Describe alternatives you've considered**
I've built some of this myself, but I think this would be a great addition to the package, makes `useFuture` so easy.

**Additional context**

**Comment by rrousselGit** [comment]
Flutter_hooks isn't responsible for AsyncSnapshot. 
I'd suggest either requesting that on the Flutter repo, or maybe such an extension in your own project.

Considering Dart 3 now has pattern matching, I have no plan on adding such a feature.
