### ISSUE TITLE
a hook for the DraggableScrollableController

### ISSUE THREAD

**Issue by dickermoshe** [rrousselGit/flutter_hooks#416]
**Is your feature request related to a problem? Please describe.**
There is no hook for the DraggableScrollableController

**Describe the solution you'd like**
a hook for the DraggableScrollableController

**Describe alternatives you've considered**
Should be included as it is a Built in Material Widget

**Additional context**
None

**Comment by rrousselGit** [comment]
Sure. Feel free to make a PR :)

**Comment by dickermoshe** [comment]
https://github.com/rrousselGit/flutter_hooks/pull/417

**Comment by timcreatedit** [comment]
@rrousselGit @dickermoshe This is fixed and could be closed right?
