### ISSUE TITLE
onAttach and onDetach is missing on usePageController

### ISSUE THREAD

**Issue by Kinwailo** [rrousselGit/flutter_hooks#420]
[Official](https://api.flutter.dev/flutter/widgets/PageController-class.html) constructor:
`PageController({int initialPage = 0, bool keepPage = true, double viewportFraction = 1.0, ScrollControllerCallback? onAttach, ScrollControllerCallback? onDetach})`

Hook usePageController:
`PageController usePageController( {int initialPage = 0, bool keepPage = true, double viewportFraction = 1.0, List<Object?>? keys} )`

**Comment by Spotchi** [comment]
+1 here

**Comment by rrousselGit** [comment]
Fancy making a PR?
