### ISSUE TITLE
[Feature Request] Is it possible to implement `useSWR` in flutter_hooks

### ISSUE THREAD

**Issue by Cierra-Runis** [rrousselGit/flutter_hooks#425]
There's a useful and powerful hook at `React`, it names `useSWR`, link [here](https://swr.vercel.app/).

**Comment by rrousselGit** [comment]
This isn't an official React hook, but a third-party one.   
As such I'd prefer not having it in flutter_hooks. You can make a package for it if you wish :) 

In the end, `useSWR` is very close to what Riverpod tries to do.

**Comment by Cierra-Runis** [comment]
Thanks a lot, I will try to use riverpod to implement it ❤️.
