### ISSUE TITLE
implement useGlobalState

### ISSUE THREAD

**Issue by iambudi** [rrousselGit/flutter_hooks#57]
What is best practice to use global state without having intermediary sharedPreference?

**Comment by rrousselGit** [comment]
Hooks are not a state management library, at least not by default.

They allow some pretty powerful stuff in that matter, but `flutter_hooks` will hardly suggest one over another. You're free to use redux, bloc, mobx or whatever you like in combination with hooks. Or even bake your own

**Comment by iambudi** [comment]
I thought when i read the example code `final counter = useState<int>(5);` that can increment the value and update the UI it holds the local state.
Thanks for the clarification.

**Comment by rrousselGit** [comment]
That is the case. But this is equal to creating a `counter` property on  a `State`  subclass. It's not a global state

You _can_ make one though. In react, there are multiple user made hooks that do something similar. 
But it's completely outside of the scope of this library.

**Comment by ianldgs** [comment]
@rrousselGit any ideas on how to create such hook?
I'd imagine something related to context, but unlike react, we can't create a new context and use a provider to assign a custom value and dispatch in a three. Also inherited widget doesn't sound practical.

**Comment by rrousselGit** [comment]
See Riverpod, it's similar
