### ISSUE TITLE
more easy to use Context

### ISSUE THREAD

**Issue by shingohu** [rrousselGit/flutter_hooks#61]
I want to use context anywhere like State
I don't want to pass a context in the method,and I don't want to use HookBuilder to wrap the child widget。
how can i do 

```

class Demo extends HookWidget{
  @override
  Widget build(BuildContext context) {
    
    return button();
  }

  Widget button(){
    return FlatButton(onPressed: (){
      // here need context
      Navigator.of(context).pushNamed("xx");
    },);
  }

}
```

**Comment by rrousselGit** [comment]
```
Widget button() {
  final context = useContext();
 ... 
}
```

**Comment by shingohu** [comment]
@rrousselGit  what does the mean of `DO always call all the hooks` 
the useXXX can call in child widget?

**Comment by rrousselGit** [comment]
What don't you understand with the example in the Readme?

**Comment by shingohu** [comment]
@rrousselGit 
A little confused 
the Readme say :
`They can only be used in the build method of a HookWidget`
`DO always call all the hooks`

Make me think all the useXXX should call in build method

Is useXXX used correctly in the following demo
```
class Demo extends HookWidget{
  @override
  Widget build(BuildContext context) {
    
    return Column(
      children: <Widget>[
        child1(),
        child2(),
      ],
    );
  }

  Widget child1(){
    useXXX1();
    useXXX2();
    return Container();
  }

  Widget child2(){
    useXXX3();
    useXXX4();
    return Container();
  }

}
```

**Comment by rrousselGit** [comment]
It'll work, but that's bad practice. To begin with you should extract `child1/2` into independent class — not as a method.
