### ISSUE TITLE
TextField will be cleared when the soft keyboard disappears

### ISSUE THREAD

**Issue by shingohu** [rrousselGit/flutter_hooks#62]
1.input text
2.close the softkeyboard，the text will be cleared

Every time the build call,the _oldPWControll print as a new instance

```
class Demo extends HookWidget {
  final _oldPWControll = TextEditingController();

  final _oldPWFN = FocusNode();
  @override
  Widget build(BuildContext context) {
    print(_oldPWControll);
    return Scaffold(
      resizeToAvoidBottomInset: true,
      body: TextField(
        controller: _oldPWControll,
        textInputAction: TextInputAction.next,
        focusNode: _oldPWFN,
        decoration: InputDecoration(
          hintText: "请输入",
          contentPadding: EdgeInsets.fromLTRB(35.0, 12.0, 12.0, 12.0),
        ),
      ),
    );
  }
}
```

When Demo  as the home Widget of MaterialApp,it is work
but push to the Demo,problems will arise

**Comment by rrousselGit** [comment]
You should not create these as fields of the class.

Instead create them using hooks inside the build method

```dart
Widget build(BuildContext context) {
  final controller = useMemoized(() => TextEditingController());
  ... 
}

**Comment by shingohu** [comment]
you  mean I can't define any final variables directly from KookWidget?

**Comment by rrousselGit** [comment]
Nor can you do so with any other kind of widgets.

Widgets are immutable. You need a `State` subclass using hooks to preserve values between builds.
