### ISSUE TITLE
why is the implementation of useEffect different from React hooks useEffect?

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/flutter_hooks#63]
documentation for useEffect on [react hooks page](https://reactjs.org/docs/hooks-reference.html#useeffect)
> The function passed to useEffect will run after the render is committed to the screen.

Flutter hooks [synchronously](https://github.com/rrousselGit/flutter_hooks/blob/master/lib/src/hooks.dart#L684) executes the function which will lead in a different result as expected (coming from react hooks).

React also offers a hook called [uselayouteffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect) that is more similar to flutter hooks useEffect.

https://github.com/rrousselGit/flutter_hooks/issues/34 might be more similar to reacts useEffect.

Kind of confusing 😩  Maybe @rrousselGit  can clarify some things here :)

**Comment by rrousselGit** [comment]
This is voluntary. 
If we compare a Component and a Widget, they have roughly the same life-cycles:

- didMount / initState
- didUpdate / didUpdateWidget
- willUnmount / dispose

`useEffect` is a fusion of all the tree life-cycles into one simple API.

But here's the catch: Flutter vs React behave differently.

`didMount` & `didUpdate` are called _after_ the render
`initState` & `didUpdateWidget` are called _before_ the render

Similarly, when unmounting a Component tree, React will call `willUnmount` on parents first and go down the tree.
But Flutter does the opposite. It calls `dispose` on leaves first and goes up the tree.


As such, I made sure to preserve that subtle difference. This is important for peoples converting from a `StatefulWidget` to `HookWidget`. 

In fact, Flutter possesses no life-cycle that gets executed after the widget tree is mounted. 
Flutter may not need a `useAsyncEffect` at all

**Comment by smiLLe** [comment]
Thank you for this detailed explanation! 

The reason I found the differences between react and flutter was, that I was trying to implement the following react hook:
``` js
function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
}
```

Since useEffect (react) is called after render, the current render method uses the value of the previous render. 
I am not sure if can just add an addPostFrameCallback in flutter hooks useEffect() without introducing bugs.

``` dart
/// naive implementation ?!
T usePrevious<T>(T val) {
  final vn = useValueNotifier<T>(); // abusing as a ref
  useEffect( () {
    SchedulerBinding.addPostFrameCallback( () { vn.value = val; } );
  });
  return vn.value;
}
```

**Comment by rrousselGit** [comment]
Actually I was about to push an implementation of a `usePrevious`

Here it is


```dart
T usePrevious<T>(T val) {
  return Hook.use(_PreviousHook(val));
}

class _PreviousHook<T> extends Hook<T> {
  _PreviousHook(this.value);
 
  final T value;

  _PreviousHookState<T> createState() => _PreviousHookState();
}

class _PreviousHookState<T> extends HookState<T, _PreviousHook<T>> {
  T previous;

  @override
  void didUpdateHook() {
    previous = hook.value;
  }

  @override
  T build(BuildContext context) => previous;
}
```

**Comment by smiLLe** [comment]
Thank you :) 
I guess you are waiting for https://github.com/rrousselGit/flutter_hooks/pull/59 until you push a new version to pub?

I close this issue. Thanks a lot.

**Comment by rrousselGit** [comment]
Yes and no.

I'm supposed to finish the PR myself, but I've been a bit too tired recently

**Comment by aloisdeniel** [comment]
Apply to Google damn ! You do so much work for the community it should be you work time instead of consuming your spare time... It isn't possible to not see all the value you bring to the Flutter community.

**Comment by smiLLe** [comment]
I totally agree with @aloisdeniel 

@rrousselGit i think your usePrevious should set the previous property in didBuild rather than didUpdateHook.

``` dart
    final myState = useState(1);
    final prevMyState = usePrevious(myState.value);
    useEffect(() {
      if (myState.value != prevMyState) {
        // will only work if i use didBuild
      }
    });
```

**Comment by rrousselGit** [comment]
> I think your usePrevious should set the previous property in didBuild rather than didUpdateHook.

Sorry, it was a mistake in the code I gave (I wrote it directly on github without testing it... haha)


I updated it. The issue was `didUpdateHook` that used the current hook instead of the previous one.
Should be fixed

**Comment by Danopie** [comment]
> In fact, Flutter possesses no life-cycle that gets executed after the widget tree is mounted.
> Flutter may not need a useAsyncEffect at all

Can you elaborate a bit more on this @rrousselGit? 
Functionality wise, don't we still need to push routes, show dialogs, etc?

**Comment by rrousselGit** [comment]
Routes/Overlays are not pushed declaratively though.

If you want to show routes/overlays declaratively, this is not an async useEffect that you want, but something like https://github.com/rrousselGit/flutter_portal and Navigator 2.0

**Comment by Danopie** [comment]
Thank you I will check those out. A follow-up question is since imperative APIs in Routes/Overlays are still widely used, what would your recommended approach be? Here's my take on removing boilerplates like BlocBuilder and BlocListener with hooks which would benefit greatly from useAsyncEffect:

``` dart
    HookBuilder(
        builder: (context) {
          final counterState = useBloc<CounterBloc, CounterState>();

          // ignore: missing_return
          useEffect(() {
            if (counterState.count > 5) {
              Future.microtask(() {
                showDialog(
                    context: context,
                    builder: (_) => AlertDialog(
                          content: Text("Count has surpassed 5"),
                        ));
              });
            } else if (counterState.count == 10) {
              Future.microtask(() {
                NewRoute.show(context);
              });
            }
          }, [counterState]);

          return ...
        },
    )
```

**Comment by rrousselGit** [comment]
Instead of "useBloc", which causes rebuilds, you likely want a custom hook
for listening the bloc without rebuilding the widget

Like "useBlocListener(bloc, (value) {...})

**Comment by ben-xD** [comment]
I was wondering what line of code that being referred in the start of this thread, and here it is

https://github.com/rrousselGit/flutter_hooks/blob/e3c79da9df8468b7b771bb3bde093b1852529d9f/lib/src/hooks.dart#L682-L689
