### ISSUE TITLE
useStream bug in android release build

### ISSUE THREAD

**Issue by kafein** [rrousselGit/flutter_hooks#66]
Hi,

I try latest v0.3.0-dev.3 on my project. It works well in emulators (both IOS and Android) but in Android release build, application crashes. When i remove useStream and useEffect it works again. Error is something like "Boolean expression not be null". Not remembering exactly. 

Version 0.2.1 works well on release build.

By the way, great library. Thanks!

Flutter doctor output;

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.4.10, on Mac OS X 10.14.3 18D109, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] VS Code (version 1.33.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by rrousselGit** [comment]
I managed to reproduce it and found the issue.

Thanks for the report!
