### ISSUE TITLE
[Example] Infinite scroll pagination with Firestore using hooks

### ISSUE THREAD

**Issue by RollyPeres** [rrousselGit/flutter_hooks#67]
Please provide an example of using hooks together with Firestore, in order to achieve a real time paginated ListView of a Firestore collection.

The most common approach to pagination could be showcased by: 
- Having an initial loading spinner
- Hiding the spinner as soon as the first batch comes in
- Requesting a new batch of documents as soon as the user scroll down and hits the bottom of the list(a loading spinner could be shown here until the requested batch arrives)
- Having a message shown at the bottom of the list when we reach the end of Firestore's collection.

Preferably, the list should maintain it's real time functionality, meaning any additions, updates or deletes, should be reflected in the list.

**Comment by Solido** [comment]
Are you asking for someone to develop your app ?

**Comment by RollyPeres** [comment]
I've already built this feature with my custom implementation of the BLoC pattern, but I find hooks to be a really nice concept and this example would be a really cool showcase of how to use hooks. 

FYI, I've emailed Remi in regards to this and he asked me to create an example request. I'm sure this would be useful for a lot of people in general.

**Comment by rrousselGit** [comment]
FWIW don't expect something any time soon.

It's in my backlog, but I have other priorities. 
Overall I need to think of good documentation for hooks

**Comment by RollyPeres** [comment]
Ye, no worries. 

Maybe have some real world examples coupled with a detailed documentation, like auth, pagination, search, form & validation, etc.

**Comment by rrousselGit** [comment]
Closing this as I do not have the time to work on it
