### ISSUE TITLE
Cannot access state/hooks from local methods

### ISSUE THREAD

**Issue by bobmoff** [rrousselGit/flutter_hooks#73]
When using regular StatefulWidget I can access the state from any method as the variables are declared as class members, but when using HookWidget there is no way to access them as hooks may only be created (and stored in the scope of) in the build method.

Is there something that I am missing? Or do I have to send state along as arguments to any method that need to mutate it ?

**Comment by rrousselGit** [comment]
This is generally considered a bad practice to access the `State` class. It is an implementation detail. 

Instead you should explicitly expose the desired values through an Inheritedwidget (`provider` package?) or constructors.

**Comment by bobmoff** [comment]
Sorry for the late reply, but I don't follow what you mean that is bad practise to "access the state".

When using "flutter create" to setup a new project, the _MyHomePageState has a method called _incrementCounter that modifies the state of the widget. Is this bad practise?

Using a HookWidget, should methods on this object never be able to modify its own state ?

**Comment by rrousselGit** [comment]
Oh, that kind of access. I thought you talked about `ancestorStateOfExactType`, my bad.

With hooks you shouldn't use methods, and instead inline functions inside the build method:


```dart
class Foo extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final counter = useState(0);

    void incrementCounter() {
       counter.value++;
    }

    return RaisedButton(
      onPresssed: incrementCounter,
      child: Text(counter.value.toString()),
    );
  }
}
```

**Comment by bobmoff** [comment]
Ahh, ofc. Makes sense. Dont know why I didnt think of that.

Thanks for helping out!

**Comment by rrousselGit** [comment]
This reinforces the idea that a class is a bit pointless with hooks.

If you haven't already, I encourage you to give `functional_widget` a try!

**Comment by bobmoff** [comment]
I will check it out, thx

**Comment by stephenwil** [comment]
Hitting this issue myself, but figured the only way around it is to have functions, vars, etc defined within the build method.
Got an example of the functional_widget you mention?

**Comment by rrousselGit** [comment]
> figured the only way around it is to have functions, vars, etc defined within the build method.

That's expected. Do that.

**Comment by stephenwil** [comment]
Baby I haven't literally no idea what you're talking about, sorry.

Xx

**Comment by devwithmnasir** [comment]
> Oh, that kind of access. I thought you talked about `ancestorStateOfExactType`, my bad.
> 
> With hooks you shouldn't use methods, and instead inline functions inside the build method:
> 
> ```dart
> class Foo extends HookWidget {
>   @override
>   Widget build(BuildContext context) {
>     final counter = useState(0);
> 
>     void incrementCounter() {
>        counter.value++;
>     }
> 
>     return RaisedButton(
>       onPresssed: incrementCounter,
>       child: Text(counter.value.toString()),
>     );
>   }
> }
> ```

If we create our methods within the build method in Flutter, will it not impact performance because the method will be recreated every time the build method is called?

**Comment by dorklord23** [comment]
> > Oh, that kind of access. I thought you talked about `ancestorStateOfExactType`, my bad.
> > With hooks you shouldn't use methods, and instead inline functions inside the build method:
> > ```dart
> > class Foo extends HookWidget {
> >   @override
> >   Widget build(BuildContext context) {
> >     final counter = useState(0);
> > 
> >     void incrementCounter() {
> >        counter.value++;
> >     }
> > 
> >     return RaisedButton(
> >       onPresssed: incrementCounter,
> >       child: Text(counter.value.toString()),
> >     );
> >   }
> > }
> > ```
> 
> If we create our methods within the build method in Flutter, will it not impact performance because the method will be recreated every time the build method is called?

I saw a similar SO question and the answers unanimously said it's a bad practice.
