### ISSUE TITLE
build method called repeatedly with useStream and dynamically created streams.

### ISSUE THREAD

**Issue by modulovalue** [rrousselGit/flutter_hooks#82]
I wanted to replace the following snippet
```dart
Observable<int> someStream() => Observable.just(1);

return StreamBuilder<int>(
    builder: (context, snapshot) {
        stream: someStream(),
        return Text(snapshot.toString());
    }
);
```
with
```dart
Observable<int> someStream() => Observable.just(1);

return Text(useStream(someStream()).toString()); /// also tried it with preserveState = false
```

And the hooks way of doing this constantly rebuilds my widget as if I'd be calling setState on every build. Is this expected?

Thanks.

I'm on 0.3.0

**Comment by rrousselGit** [comment]
This is expected. 
Every time your _build_ method is called, you create a new stream instance.

This can cause a lot of issues, such as losing your state when opening the keyboard.

You should instead memoize the instance of stream such that it is not recreated everytimes:


```dart
final stream = useMemoized(() => Observable.just(1));

return Text(useStream(stream).toString());
```
