### ISSUE TITLE
Move flutter_mobx_hooks to this repository

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/flutter_hooks#83]

**Comment by smkhalsa** [comment]
@rrousselGit where is this package currently located? I noticed that it was [deleted](https://github.com/mobxjs/mobx.dart/pull/172) from mobx.

**Comment by rrousselGit** [comment]
It is currently located on my mobx fork [here](https://github.com/rrousselGit/mobx.dart/tree/backup/flutter_mobx_hooks)

**Comment by smiLLe** [comment]
Hi Remi. Do you want flutter_mobx_hooks located in flutter_hooks or as a separate repo? Or do you accept PR in the fork you made?

**Comment by rrousselGit** [comment]
It should be on this repo. You can make a PR. The folder architecture should match `provider`

**Comment by rrousselGit** [comment]
Closing this. In the end, I don't need it as I use a different architecture.

If people still want it, feel free to open a PR or make a separate package
