### ISSUE TITLE
Use with standard Stateful / Stateless components

### ISSUE THREAD

**Issue by smkhalsa** [rrousselGit/flutter_hooks#88]
@rrousselGit Are you exploring using ComponentElement as mentioned in [your comment](https://github.com/flutter/flutter/issues/25280#issuecomment-456403184) on the flutter repo?

I'd like to be able to use hooks on normal stateful / stateless components.

**Comment by rrousselGit** [comment]
That is not something possible as a package.
For this to work, hooks must be included directly in flutter.
