### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by modulovalue** [rrousselGit/flutter_hooks#90]
```
flutter: setState() called after dispose(): _HookWidgetState#e2545(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback. The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose(). with ...
```

> To avoid memory leaks, consider breaking the reference to this object during dispose()

Sometimes, the reference can't be broken without a lot of boilerplate for example when a Future is used.

Currently, there is no `mounted` property in `HookState`, is this intentional?

**Comment by rrousselGit** [comment]
Consider using `CancelableOperation` from [async](https://pub.dev/packages/async) package

**Comment by modulovalue** [comment]
Could you please answer the question.

> is this intentional?

I don't see the reason why hooks should hide the mounted property when `State` doesn't.

Yes, I know, it is considered 'a hack' to check for mounted, but it is also [...an error to call setState unless mounted is true.](https://api.flutter.dev/flutter/widgets/State/mounted.html) and hooks violate that.

**Comment by rrousselGit** [comment]
I didn't need it, so I didn't to it. Free free to make a PR if you want.

> hooks violate that.

They don't. All of the existing hooks correctly handle that behavior. Even `useFuture`

**Comment by modulovalue** [comment]
Yes, you're right, my wording was too imprecise. Existing hooks do not violate that but some classic 'State' code could be ported easier to a hook with an existing mounted property.

I'll reevaluate my use of Hook.setState and will open a PR if still needed. thanks.
