### ISSUE TITLE
Issue on Pub?

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/flutter_hooks#95]
Couldn't find hooks on pub today after a bit of searching until I got to like the fourth page (searched for "hooks"). Looks like the library has been tagged with `[UNIDENTIFIED]` and has a [couple of issues](https://pub.dev/packages/flutter_hooks#-analysis-tab-)

Apologies if you were already aware of this

**Comment by rrousselGit** [comment]
Thanks!

Sadly the issue is on pub. It uses an older version of the stable release, which hooks don't support anymore.

**Comment by rrousselGit** [comment]
Related: https://github.com/dart-lang/pub-dev/issues/2283
