### ISSUE TITLE
Provide an example for useReducer for managing local state

### ISSUE THREAD

**Issue by TanaseHagi** [rrousselGit/flutter_hooks#96]
I'm trying to create a simple demo for useReducer for managing local state.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage2(title: 'Flutter Demo Home Page'),
    );
  }
}

class State {
  int counter = 0;
}

class IncrementAction {
  int count;
  IncrementAction({this.count});
}

class MyHomePage2 extends HookWidget {
  MyHomePage2({Key key, this.title}) : super(key: key);

  final String title;

  final State initialState = State();

  State reducer(State state, action) {
    if (action is IncrementAction) {
      state.counter = state.counter + action.count;
    }
    return state;
  }

  @override
  Widget build(BuildContext context) {
    final _store = useReducer(reducer, initialState: initialState);
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '${_store.state.counter}',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _store.dispatch(IncrementAction(count: 1)),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

In the example above, the reducer gets called, the state gets updated, but the widget does not rerender. 

Sorry if this seems like a question to be asked on stackoverflow, I could not find an example, I would like to donate my example to the docs after it gets fixed. :-)

Thanks

**Comment by rich-j** [comment]
@TanaseHagi - I didn't run your example, but it probably "does not rerender" because you are mutating `State` instead of creating a new `State` as is expected when using a "redux" like pattern.

Your "reducer" function needs to return a *new* `State` object:

    State reducer(State state, action) {
      if (action is IncrementAction) {
        return State(counter: state.counter + action.count);
      }
      return state;
    }

It's helpful and more concise to declare your "state" as immutable (note the use of `final`) to avoid inadvertent data mutation. You could declare `State` like:

    class State {
      final int counter;
      State({this.counter=0});
    }

Your "action" could also be immutable:
 
    class IncrementAction {
      final int count;
      IncrementAction({this.count=1});
    }

**Comment by TanaseHagi** [comment]
@rich-j That works now. Thanks.

**Comment by gochev** [comment]
not clear how to dispatch from child component that doesnt have access to the _store or reducer.
