### ISSUE TITLE
Dealing with lists

### ISSUE THREAD

**Issue by jascodes** [rrousselGit/flutter_hooks#97]
Updating state of object of type `List<T>` either by **direct assignment** with new List or direct mutation; does't rebuild widget tree. I am currently after updating list, use notify listeners.

Thx

**Comment by rrousselGit** [comment]
Do you have an example?

**Comment by jascodes** [comment]
Something like, 
```
final x = useState([true,false])
```

Here's list of booleans, if I do
```
x.value[0]=false;
```
or
```
x.value[0]=false;
x.value = x.value; // trying to trigger rebuild
```
But it won't rebuild for me..
What works for me is below.
```
x.value[0]=false;
x.notifyListners(); // this triggers update **but give me warning**  
```

Thx

**Comment by rrousselGit** [comment]
The state is supposed to be immutable.
You should not mutate the list, but create a new one with updated content instead.

**Comment by jascodes** [comment]
What do you mean?
```
x.value = [true,true];
```
Even this doesn't work for me...
Read my initial issue description

> Updating state of object of type List<T> either by direct assignment

Can you give me working example of useState using list?

Thx

**Comment by DennisOosterling** [comment]
@jascodes and future people having this problem

He means that you have to assign a new list to the state value. Otherwise it will still be the same array and not notify the listeners.

``` dart
final numbers = useState(<int>[]);

void changeNumbers() {
      List<int> newNumbers = List.from(numbers.value);
      newNumbers.add(1);
      numbers.value = newNumbers;
}
```

**Comment by callmejm** [comment]
@DennisOosterling Hi, for add new value is `numbers.value = [...numbers.value, 1];` , how about remove value
